### ISSUE TITLE
新功能建议： 添加并显示文章、标签和分类的数量，以及点击标签和分类后显示导航信息

### ISSUE THREAD

**Issue by zhekunren** [Candinya/Kratos-Rebirth#100]
1. **您的新功能建议是由使用时出现的不便引发的吗？**

① 添加文章、标签和分类的数量统计，并在avatar的下方显示，会让自己和读者对站内的内容更加清晰。效果类似于[icarus](https://ppoffice.github.io/hexo-theme-icarus/)界面，如图1所示。

<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图1-hexo-theme-icarus-countshow.PNG width=40% alt="图1" title="图1" />
</br>图1
</p>

我目前希望添加的位置可见博客[zhekunのblog](https://zhekunren.github.io/)，如图2所示。

<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图2-myaboutshow.PNG width=40% alt="图2" title="图2" />
</br>图2
</p>

② 点击标签和分类后显示导航信息，是为了便于点击标签和分类后的阅读体验，效果同样见[icarus](https://ppoffice.github.io/hexo-theme-icarus/)。即添加类似于图3的导航信息。

<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图3-hexo-theme-icarus-tags-Demo.PNG width=40% alt="图3" title="图3" />
</br>图3
</p>

2. **请描述您所设想的功能或是解决方案**

3. **补充内容:**

感谢大佬开发了这么nice的主题👍。

**Comment by Candinya** [comment]
✅  in 88571c682bed2c780406a18ad8ed488644f6499f

**Comment by zhekunren** [comment]
哇偶 反馈太快了 厉害👍
