### ISSUE TITLE
Bug 回报：采用Disqus时，link post评论区不显示

### ISSUE THREAD

**Issue by zhekunren** [Candinya/Kratos-Rebirth#102]
1. **对Bug的描述:**

首先，已经将theme的评论配置为了Disqus。其他文章均正常显示评论区。而[link post](https://zhekunren.github.io/archives/6297e43c.html)在导航界面显示有“留言”，点击进入后，没有显示评论区，效果如图1和2所示。

<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图1-linkpost.PNG width=80% alt="图1" title="图1" />
</br>图1
</p>
<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图2-linkpost.PNG width=80% alt="图2" title="图2" />
</br>图2
</p>

link post的配置信息如下。
```
---
title: www.google.com
link: https://www.google.com
date: 2022-02-14 10:45:00
updated: 2022-02-14 10:45:00
tags:
  - hexo
  - blog-test
categories: 
  - [软件工具,Hexo]

toc: true
abbrlink: 6297e43c
pic: 

password: ''
abstract: 'Here''s something encrypted, password is required to continue reading.'
message: 'Hey, password is required here.'
wrong_pass_message: 'Oh, this is an invalid password. Check and try again, please.'
wrong_hash_message: 'Oh, these decrypted content cannot be verified, but you can still have a look.'
theme: Blink

comments:  true
# only:
# # - home
# # - category
# # - tag
# # - none
sticky: -1 # 默认值为0，设置-1表示置底，设置正数值越大优先级越高

excerpt: ""
---
```

2. **复现Bug的方法:**

3. **期望的行为:**

4. **相关的截图:**

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

 - 操作系统: Window 10
 - 浏览器: Microsoft Edge
 
6. **您的配置文件:**

7. **补充内容:**

**Comment by Candinya** [comment]
link post 默认情况下不该有评论区，但是考虑到主题的定制化需求，会推送一个修复来确保开启了评论区的 link post 也可以看到评论区

**Comment by zhekunren** [comment]
好的 谢谢大佬解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nya ***@***.***&gt;; 
发送时间: 2022年2月19日(星期六) 下午5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Candinya/Kratos-Rebirth] Bug 回报：采用Disqus时，link post评论区不显示 (Issue #102)





 
link post 默认情况下不该有评论区，但是考虑到主题的定制化需求，会推送一个修复来确保开启了评论区的 link post 也可以看到评论区
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
