### ISSUE TITLE
Bug 回报：categories在darkmode图标颜色问题，以及多级分类目录在breadcrumb处跳转出现404的问题

### ISSUE THREAD

**Issue by zhekunren** [Candinya/Kratos-Rebirth#104]
1. **对Bug的描述:**

①.categories在darkmode图标颜色问题，如下图1。

<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图1-categories.PNG width=30% alt="图1" title="图1" />
</br>图1
</p>

②.breadcrumb处链接问题。
breadcrumb处只显示了最终的分类目录，点击链接跳转时也是直接跳转最终的分类目录，忽略了上一级的分类目录，导致跳转链接不对，如下图2。
<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图2-breadcrumb1-20220221.PNG width=80% alt="图2" title="图2" />
</br>图2
</p>
此外，当显示界面较小时（比如手机），会发现breadcrumb界面和banner界面都有网站名字（见图3），建议删除breadcrumb处的网站名。
<p align="center">
    <img src=https://cdn.jsdelivr.net/gh/zhekunren/blog_image/img/issuresUse/图3-breadcrumb2-20220221.PNG width=80% alt="图3" title="图3" />
</br>图3
</p>

2. **复现Bug的方法:**

3. **期望的行为:**

4. **相关的截图:**

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

6. **您的配置文件:**

7. **补充内容:**

我的网站链接[zhekunのblog](https://zhekunren.github.io/)

**Comment by Candinya** [comment]
应该已经修复，您可以拉取最新的代码进行测试

**Comment by zhekunren** [comment]
好的 等下测试 谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nya ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Candinya/Kratos-Rebirth] Bug 回报：categories在darkmode图标颜色问题，以及多级分类目录在breadcrumb处跳转出现404的问题 (Issue #104)





 
应该已经修复，您可以拉取最新的代码进行测试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhekunren** [comment]
更新后没问题了👍
