### ISSUE TITLE
vercel部署出错

### ISSUE THREAD

**Issue by JesseJeson** [Candinya/Kratos-Rebirth#105]
![image](https://user-images.githubusercontent.com/55904993/155868675-5448287e-6431-445e-beb7-3e680a40eedc.png)

**Comment by Candinya** [comment]
1. 请遵循模板格式
2. 请给出详细的复现步骤
3. 请确认您已认真阅读 ReadMe.md 中的 [💞 安装使用](https://github.com/Candinya/Kratos-Rebirth#-%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8) 部分

**Comment by Candinya** [comment]
> 抱歉，似乎是在git的时候把主题的config误删了，感谢！

没事，问题解决了就好 🎉

**Comment by Candinya** [comment]
以及应该并不是误删，为了防止主题配置被上传，主题配置是写到 .gitignore 里面的（被忽略的文件），您可能需要手动添加一下

**Comment by JesseJeson** [comment]
哦哦，感谢！
