### ISSUE TITLE
文章页面说明中的“文章资源文件夹”是哪。。。

### ISSUE THREAD

**Issue by VladmirLin** [Candinya/Kratos-Rebirth#106]
并不知道F12所得的图片地址指向哪里（

**Comment by Candinya** [comment]
是指 资源文件夹 ，可以参见 Hexo 官方文档 [资源文件夹](https://hexo.io/zh-cn/docs/asset-folders)

**Comment by VladmirLin** [comment]
F12检查封面（通过 pic: spirit.JFIF 声明）路径为
<img class="kratos-entry-thumb-new-img" src="/Blog-basic/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E7%AE%80%E8%BF%B0.htmlspirit.JFIF">
与在文章中引用资源文件夹内图片( ![](spirit.JFIF ))所得
<img src="/Blog-basic/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E7%AE%80%E8%BF%B0/spirit.JFIF" alt="test">
不同，无法显示封面图像，或与封面路径中html后缀有关？

> 是指 资源文件夹 ，可以参见 Hexo 官方文档 [资源文件夹](https://hexo.io/zh-cn/docs/asset-folders)

**Comment by Candinya** [comment]
> F12检查封面（通过 pic: spirit.JFIF 声明）路径为 img class="kratos-entry-thumb-new-img" src="/Blog-basic/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E7%AE%80%E8%BF%B0.htmlspirit.JFIF" 与在文章中引用资源文件夹内图片( ![](spirit.JFIF))所得 img src="/Blog-basic/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E7%AE%80%E8%BF%B0/spirit.JFIF" alt="test" 不同，文章内图像可以正常显示而封面图像不显示，或与封面路径中html后缀有关？
> 
> > 是指 资源文件夹 ，可以参见 Hexo 官方文档 [资源文件夹](https://hexo.io/zh-cn/docs/asset-folders)

看起来是个 bug ，可以按照 Bug 上报的格式模板帮忙提供一下信息，以便这边的复现吗，非常感谢

**Comment by Candinya** [comment]
跟进 #107
