### ISSUE TITLE
自定义的封面图片不能正常显示

### ISSUE THREAD

**Issue by VladmirLin** [Candinya/Kratos-Rebirth#107]
**对Bug的描述:**
通过 pic: spirit.JFIF 声明封面，在localhost与giteepages中自定义封面不能正常显示，检查封面路径为
img class="kratos-entry-thumb-new-img" src="/Blog-basic/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E7%AE%80%E8%BF%B0.htmlspirit.JFIF"
同一图片可在文章中正常显示，路径为
img src="/Blog-basic/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E7%AE%80%E8%BF%B0/spirit.JFIF" alt="test"

 **复现Bug的方法:**
1 注释jsconfig 中pic部分
2 在front matter中声明pic: xxx.jpg，xxx.jpg放入资源文件夹；在文章内![](xxx.jpg)引用同一图片
3 hexo g生成页面
4 hexo s 所得页面中封面图片无法正常显示，文章内图片可以正常显示

 **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

**Comment by Candinya** [comment]
确认是主题处理不严谨的问题，因为这个图片使用的是手动拼合路径的方式，所以在非站点默认路径配置下会出现错误
正在研究修复的方案 👀 
![image](https://user-images.githubusercontent.com/20502130/156866386-afa8fa64-236f-4c1c-bda9-198135df8e31.png)

**Comment by Candinya** [comment]
最新的代码尝试进行了兼容性修复，您可以尝试拉取一下看看是否能正常工作

**Comment by Candinya** [comment]
您好，请问问题能得到解决吗 👀

**Comment by Candinya** [comment]
由于该 issue 较长时间处于不活跃状态，因而暂行关闭，如有任何跟进您可随时重新开启，非常感谢您的帮助。
