### ISSUE TITLE
Bug 回报：（先版本的bug,hexo s就报错了

### ISSUE THREAD

**Issue by barry200890** [Candinya/Kratos-Rebirth#111]
0. **报告前须知**
ERROR {
  err: SyntaxError: Unexpected token '.' in D:\data\blog\themes\kratos-rebirth\l
ayout\_partial\head.ejs while compiling ejs

- [ ] 我确认该Bug是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [ ] 我确认已认真阅读 ReadMe.md 和文档，确认描述的内容有误或是不能解决我的问题
- [ ] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

1. **对Bug的描述:**

2. **复现Bug的方法:**

3. **期望的行为:**

4. **相关的截图:**

ERROR {
  err: SyntaxError: Unexpected token '.' in D:\data\blog\themes\kratos-rebirth\l
ayout\_partial\head.ejs while compiling ejs

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

6. **您的配置文件:**

7. **补充内容:**

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/161432488-2c291f2d-301a-4130-9cd4-a135e4e7fc64.png)

**Comment by Candinya** [comment]
您好，请问您的问题是否已经得到了解决呢
