### ISSUE TITLE
Aplayer好像无法展示了

### ISSUE THREAD

**Issue by hcxx** [Candinya/Kratos-Rebirth#112]
如题

**Comment by Candinya** [comment]
我站用 MetingJS 的 aplayer 也没了，估计是 meting 他们服务器问题，明天再看看吧

**Comment by hcxx** [comment]
> 我站用 MetingJS 的 aplayer 也没了，估计是 meting 他们服务器问题，明天再看看吧

好的，谢谢糖喵大佬。

**Comment by hcxx** [comment]
好像Meetingjs已经修复了，可以正常使用了。
