### ISSUE TITLE
主题版本更新后，文章中的标题变成了浅灰色

### ISSUE THREAD

**Issue by xhege** [Candinya/Kratos-Rebirth#119]
1. **对Bug的描述:**
主题更新到最新版本后，电脑和手机端的文章所有标题变成都了浅灰色，不是原本的深黑色加粗标题体了

4. **期望的行为:**
希望可以修复原本标题应有的显示效果

5. **相关的截图:**

![](https://cdn.jsdelivr.net/gh/xhege/xhg-images/Snipaste_2022-04-10_17-17-01.jpg)
![](https://cdn.jsdelivr.net/gh/xhege/xhg-images/c12a92614584af08dfb0b9cbc3162ba.jpg)

6. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

7. **您的配置文件:**
# 主题：
# Global 全局配置
site_analytics: 
site_logo: /images/favicon.webp
snow: false
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
cdn: unpkg # 请注意这里是静态资源的 CDN 来源，图片的 CDN 在下方 jsconfig.main.pic.CDN 段配置
check_update: true

# 自定义样式
customStyles:
  images: # 图片相关设置
    banner: /images/banner.webp # 站点横幅
    background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  new:
    submenu: true
    youxi: /categories/单机游戏/
    ware: /categories/电脑软件/
    Android: /categories/手机软件/
    Java: /categories/编程技术/
  archives: /archives/
  contact: /contact/
  about: /about/
#  friends: /friends/
  sites:
    submenu: true
    author: https://mp.weixin.qq.com/s/W5trOUAEyeaTxEtP1mEHXQ
    project: https://jq.qq.com/?_wv=1027&k=d1YSH37A
  search: /search/

label:
  index: <i class="fa fa-home"></i>首页
  new: 
    submenu: <i class="fa fa-th-large"></i>分类
    youxi: 单机游戏
    ware: 电脑软件
    Android: 手机软件
    Java: 编程技术
  archives: <i class="fa fa-archive"></i>文章
  contact: <i class="fa fa-pencil-square-o"></i>留言板
  about: <i class="fa fa-paper-plane"></i>关于我
#  friends: <i class="fa fa-paw"></i>好伙伴
  sites:
    submenu: <i class="fa fa-list"></i>更多
    author: 微信公众号
    project: QQ群
  search: <i class="fa fa-search"></i>搜索

# Footer 页脚配置
group_link: https://qm.qq.com/cgi-bin/qm/qr?k=AcRDKZ03JwFUffMzFGJZkm0eiungjnN_&authKey=RvpN3SwOKbIdKVYI%2F1sMAwJWww2b74vAHDVNpBG86OEPKGjiCthHk2BW3Id%2B2MM0&noverify=0&group_code=1040610096
contact:
  weibo: 
  mail: 
  telegram: # CandyUnion
  twitter: 
  facebook: 
  linkedin: 
  fediverse:
    instance: # nya.one
    username: # Candinya
  github: # Candinya
  rss:
timenotice: 本站已在风雨中度过
icp: 豫ICP备2021024515号-1
psr:  41012202000323
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: true
  share: true
  comments: 
    provider: waline
    enableBGImage: true

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: https://blog-m6z684kp2-xhege.vercel.app #后端服务器地址，必填
  visitor: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'Kratos-Rebirth-Demo'
  owner: 'Candinya'
  admin: 
    - 'Candinya'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Candinya'
  repo: 'Kratos-Rebirth-Demo'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid:

# APlayer 左下角音乐播放器
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 3204190542
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/avatar.webp
mobile_toc: 
  hide: false
  hide_id: true

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    pic:
      CDN: false # 表示使用 CDN 加载图片
      random_amount: 20 # 表示从1~20
      filename: "images/thumb/thumb_{no}.webp" # 相对于主题根目录，表示文件名的格式, {no} 用以指代随机的编号。
                                              # 如果包含 // 表示使用指定域名的绝对路径（例如第三方图床服务等），那么会忽略 CDN 选项
    createTime: "2022/01/04 08:00:00"
    donateBtn: "支持我~"
    scanNotice: "感谢支持"
    qr_alipay: "/images/wechatpayqr.webp"
    qr_wechat: "/images/alipayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# 站点配置：
url: http://xhgblog.club
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
  abbrlink:
  alg: crc32 # 算法：crc16(default) and crc32
  rep: hex # 进制：dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

8. **补充内容:**

**Comment by xhege** [comment]
还有一个问题，我用的是Waline评论系统，今天发现网站首页和文章里的阅读量和评论数量不显示了，不知道是哪方面的出问题呢？

**Comment by Candinya** [comment]
应该是样式文件调整的时候出现了丢失，会跟进检查
Waline 评论丢失这里也有出现，可能是主题加载调整时候出现了错误，也会继续跟进
非常感谢您的提示 👏

**Comment by Candinya** [comment]
应该在 v1.8.1 修复了，您可以尝试更新一下来看看，非常感谢您的支持！

**Comment by xhege** [comment]
好的，修复速度真快，牛逼！
