### ISSUE TITLE
可以开关CDN及其预加载

### ISSUE THREAD

**Issue by earthcry** [Candinya/Kratos-Rebirth#121]
首先，谢谢您的这么棒的主题。

但，在内网使用的话，
一直CDN，网页打不开或打开很慢。

希望有可能的话，可以设置CDN开关，彻底关闭，不要预加载。

我不会coding.

**Comment by Candinya** [comment]
默认情况下站点静态资源应该就是无 CDN 模式，您可以检查配置文件的（样例模板中）第 9 行，设置为 `cdn: false` 即可；对于无图片文章默认使用的替代图片的 CDN 配置在 （样例模板中）第 167 行，您也可以手动关闭该 CDN 选项（设置 `CDN: false`）。

**Comment by ArcticLampyrid** [comment]
> 默认情况下站点静态资源应该就是无 CDN 模式

好像外部组件会始终从CDN获取
```ejs
<link rel="stylesheet" id="fontawe-css" href="<%- url_npm_cdn('font-awesome@4.7.0/css/font-awesome.min.css') %>" type="text/css" media="all">
<link rel="stylesheet" id="nprogress-css" href="<%- url_npm_cdn('nprogress@0.2.0/nprogress.css') %>" type="text/css" media="all">
<script defer src="<%- url_npm_cdn('bootstrap@3.3.4/dist/js/bootstrap.min.js') %>"></script>
<script defer src="<%- url_npm_cdn('nprogress@0.2.0/nprogress.js') %>"></script>
<script defer src="<%- url_npm_cdn('aplayer@1.10.1/dist/APlayer.min.js') %>"></script>
<script defer src="<%- url_npm_cdn('@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js') %>"></script>
<script defer src="<%- url_npm_cdn('layui-src@2.5.5/dist/layui.all.js') %>"></script>
// ......
```

**Comment by alhricke** [comment]
cdn.jsdelivr.net于5/17日开始又无法访问了，鉴于此，最好感觉能把css，js等文件放到本地加载，或者添加更多的cdn渠道

**Comment by Candinya** [comment]
> 好像外部组件会始终从CDN获取

有道理，可以统一一下 CDN 控制 ✅

**Comment by Candinya** [comment]
现在拉取 master 分支的主题可以通过设置 `cdn: false` 来统一关闭资源 CDN 了（包括图片CDN），在确定依赖完整加载没问题之后会发版，有任何问题欢迎随时跟进

**Comment by ArcticLampyrid** [comment]
可能需要更细粒度的cdn控制
比如我自己的使用，为了便于定制细节，我对样式等有些微调，需要`cdn: false`
但是对于第三方组件库则希望完全从cdn获取

另外，使用通用cdn地址而不是自行保管的cdn有利于缓存（包括浏览器端、CDN节点预热等）等场景

**Comment by Candinya** [comment]
现在发布的版本可以用更精细的 CDN 粒度控制了，请注意文章封面随机图片的相关参数发生了变更 （具体可以参见 #137 和 [样例的配置文件](https://github.com/Candinya/Kratos-Rebirth/blob/master/.demo/_config.kratos-rebirth.yml) ） ，非常感谢 @ArcticLampyrid

**Comment by earthcry** [comment]
关了，关不了，有预加载。



| |
mlinks
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Nya ***@***.***> |
| 日期 | 2022年04月13日 00:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Candinya/Kratos-Rebirth] 可以开关CDN及其预加载 (Issue #121) |

默认情况下站点静态资源应该就是无 CDN 模式，您可以检查配置文件的（样例模板中）第 9 行，设置为 cdn: false 即可；对于无图片文章默认使用的替代图片的 CDN 配置在 （样例模板中）第 167 行，您也可以手动关闭该 CDN 选项（设置 CDN: false）。
