### ISSUE TITLE
功能建议：私密文章

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#122]
* [相关参考](https://zhuanlan.zhihu.com/p/113235573)
只是很好奇怎么实现

**Comment by xhege** [comment]
你说的应该是给文章加个密码吧，之前大佬在评论区说过，自己安装一个插件就可以实现了，插件是：hexo-blog-encrypt，插件作者的GitHub地址：https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md
GitHub项目地址里有详细配置教程的

**Comment by greenhandzdl** [comment]
> 你说的应该是给文章加个密码吧，之前大佬在评论区说过，自己安装一个插件就可以实现了，插件是：hexo-blog-encrypt，插件作者的GitHub地址：https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md GitHub项目地址里有详细配置教程的

抱歉，那篇教程已经过期，我以为要替换主题文件的
