### ISSUE TITLE
博客Waline评论不显示

### ISSUE THREAD

**Issue by xhege** [Candinya/Kratos-Rebirth#125]
0. **报告前须知**

- [ ] 我确认该Bug是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [ ] 我确认已认真阅读 ReadMe.md 和文档，确认描述的内容有误或是不能解决我的问题
- [ ] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

1. **对Bug的描述:**
博客文章末尾的评论系统Waline加载不出来，无法评论留言，文章阅读量和评论数也不显示了

**Comment by Candinya** [comment]
0. 如果可以的话希望您能仔细阅读 Bug 上报模板 中的每一个字，如果某个部分没有内容，您可以将其留空，而不是删除它，以避免我们认为您没有看到这个部分。
1. 如果可以的话希望您能附上您的配置文件（或是其中和评论相关的部分），如果有控制台报错也可以一并贴上，方便我们排查问题。
2. 请注意主题的评论管理有一定的配置样式变更，但也有对应的回落策略以向下兼容，我们需要细节的配置信息 / 报错信息来定位您可能出现的配置异常。

**Comment by Candinya** [comment]
稍等，是可以复现的问题，这边查询到 unpkg 的 CDN 出现了 `Cannot find "/dist/Waline.min.js" in @waline/client@2.0.3` 的报错，这边会继续跟进相关的情况

**Comment by Candinya** [comment]
暂时在 b06e1bd80348e3ec2a4c618d5e8371896e693d1a 中锁定了 waline 版本为 v1 ， v2 目前测试发现有很多功能性变化需要进行调整，会在 #126 继续跟进更新

**Comment by xhege** [comment]
没看太懂，意思是把
![image](https://user-images.githubusercontent.com/65748515/165680220-7ec76acc-906f-466f-ab79-3d1ad25996ef.png)
这里面的代码和本地的waline.ejs文件对应代码替换一下就好了吗？

**Comment by Candinya** [comment]
对的，暂时加上那个 `@1` 可以缓解 waline 不可用的问题，如果您使用的是 git 拉取的主题，您也可以在主题目录下使用 git pull 来拉取升级
进一步的兼容性调整（迁移到 waline v2）会在 #126 中跟进，现在因为他们也才升级不久，存在一些不稳定的部分（本地调试时候发现缺失了一些功能，需要进一部测试）
