### ISSUE TITLE
加密的文章，输入密码回车确认没有反应

### ISSUE THREAD

**Issue by xhege** [Candinya/Kratos-Rebirth#127]
1. **对Bug的描述:**

最近发现一个问题，网站使用了hexo-blog-encrypt加密的文章，第一次进入文章输入不管密码是否正确，怎么按回车键都没有任何反应，只有刷新一次网页重新输入后才有反应，每次进入都是这样，我试了大佬你的加密文章也是这种情况，相反插件作者的测试页面没有这种情况，不知道是哪方面的问题呢？

**Comment by Candinya** [comment]
似乎是 hexo-blog-encrypt 所需的 script 在 pjax 之后没有被加载，会进一步研究相关的兼容性问题

未加载举例：
![image](https://user-images.githubusercontent.com/20502130/166112809-04149d91-244f-4717-a2bf-902e4f861c77.png)

正确加载举例：
![image](https://user-images.githubusercontent.com/20502130/166112822-eb8833af-7575-454a-8ab4-d75d55a7e7f8.png)

**Comment by xhege** [comment]
好的，谢谢大佬，不好意思，这么晚打扰您了😃
