### ISSUE TITLE
Change npm package name to `hexo-theme-kratos-rebirth`

### ISSUE THREAD

**Issue by ArcticLampyrid** [Candinya/Kratos-Rebirth#129]
Hexo v5.0 以上支持使用 npm 包形式引用主题，但需要遵守特定命名格式，如 `hexo-theme-` 前缀
See also [通过 npm 安装主题](https://blog.skk.moe/post/hexo-5/#%E9%80%9A%E8%BF%87-npm-%E5%AE%89%E8%A3%85%E4%B8%BB%E9%A2%98)

p.s. 为了在使用 npm 包时兼顾自定义性，可能需要改变一些与配置相关的东西
如当前最佳的custom background方式实际上是直接替换相关图片文件（这比注入`<style>`更简洁，且支持dark主题等等）

**Comment by ArcticLampyrid** [comment]
出于依赖稳定性考虑，npm不允许对已发布的包进行操作。
根据社区推荐方案，首先使用`npm deprecate`弃用老的npm包，然后使用新名称publish
```bash
npm deprecate ${oldName}@"<=${version}" "WARNING: This project has been renamed to ${newName}. Install using ${newName} instead."
```

**Comment by Candinya** [comment]
`custom background` 担心的是这种 npm / yarn 安装方式的用户没法修改源文件，所以有这样一个奇怪的妥协接口 🧐

**Comment by Candinya** [comment]
包名也改好了 🎉 
为了庆祝直接升级了一个大版本（逃x

**Comment by ArcticLampyrid** [comment]
虽然但是，好像发得太快了
还得再发一个 Candinya/Kratos-Rebirth@bedf8701814ef6a3a4f7747b483cd1b15bd1ddbd

**Comment by Candinya** [comment]
oops (

**Comment by Candinya** [comment]
直接推了个新包 + 修改了 release tag（逃x
