### ISSUE TITLE
优化Status类型内容的SEO

### ISSUE THREAD

**Issue by ArcticLampyrid** [Candinya/Kratos-Rebirth#132]
Google:
![image](https://user-images.githubusercontent.com/9017609/172083251-1ed7491d-effd-464d-9b3a-e25c8495ad37.png)

**Comment by Candinya** [comment]
caefdee72e4b0591c4a4803f03ec2f89dbc0f3df 默认把 status 的过期提示禁用掉了，也许会稍微好一点（毕竟对 status 来说本来就是发生的过期的小记录） 🤔
