### ISSUE TITLE
新功能建议： 优化顶栏菜单在配置文件中的写法

### ISSUE THREAD

**Issue by Candinya** [Candinya/Kratos-Rebirth#133]
0. **报告前须知**

- [x] 我已确认该功能确实不存在
- [x] 我会认真详细地描述清楚我想要的功能

1. **您的新功能建议是由使用时出现的不便引发的吗？**

是，因为原来这种 object 写法是在完全不懂 yaml 语法时候瞎整出来的，现在觉得实在太难看了

2. **请描述您所设想的功能或是解决方案**

改成 
``` ts
topMenu: Array<{
  label: String;
  icon?: String; // Select from FontAwesome@4.7.0
  url?: String;
  submenu?: Array<{
    label: String;
    icon?: String; // Select from FontAwesome@4.7.0
    url: String
  }>
}> 
```
写法

3. **补充内容:**

1. 一级菜单中如果有 submenu 就会无视 url ，没有就会作为单独一项的 url
2. 保留向下兼容性，如果 `topMenu` 配置项存在则覆盖老一套的配置逻辑，不存在就还是使用老一套的

**Comment by ArcticLampyrid** [comment]
可以再加个 `icon: string`

**Comment by Candinya** [comment]
> 可以再加个 `icon: string`

有道理，强调一下 icon 的重要性 😯

**Comment by Candinya** [comment]
（因为看到有人问哪里去找图标但找不到那条回复所以在这里附一下）
FontAwesome 4.7.0 的图标可以去 https://fontawesome.com/v4/icons/ 这里找到（我知道它很老了）

**Comment by ArcticLampyrid** [comment]
同样对着邮件通知找了半天，没找到在哪😂
太奇怪了
