### ISSUE TITLE
Bug 回报：页面手动暗色模式切换按钮失效

### ISSUE THREAD

**Issue by BH6AOV** [Candinya/Kratos-Rebirth#135]
0. **报告前须知**

- [√] 我确认该Bug是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [√] 我确认已认真阅读 ReadMe.md 和文档，确认描述的内容有误或是不能解决我的问题
- [√] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

1. **对Bug的描述:**
页面手动暗色模式切换按钮失效

2. **复现Bug的方法:** 
可以使用如下的方案进行复现:
1 使用npm安装主题v2.0.2
2 通过```npm update```升级主题至v2.0.3
3 ```hexo g```生成网站
4 看，出错了吧！ 

3. **期望的行为:**
按钮应可以正常手动切换暗色主题

4. **相关的截图:**
可直接访问 https://blog.ypa.moe/ 进行按钮测试

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
 - 操作系统: Windows 10 专业版 / Android Q
 - 浏览器: Chrome
 - 版本: 均为最新版本

6. **服务器环境**
以下参数来自```hexo v```
- hexo: 6.2.0
- hexo-cli: 4.3.0
- os: linux 5.4.0-107-generic Ubuntu 20.04.4 LTS (Focal Fossa)
- node: 17.9.0
- v8: 9.6.180.15-node.16
- uv: 1.43.0
- zlib: 1.2.11
- brotli: 1.0.9
- ares: 1.18.1
- modules: 102
- nghttp2: 1.47.0
- napi: 8
- llhttp: 6.0.4
- openssl: 3.0.2+quic
- cldr: 40.0
- icu: 70.1
- tz: 2021a3
- unicode: 14.0
- ngtcp2: 0.1.0-DEV
- nghttp3: 0.1.0-DEV
Nginx版本： 1.18.0

7. **您的配置文件:**
/*****/_config.kratos-rebirth.yml Line 10
......
enable_dark: true
......

8. **补充内容:**
暂无

**Comment by Candinya** [comment]
有点奇怪，感觉是切换监听事件没有被挂载到按钮上导致的，看控制台这里有一个 clarity.ms 的代码加载报错（但不确定是不是被我的什么拦截器规则误伤了），其他暂时没法发现什么，手动执行样式切换是可行的
<img width="573" alt="image" src="https://user-images.githubusercontent.com/20502130/174466483-9df76188-e875-4be9-af7f-6c3e11ebb017.png">
可以先去掉这行（应该是站点统计代码？）试试，或是在 script 里看看加个 `type="text/javascript"` 看看能否解决问题？

**Comment by BH6AOV** [comment]
我回去注释掉试一下，按理说应该没影响x，之前用老版本（指不用npm安装的那个）的时候啥问题没有（？）

**Comment by BH6AOV** [comment]
刚刚尝试了一下，将控制台里所有的报错项目都删掉了（除了cloudflare那个烦人的static），一样还是不能用的，怪诶

**Comment by BH6AOV** [comment]
> 根据加载失败的内容来看，你应该是使用了 `cloudflare cdn` 同时在 `对应域名-Apps` 里安装了一些应用
> <details>
>     <summary>/cdn-cgi/apps/head/o8VSJLPlJ630VzpFGAYxShTLMQY.js</summary><p>
> 
> ```js
> ;window.CloudflareApps=window.CloudflareApps||{};CloudflareApps.siteId="3bf9f6cadf55be30dc8bd75986975e99";CloudflareApps.installs=CloudflareApps.installs||{};;(function(){'use strict'
> CloudflareApps.internal=CloudflareApps.internal||{}
> var errors=[]
> CloudflareApps.internal.placementErrors=errors
> var errorHashes={}
> function noteError(options){var hash=options.selector+'::'+options.type+'::'+(options.installId||'')
> if(errorHashes[hash]){return}
> errorHashes[hash]=true
> errors.push(options)}
> var initializedSelectors={}
> var currentInit=false
> CloudflareApps.internal.markSelectors=function markSelectors(){if(!currentInit){check()
> currentInit=true
> setTimeout(function(){currentInit=false})}}
> function check(){var installs=window.CloudflareApps.installs
> for(var installId in installs){if(!installs.hasOwnProperty(installId)){continue}
> var selectors=installs[installId].selectors
> if(!selectors){continue}
> for(var key in selectors){if(!selectors.hasOwnProperty(key)){continue}
> var hash=installId+'::'+key
> if(initializedSelectors[hash]){continue}
> var els=document.querySelectorAll(selectors[key])
> if(els&&els.length>1){noteError({type:'init:too-many',option:key,selector:selectors[key],installId:installId})
> initializedSelectors[hash]=true
> continue}else if(!els||!els.length){continue}
> initializedSelectors[hash]=true
> els[0].setAttribute('cfapps-selector',selectors[key])}}}
> CloudflareApps.querySelector=function querySelector(selector){if(selector==='body'||selector==='head'){return document[selector]}
> CloudflareApps.internal.markSelectors()
> var els=document.querySelectorAll('[cfapps-selector="'+selector+'"]')
> if(!els||!els.length){noteError({type:'select:not-found:by-attribute',selector:selector})
> els=document.querySelectorAll(selector)
> if(!els||!els.length){noteError({type:'select:not-found:by-query',selector:selector})
> return null}else if(els.length>1){noteError({type:'select:too-many:by-query',selector:selector})}
> return els[0]}
> if(els.length>1){noteError({type:'select:too-many:by-attribute',selector:selector})}
> return els[0]}}());(function(){'use strict'
> var prevEls={}
> CloudflareApps.createElement=function createElement(options,prevEl){options=options||{}
> CloudflareApps.internal.markSelectors()
> try{if(prevEl&&prevEl.parentNode){var replacedEl
> if(prevEl.cfAppsElementId){replacedEl=prevEls[prevEl.cfAppsElementId]}
> if(replacedEl){prevEl.parentNode.replaceChild(replacedEl,prevEl)
> delete prevEls[prevEl.cfAppsElementId]}else{prevEl.parentNode.removeChild(prevEl)}}
> var element=document.createElement('cloudflare-app')
> var container
> if(options.pages&&options.pages.URLPatterns&&!CloudflareApps.matchPage(options.pages.URLPatterns)){return element}
> try{container=CloudflareApps.querySelector(options.selector)}catch(e){}
> if(!container){return element}
> if(!container.parentNode&&(options.method==='after'||options.method==='before'||options.method==='replace')){return element}
> if(container===document.body){if(options.method==='after'){options.method='append'}else if(options.method==='before'){options.method='prepend'}}
> switch(options.method){case'prepend':if(container.firstChild){container.insertBefore(element,container.firstChild)
> break}
> case'append':container.appendChild(element)
> break
> case'after':if(container.nextSibling){container.parentNode.insertBefore(element,container.nextSibling)}else{container.parentNode.appendChild(element)}
> break
> case'before':container.parentNode.insertBefore(element,container)
> break
> case'replace':try{var id=element.cfAppsElementId=Math.random().toString(36)
> prevEls[id]=container}catch(e){}
> container.parentNode.replaceChild(element,container)}
> return element}catch(e){if(typeof console!=='undefined'&&typeof console.error!=='undefined'){console.error('Error creating Cloudflare Apps element',e)}}}}());(function(){'use strict'
> CloudflareApps.matchPage=function matchPage(patterns){if(!patterns||!patterns.length){return true}
> var loc=document.location.host+document.location.pathname
> if(window.CloudflareApps&&CloudflareApps.proxy&&CloudflareApps.proxy.originalURL){var url=CloudflareApps.proxy.originalURL.parsed
> loc=url.host+url.path}
> for(var i=0;i<patterns.length;i++){var re=new RegExp(patterns[i],'i')
> if(re.test(loc)){return true}}
> return false}}());CloudflareApps.installs["0NdsAfludTde"]={appId:"U7qJvtD8fdSv",scope:{}};;CloudflareApps.installs["0NdsAfludTde"].options={"backgroundColor":"#757575","backgroundOpacity":0.84,"buttonBorderColor":"#000000","buttonColor":"#66ccff","buttonHoverColor":"#ffffff","buttonHoverTextColor":"#000000","buttonLocation":"right","buttonText":"知道啦w","buttonTextColor":"#ffffff","buttonTextSize":{"unit":"px","value":10},"callbackFunction":"","cookieLifetime":false,"location":"bottom","message":"本站可能会使用Cooike记录您的访问用于提供更好的服务.","popupLocation":{"method":"prepend","selector":"body"},"popupPositioning":"fixed","splitTextAndButton":true,"textColor":"#ffffff","textLink":"了解更多","textLinkColor":"#497cc9","textLinkHoverColor":"#559bbd","textLinkNewTab":true,"textLinkUrl":"https://cookie-consent.app.forthe.top/why-websites-use-cookies/","textSize":{"unit":"em","value":1}};;CloudflareApps.installs["0NdsAfludTde"].URLPatterns=["^blog.ypa.moe/?.*$","^dirdl1.ypa.moe/?.*$"];;CloudflareApps.installs["0NdsAfludTde"].selectors={"popupLocation.selector":"body"};(function(){var script = document.createElement('script');script.src = '/cdn-cgi/apps/body/jiAxQlwkSsxXh7IFgs8rxTevbXo.js';document.head.appendChild(script);})();
> ```
> 
> </p></details>
> 
> 可以尝试去cloudflare那边暂时停用cdn功能检查一下

感谢，我去尝试一下

**Comment by BH6AOV** [comment]
> 根据加载失败的内容来看，你应该是使用了 `cloudflare cdn` 同时在 `对应域名-Apps` 里安装了一些应用
> <details>
>     <summary>/cdn-cgi/apps/head/o8VSJLPlJ630VzpFGAYxShTLMQY.js</summary><p>
> 
> ```js
> ;window.CloudflareApps=window.CloudflareApps||{};CloudflareApps.siteId="3bf9f6cadf55be30dc8bd75986975e99";CloudflareApps.installs=CloudflareApps.installs||{};;(function(){'use strict'
> CloudflareApps.internal=CloudflareApps.internal||{}
> var errors=[]
> CloudflareApps.internal.placementErrors=errors
> var errorHashes={}
> function noteError(options){var hash=options.selector+'::'+options.type+'::'+(options.installId||'')
> if(errorHashes[hash]){return}
> errorHashes[hash]=true
> errors.push(options)}
> var initializedSelectors={}
> var currentInit=false
> CloudflareApps.internal.markSelectors=function markSelectors(){if(!currentInit){check()
> currentInit=true
> setTimeout(function(){currentInit=false})}}
> function check(){var installs=window.CloudflareApps.installs
> for(var installId in installs){if(!installs.hasOwnProperty(installId)){continue}
> var selectors=installs[installId].selectors
> if(!selectors){continue}
> for(var key in selectors){if(!selectors.hasOwnProperty(key)){continue}
> var hash=installId+'::'+key
> if(initializedSelectors[hash]){continue}
> var els=document.querySelectorAll(selectors[key])
> if(els&&els.length>1){noteError({type:'init:too-many',option:key,selector:selectors[key],installId:installId})
> initializedSelectors[hash]=true
> continue}else if(!els||!els.length){continue}
> initializedSelectors[hash]=true
> els[0].setAttribute('cfapps-selector',selectors[key])}}}
> CloudflareApps.querySelector=function querySelector(selector){if(selector==='body'||selector==='head'){return document[selector]}
> CloudflareApps.internal.markSelectors()
> var els=document.querySelectorAll('[cfapps-selector="'+selector+'"]')
> if(!els||!els.length){noteError({type:'select:not-found:by-attribute',selector:selector})
> els=document.querySelectorAll(selector)
> if(!els||!els.length){noteError({type:'select:not-found:by-query',selector:selector})
> return null}else if(els.length>1){noteError({type:'select:too-many:by-query',selector:selector})}
> return els[0]}
> if(els.length>1){noteError({type:'select:too-many:by-attribute',selector:selector})}
> return els[0]}}());(function(){'use strict'
> var prevEls={}
> CloudflareApps.createElement=function createElement(options,prevEl){options=options||{}
> CloudflareApps.internal.markSelectors()
> try{if(prevEl&&prevEl.parentNode){var replacedEl
> if(prevEl.cfAppsElementId){replacedEl=prevEls[prevEl.cfAppsElementId]}
> if(replacedEl){prevEl.parentNode.replaceChild(replacedEl,prevEl)
> delete prevEls[prevEl.cfAppsElementId]}else{prevEl.parentNode.removeChild(prevEl)}}
> var element=document.createElement('cloudflare-app')
> var container
> if(options.pages&&options.pages.URLPatterns&&!CloudflareApps.matchPage(options.pages.URLPatterns)){return element}
> try{container=CloudflareApps.querySelector(options.selector)}catch(e){}
> if(!container){return element}
> if(!container.parentNode&&(options.method==='after'||options.method==='before'||options.method==='replace')){return element}
> if(container===document.body){if(options.method==='after'){options.method='append'}else if(options.method==='before'){options.method='prepend'}}
> switch(options.method){case'prepend':if(container.firstChild){container.insertBefore(element,container.firstChild)
> break}
> case'append':container.appendChild(element)
> break
> case'after':if(container.nextSibling){container.parentNode.insertBefore(element,container.nextSibling)}else{container.parentNode.appendChild(element)}
> break
> case'before':container.parentNode.insertBefore(element,container)
> break
> case'replace':try{var id=element.cfAppsElementId=Math.random().toString(36)
> prevEls[id]=container}catch(e){}
> container.parentNode.replaceChild(element,container)}
> return element}catch(e){if(typeof console!=='undefined'&&typeof console.error!=='undefined'){console.error('Error creating Cloudflare Apps element',e)}}}}());(function(){'use strict'
> CloudflareApps.matchPage=function matchPage(patterns){if(!patterns||!patterns.length){return true}
> var loc=document.location.host+document.location.pathname
> if(window.CloudflareApps&&CloudflareApps.proxy&&CloudflareApps.proxy.originalURL){var url=CloudflareApps.proxy.originalURL.parsed
> loc=url.host+url.path}
> for(var i=0;i<patterns.length;i++){var re=new RegExp(patterns[i],'i')
> if(re.test(loc)){return true}}
> return false}}());CloudflareApps.installs["0NdsAfludTde"]={appId:"U7qJvtD8fdSv",scope:{}};;CloudflareApps.installs["0NdsAfludTde"].options={"backgroundColor":"#757575","backgroundOpacity":0.84,"buttonBorderColor":"#000000","buttonColor":"#66ccff","buttonHoverColor":"#ffffff","buttonHoverTextColor":"#000000","buttonLocation":"right","buttonText":"知道啦w","buttonTextColor":"#ffffff","buttonTextSize":{"unit":"px","value":10},"callbackFunction":"","cookieLifetime":false,"location":"bottom","message":"本站可能会使用Cooike记录您的访问用于提供更好的服务.","popupLocation":{"method":"prepend","selector":"body"},"popupPositioning":"fixed","splitTextAndButton":true,"textColor":"#ffffff","textLink":"了解更多","textLinkColor":"#497cc9","textLinkHoverColor":"#559bbd","textLinkNewTab":true,"textLinkUrl":"https://cookie-consent.app.forthe.top/why-websites-use-cookies/","textSize":{"unit":"em","value":1}};;CloudflareApps.installs["0NdsAfludTde"].URLPatterns=["^blog.ypa.moe/?.*$","^dirdl1.ypa.moe/?.*$"];;CloudflareApps.installs["0NdsAfludTde"].selectors={"popupLocation.selector":"body"};(function(){var script = document.createElement('script');script.src = '/cdn-cgi/apps/body/jiAxQlwkSsxXh7IFgs8rxTevbXo.js';document.head.appendChild(script);})();
> ```
> 
> </p></details>
> 
> 可以尝试去cloudflare那边暂时停用cdn功能检查一下

尝试了一下，把APPS卸载，cdn改bypass之后一样是没有效果的
基本排除cloudflare的问题了

**Comment by ArcticLampyrid** [comment]
您好，在新的主题模式实现（#113）中，监听按钮这一步骤在`DOMContentLoaded`事件触发后进行
这边注意到您开启了`Cloudflare`的`Rocket-Loader`，这似乎影响了`DOMContentLoaded`的正常触发，导致按钮无法被监听
这似乎属于`Cloudflare`的bug

See also:
[Understanding Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-Understanding-Rocket-Loader)
[Solution to Missing DOMContentLoaded Event when Enabling both HTML Auto Minify and Rocket Loader in Cloudflare](https://dev.to/hollowman6/solution-to-missing-domcontentloaded-event-when-enabling-both-html-auto-minify-and-rocket-loader-in-cloudflare-5ch8) by @HollowMan6

**Comment by BH6AOV** [comment]
> 您好，在新的主题模式实现（#113）中，监听按钮这一步骤在`DOMContentLoaded`事件触发后进行 这边注意到您开启了`Cloudflare`的`Rocket-Loader`，这似乎影响了`DOMContentLoaded`的正常触发，导致按钮无法被监听 这似乎属于`Cloudflare`的bug
> 
> See also: [Understanding Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-Understanding-Rocket-Loader) [Solution to Missing DOMContentLoaded Event when Enabling both HTML Auto Minify and Rocket Loader in Cloudflare](https://dev.to/hollowman6/solution-to-missing-domcontentloaded-event-when-enabling-both-html-auto-minify-and-rocket-loader-in-cloudflare-5ch8) by @HollowMan6

非常感谢，刚刚对`Rocket-Loader`的设置进行了更改，已经解决了这一问题，同时我在对相关问题进行检索后发现[一篇文章](https://blog.hissummer.com/2016/03/cloudflare-rocket-loader%E5%BB%BA%E8%AE%AE%E4%B8%AD%E5%9B%BD%E4%BD%BF%E7%94%A8%E8%80%85%E5%85%B3%E9%97%AD/)有提到`Rocket-Loader`对中国大陆访问者的不便利之处，可能是同一原因造成的这一问题。
再次感谢！

**Comment by ArcticLampyrid** [comment]
> 可能是同一原因造成的这一问题。

应该也不仅仅是墙的问题，毕竟我开着梯子也没法正常触发`DOMContentLoaded`

**Comment by BH6AOV** [comment]
> > 可能是同一原因造成的这一问题。
> 
> 应该也不仅仅是墙的问题，毕竟我开着梯子也没法正常触发`DOMContentLoaded`

我这里也是，就很奇怪，但是至少目前能暂时解决这个问题了
