### ISSUE TITLE
顶部导航栏是只能复制sites这种链接式的菜单麽，可不可以复制friends这种新增路由菜单

### ISSUE THREAD

**Issue by enjoyWeb** [Candinya/Kratos-Rebirth#136]
顶部导航栏是只能复制sites这种链接式的菜单麽，可不可以复制friends这种新增路由菜单。不然感觉菜单分类不够用，用分类或者标签来区分文章感觉不大够

**Comment by enjoyWeb** [comment]
其实看着friends和sites的作用都重复的，就是提供外链而已罢了

**Comment by ArcticLampyrid** [comment]
具体描述一下你的需求？

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！

**Comment by enjoyWeb** [comment]
> 具体描述一下你的需求？

举个例子，比如我想把分类都放到一级菜单或者二级菜单，前端技术=>vue|react|...，面试题=>html相关|js相关，菜单那边直接看到的是前端技术|面试题，然后点进去是前端技术相关的文章列表（效果类似现在的归档）

**Comment by ArcticLampyrid** [comment]
为什么不直接使用多级分类呢

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by enjoyWeb** [comment]
> 具体描述一下你的需求？

现在所有的文章入口都是在归档那边，或者是sidebar那边的标签，感觉太深或者说不直观，没有直接放在导航栏上来的直观
![image](https://user-images.githubusercontent.com/8252286/176862048-0cc14e1b-27d8-4ad1-94d9-1d316bcd2086.png)

**Comment by enjoyWeb** [comment]
> 为什么不直接使用多级分类呢 Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

多级分类是指？

**Comment by ArcticLampyrid** [comment]
您可以将 `vue|react|...` 等子分类都放到 `前端技术` 下，然后将menu item指向 `前端技术` 分类展示页

参照本主题样例 https://kr-demo.candinya.com/
我们可以看到，属于 `Foo/Bar/Baz` 的文章也将在 [`Foo` 分类展示页](https://kr-demo.candinya.com/categories/Foo/)显示出来

**Comment by ArcticLampyrid** [comment]
`friends` 在本主题的主要作用是生成一个 2 列的随机排序的列表，这是专用于展现友联的定制样式
https://kr-demo.candinya.com/friends/

**Comment by enjoyWeb** [comment]
> 您可以将 `vue|react|...` 等子分类都放到 `前端技术` 下，然后将menu item指向 `前端技术` 分类展示页
> 
> 参照本主题样例 https://kr-demo.candinya.com/ 我们可以看到，属于 `Foo/Bar/Baz` 的文章也将在 [`Foo` 分类展示页](https://kr-demo.candinya.com/categories/Foo/)显示出来

👍知道了，我试试

**Comment by enjoyWeb** [comment]
> 您可以将 `vue|react|...` 等子分类都放到 `前端技术` 下，然后将menu item指向 `前端技术` 分类展示页
> 
> 参照本主题样例 https://kr-demo.candinya.com/ 我们可以看到，属于 `Foo/Bar/Baz` 的文章也将在 [`Foo` 分类展示页](https://kr-demo.candinya.com/categories/Foo/)显示出来

好像有个小瑕疵，这样子每次点击菜单，都会新打开一个tab标签页，menu里item有没有设置target是否是在当前页打开链接

**Comment by enjoyWeb** [comment]
顺便问下，menu item里的fa fa-link这些iconfont命名是哪里去找更多的图标
