### ISSUE TITLE
文章详情页评论使用gitment和gitalk都会报错

### ISSUE THREAD

**Issue by enjoyWeb** [Candinya/Kratos-Rebirth#139]
yml配置如下所示
![image](https://user-images.githubusercontent.com/8252286/178398578-78b3d3c6-303c-46e6-9e2b-c5b6e5707306.png)
应用和密钥在github上均已创建
![image](https://user-images.githubusercontent.com/8252286/178398813-30e29e9a-f87c-4815-b054-1676036f1633.png)
（1）使用gitment报错如下
![image](https://user-images.githubusercontent.com/8252286/178398211-52bebbcb-d95e-46ac-b65e-ec15967ce250.png)
（2）使用gitalk报错如下
![image](https://user-images.githubusercontent.com/8252286/178398244-48e399cb-184e-438a-bf48-f51a45594696.png)

**Comment by ArcticLampyrid** [comment]
这些评论系统似乎需要您手动创建 issue

**Comment by enjoyWeb** [comment]
> 这些评论系统似乎需要您手动创建 issue

我之前好像是可以评论成功，但是后面用正式域名就不行了（应用里的callback url地址也改成正是域名的了）
![image](https://user-images.githubusercontent.com/8252286/178399612-f8558149-2898-4c82-8bae-c9ce283cf669.png)

**Comment by enjoyWeb** [comment]
> 这些评论系统似乎需要您手动创建 issue

评论成功
![image](https://user-images.githubusercontent.com/8252286/178399855-e8894b8e-04b2-4566-86c1-830fab64349d.png)

**Comment by ArcticLampyrid** [comment]
您好，这一主题只是简单的将相关参数传输给了`Gitalk v1`的脚本，相关使用说明和答疑还请前往 https://github.com/gitalk/gitalk

**Comment by ArcticLampyrid** [comment]
> 传入 gitalk 的参数为源地址的 md5

Note: This will be a breaking change.
