### ISSUE TITLE
怎么自定义背景图片和头像

### ISSUE THREAD

**Issue by GHeillcoat** [Candinya/Kratos-Rebirth#140]
# 自定义样式
customStyles:
  images: # 图片相关设置
    banner: /images/banner.webp # 站点横幅
    background: /images/bg.webp # 站点背景

修改这里会导致不加载图片，萌新求解答

**Comment by Candinya** [comment]
想请问一下您改成了什么，最好提供一个样例站点，或者截取一下配置文件中的这一部分内容

**Comment by GHeillcoat** [comment]
![屏幕截图 2022-07-16 104220](https://user-images.githubusercontent.com/41291000/179336262-d02284e5-e377-4834-afc2-e16572b749cb.png)
我就修改了这里，是直接npm安装的

**Comment by ArcticLampyrid** [comment]
请确定相关图片文件是否存在，方便的话截取一下浏览器Console的日志

**Comment by GHeillcoat** [comment]
![1111](https://user-images.githubusercontent.com/41291000/179364389-5d617ebd-06c8-4651-9231-944482b186e2.png)
是图片的地址有问题吗

**Comment by ArcticLampyrid** [comment]
需要遵循 Hexo 的规则，放到 `source` 目录下面
比如 `source/img/banner.jpg`

**Comment by GHeillcoat** [comment]
> 需要遵循 Hexo 的规则，放到 `source` 目录下面 比如 `source/img/banner.jpg`

哦哦，我去试试

**Comment by GHeillcoat** [comment]
> 需要遵循 Hexo 的规则，放到 `source` 目录下面 比如 `source/img/banner.jpg`

谢谢大佬，学习到了
