### ISSUE TITLE
Bug 回报：填写微博个性域名而非UID后生成的微博地址无效

### ISSUE THREAD

**Issue by 201206030** [Candinya/Kratos-Rebirth#142]
0. **报告前须知**

- [v] 我确认该Bug是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [v ] 我确认已认真阅读 ReadMe.md 和文档，确认描述的内容有误或是不能解决我的问题
- [v] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

1. **对Bug的描述:**

设置微博的用户名后进入的链接无效

2. **复现Bug的方法:**

可以使用如下的方案进行复现:

 1. _config.kratos-rebirth.yml 中设置微博的用户名为 xxx
 2. 部署后点击页面底部的微博 logo 后进入 https://weibo.com/u/xxx

3. **期望的行为:**

点击页面底部的微博 logo 后进入 https://weibo.com/xxx 

4. **相关的截图:**

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

6. **您的配置文件:**

7. **补充内容:**

**Comment by ArcticLampyrid** [comment]
您好，这是微博用户页的正确格式，如 https://weibo.com/u/2028810631 对应 `uid=2028810631` 的用户

**Comment by ArcticLampyrid** [comment]
> 3\. **期望的行为:**
> 
> 点击页面底部的微博 logo 后进入 https://weibo.com/xxx

据我观察到的现象，微博并不支持您所期待的URL格式

**Comment by 201206030** [comment]
> 您好，这是微博用户页的正确格式，如 https://weibo.com/u/2028810631 对应 `uid=2028810631` 的用户

大佬，我试了下，微博官方的可以用这种方式访问，但是普通用户不行，像这个 https://weibo.com/u/lilianjie

**Comment by ArcticLampyrid** [comment]
> 大佬，我试了下，微博官方的可以用这种方式访问，但是普通用户不行，像这个 https://weibo.com/u/lilianjie

要用UID，https://weibo.com/lilianjie --> https://weibo.com/u/1270468784

**Comment by 201206030** [comment]
> > 大佬，我试了下，微博官方的可以用这种方式访问，但是普通用户不行，像这个 https://weibo.com/u/lilianjie
> 
> 要用UID，https://weibo.com/lilianjie --> https://weibo.com/u/1270468784

好的，明白了

**Comment by Candinya** [comment]
其实可以作为一个 enhancement ，前缀都是 weibo.com 的话 uid 可以用 u/xxxxx 这样的格式设置，直接输入就是兼容这个新的个性域名模式了（加入 todo 列表ing
（不过考虑到设置会变更可能需要单独拎一个平行的设置项，比如 weiboSuffix 或者其他什么的这样

**Comment by 201206030** [comment]
> 其实可以作为一个 enhancement ，前缀都是 weibo.com 的话 uid 可以用 u/xxxxx 这样的格式设置，直接输入就是兼容这个新的个性域名模式了（加入 todo 列表ing （不过考虑到设置会变更可能需要单独拎一个平行的设置项，比如 weiboSuffix 或者其他什么的这样

好的大佬，只要说文档上说清楚就好了，主要是微博用的少，一开始没反应过来，以为是设置用户名，没想到是设置 uid

**Comment by 201206030** [comment]
> > 其实可以作为一个 enhancement ，前缀都是 weibo.com 的话 uid 可以用 u/xxxxx 这样的格式设置，直接输入就是兼容这个新的个性域名模式了（加入 todo 列表ing （不过考虑到设置会变更可能需要单独拎一个平行的设置项，比如 weiboSuffix 或者其他什么的这样
> 
> 好的大佬，只要是文档上说清楚就好了，主要是微博用的少，一开始没反应过来，以为是设置用户名，没想到是设置 uid

其实也不是用户名，而是用户昵称，刚好设置得和个性域名一样，好几年没用微博了，这些概念都忘了🤦‍♂️
