### ISSUE TITLE
[Low Priority] 新功能建议： 未添加 about.webp 的自定义入口

### ISSUE THREAD

**Issue by ghost** [Candinya/Kratos-Rebirth#145]
~~好久不见 折腾hexo对我这种老年人真的折磨~~
有空闲时间了继续调试 查漏补缺
![image](https://user-images.githubusercontent.com/103689666/180490177-7a536d9b-de91-423b-bf73-07d4f5a75c8c.png)
https://github.com/Candinya/Kratos-Rebirth/blob/master/source/images/about.webp
这里的自定义修改入口没有添加(

**Comment by ArcticLampyrid** [comment]
也可以直接通过替换相应文件实现的啦

Sent from Outlook for Android<https://aka.ms/ghei36>
________________________________
From: R坂梨彩 ***@***.***>
Sent: Saturday, July 23, 2022 1:14:08 AM
To: Candinya/Kratos-Rebirth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Candinya/Kratos-Rebirth] [Low Priority] 新功能建议： 未添加 about.webp 的自定义入口・ (Issue #145)


好久不见 折腾hexo对我这种老年人真的折磨
有空闲时间了继续调试 查漏补缺
[image]<https://user-images.githubusercontent.com/103689666/180490177-7a536d9b-de91-423b-bf73-07d4f5a75c8c.png>
https://github.com/Candinya/Kratos-Rebirth/blob/master/source/images/about.webp
这里的自定义修改入口没有添加(

―

**Comment by ArcticLampyrid** [comment]
实际上，自定义资源还缺少在 dark mode 下单独设置图片的 feature

Sent from Outlook for Android<https://aka.ms/ghei36>
________________________________
