### ISSUE TITLE
新功能建议： 侧边栏添加最近评论功能

### ISSUE THREAD

**Issue by tulloch56** [Candinya/Kratos-Rebirth#150]
大佬，可以添加一个显示在侧边栏的最近评论模块功能吗？

![image](https://user-images.githubusercontent.com/111063282/190553395-ddbd0b52-6479-4a35-a2ac-79c0aea600d4.png)

**Comment by ArcticLampyrid** [comment]
静态博客的评论系统由第三方提供，这样的功能实现起来可能较为复杂，且只有在使用特定的评论系统时才可用

**Comment by ArcticLampyrid** [comment]
why close?
