### ISSUE TITLE
markdown转换的html如何在头部新增代码

### ISSUE THREAD

**Issue by enjoyWeb** [Candinya/Kratos-Rebirth#151]
想在生成html文件头部加上一行代码`<meta name="referrer" content="no-referrer" />`，有配置入口麽，还是要怎么改主题？

**Comment by Candinya** [comment]
可以在主题的 `layout/_partial/head.ejs` 文件里添加

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！

**Comment by ArcticLampyrid** [comment]
亲，建议取消对 GitHub Issues 的自动回复哦

**Comment by ArcticLampyrid** [comment]
此外，这样的功能推荐使用 Hexo 插件实现（注入代码）而不是直接修改主题哦

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！
