### ISSUE TITLE
[Question] 关于文章缩略图的Path 问题

### ISSUE THREAD

**Issue by EFF-Mr-W** [Candinya/Kratos-Rebirth#157]
您好，我的问题是关于文章首页展示的缩略图的**路径**问题。
因为我是新手，所以这个问题可能会很弱智。
您在介绍文章中提到，若要使用特定图片Pic后应跟存放在资源文件夹的文件名称。但我并不清楚具体的相对路径还是绝对路径是哪里，我尝试将缩略图存入随即图片所指向的存放位置（source/images/）发现显示错误。后面我查看了这个标题图片的地址，发现它的指向是在post 文件名称后面，而这个文件夹我只能在使用`hexo g` 命令后的public 文件夹里找到。将图片放入特定的post文件夹内后，图片显示正常。
问题来了，当我想在文章中插入图片时，路径又回到了/source/images/ 里。那么我就在想，是否存在更好的路径可以不用手动将缩略图添加进public 文件夹？因为我使用的是服务器来搭建博客，可能需要经常更新public文件夹，而使用`hexo clean && hexo g`命令则会将图片删除。是否存在其他的可使用的缩略图路径或者我如何更改路径指向，使得我可以使用`hexo g` 一键生成我想使用的全部图片？

**Comment by ArcticLampyrid** [comment]
https://github.com/Candinya/Kratos-Rebirth/blob/0c5bc070bd15579f0eb66c789b84be6020fdf456/layout/index.ejs#L130-L136

请放置在与文章 aaa.md 同目录同名的文件夹 aaa 中

**Comment by EFF-Mr-W** [comment]
OK了，问题解决，谢谢

**Comment by ArcticLampyrid** [comment]
另记：
本功能需要开启 Asset Folder，如果始终无法显示图片
请在站点的 `config.yml` （注意，并非主题配置文件）中检查一下有没有 `post_asset_folder: true`
