### ISSUE TITLE
友链页面手机端适配问题

### ISSUE THREAD

**Issue by tulloch56** [Candinya/Kratos-Rebirth#158]
1. **对Bug的描述:**

手机端访问友链网页显示不完整（友链框宽度太小了，网站名和描述都看不到了），可以适配手机端一行显示一个友链吗？

![Snipaste_2022-10-24_09-05-21](https://user-images.githubusercontent.com/111063282/197428949-11285ba8-08b9-4abe-b50b-3ab848b9a479.jpg)

**Comment by Candinya** [comment]
是一个样式问题，最新的开发代码应该已经修好了，可以试一试，或者等下一版发布就好

**Comment by tulloch56** [comment]
> 是一个样式问题，最新的开发代码应该已经修好了，可以试一试，或者等下一版发布就好

好的，谢谢大佬

**Comment by Candinya** [comment]
新的版本发布了，可以更新试一试哦
