### ISSUE TITLE
网站内的表格样式修改建议

### ISSUE THREAD

**Issue by tulloch56** [Candinya/Kratos-Rebirth#159]
2. **请描述您所设想的功能或是解决方案**
大佬，我又来提建议了，感觉网站的表格样式显示不太美观，我之前打开浏览器控制台自己捣鼓过，就是每次更新主题就要重新修改代码，感觉有点麻烦，希望大佬可以修改下源码，还有表格宽度和字体适配一下手机端吧，谢谢😘

下面是原表格样式，觉得字体有点大了，表格宽度不会自适应文章页宽度
![image](https://user-images.githubusercontent.com/111063282/197571485-b5900ce9-295a-441c-94ff-514e8b24e294.png)

手机页面显示不太好（列数多了会溢出）
![image](https://user-images.githubusercontent.com/111063282/197572306-befc128c-faad-47b2-ae3f-7595ec81b669.png)

修改后，下图是我修改的效果（前端太菜了，看别的网站随便改的😂）
![image](https://user-images.githubusercontent.com/111063282/197572051-06508550-0a7e-436c-a759-6be410a831c1.png)

![image](https://user-images.githubusercontent.com/111063282/197572586-99247a7d-21ce-41e0-acde-49300f2703fa.png)

**Comment by Candinya** [comment]
感觉参考的这个表格样式很棒，如果可以的话，能麻烦帮忙提供一下相关的样式吗，这边集成到主题里去，非常感谢！

**Comment by ArcticLampyrid** [comment]
> 或许还可以添加一个表格内文字居中对齐

表格内对齐方式可以由 markdown 指令控制哦
```markdown
| Default Header | Left Align | Right Align | Center Align |
| --- | :-- | --: | :-: |
```

**Comment by tulloch56** [comment]
> > 或许还可以添加一个表格内文字居中对齐
> 
> 表格内对齐方式可以由 markdown 指令控制哦
> 
> ```gfm
> | Default Header | Left Align | Right Align | Center Align |
> | --- | :-- | --: | :-: |
> ```

哦，长知识了，挺方便的不用改代码了👍
