### ISSUE TITLE
为啥安装后themes文件夹下没有主题配置文件

### ISSUE THREAD

**Issue by Torynatural** [Candinya/Kratos-Rebirth#160]
0. **报告前须知**

- [ ] 我确认该Bug是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [ ] 我确认已认真阅读 ReadMe.md 和文档，确认描述的内容有误或是不能解决我的问题
- [ ] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

1. **对Bug的描述:**

2. **复现Bug的方法:**

3. **期望的行为:**

4. **相关的截图:**

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

6. **您的配置文件:**

7. **补充内容:**

**Comment by Candinya** [comment]
抱歉，是文档的疏漏，之前的版本要求手动安装所以会安装在 themes 目录，现在可以用包管理工具安装了，是安装到 node_modules 下的，确实不会在主题目录中。

主题配置文件您可以参照步骤 4 的说明，复制仓库的主题配置文件来调整哦。

**Comment by Torynatural** [comment]
谢谢大佬！
