### ISSUE TITLE
dalao打扰了，侧边栏如何添加文字23333

### ISSUE THREAD

**Issue by Torynatural** [Candinya/Kratos-Rebirth#161]
0. **报告前须知**

- [ ] 我已确认该功能确实不存在
- [ ] 我会认真详细地描述清楚我想要的功能

1. **您的新功能建议是由使用时出现的不便引发的吗？**

2. **请描述您所设想的功能或是解决方案**

3. **补充内容:**

**Comment by Candinya** [comment]
如果是指个人小组件里的内容的话，是在站点配置 `_config.yml` 文件的 `description` 字段里配置的
![image](https://user-images.githubusercontent.com/20502130/198062177-b84ac53a-1d5b-42e8-baad-5bd16390313c.png)

https://github.com/Candinya/Kratos-Rebirth/blob/4c80c71dee241fc7d9dbe7c9fefb4f2417b156f0/.github/workflows/build-demo.yml#L47
