### ISSUE TITLE
建议添加自定义icon接口

### ISSUE THREAD

**Issue by 1398listener** [Candinya/Kratos-Rebirth#164]
0. **报告前须知**

- [x] 我已确认该功能确实不存在
- [x] 我会认真详细地描述清楚我想要的功能

1. **您的新功能建议是由使用时出现的不便引发的吗？**

想要给b站的链接添加一个类似github的icon，但是很明显FontAwesome@4.7.0中没有bilibili的icon图标，所以需要自己到iconfont上生成css文件并整合到现有的系统里，但是找不到对应的接口

2. **请描述您所设想的功能或是解决方案**

可以参考butterfly中的接口，比如[这个](https://cloud.tencent.com/developer/article/1813883)

3. **补充内容:**

再次感谢大佬

**Comment by Candinya** [comment]
新版本发布了，调整了页脚联系方式这边的配置格式，现在可以自定义图标和链接了，可以试一试
