### ISSUE TITLE
作者能不能给一个生成后的整站的静态页面和源码

### ISSUE THREAD

**Issue by jiangqiang1996** [Candinya/Kratos-Rebirth#165]
我自己Java开发了一个博客网站，目前没有静态页面，感觉这个主题不错，想适配下。能不能给个静态源码呀？

**Comment by ArcticLampyrid** [comment]
这个仓库不就是代码吗……

**Comment by jiangqiang1996** [comment]
> 这个仓库不就是代码吗……

这个是hexo的代码，我想要的是使用hexo生成之后的页面。我想移植到我自己使用java开发的一个静态博客系统去。

**Comment by ArcticLampyrid** [comment]
> hexo生成之后的页面

那你自己 `hexo g` 生成一遍不就好了吗...

**Comment by jiangqiang1996** [comment]
> > hexo生成之后的页面
> 
> 那你自己 `hexo g` 生成一遍不就好了吗...

注意是没内容 生成出来看不见完整效果，我想找个有内容的，生成出来。有没有大哥大姐行行好的？

**Comment by ArcticLampyrid** [comment]
https://github.com/Candinya/Kratos-Rebirth-Demo 官方样例
https://alampy.com/ 我博客（also available on IPFS）

**Comment by ArcticLampyrid** [comment]
https://candinya.com/ 作者博客
https://github.com/Candinya/Kratos-Rebirth-Demo 官方样例
https://alampy.com/ 我博客（also available on IPFS）

**Comment by Candinya** [comment]
移植这个主题移植到另一个平台

可以直接参考这些地方：

1. sources 目录，这里存放的是构建完成后被直接引用的样式和资源文件，或是依赖使用的资源文件
2. src 目录，这里存放的是构建资源文件所使用的原始版本（也就是未经构建和压缩，可供人类阅读和编辑的版本）
3. gulpfile.js ，这是用来打包构建上述资源文件使用的脚本（老，但是实用，编辑完 src 目录里的就运行一遍 build 生成 sources 目录里的构建后版本）

需要注意这些地方：

1. scripts 目录，这里存放的是一些针对 hexo 平台特殊处理的工具，如果您想要在新平台保留这些功能，您需要移植这里面的一些组件并针对平台优化
2. languages 目录，这里存放的是一些如果有 i18n 需求就可以对应使用的翻译文件（虽然目前只有简体中文），请注意针对目标平台进行优化，或是直接嵌入到模板中
3. _config.yml ，这个是主题的配置文件，包含了用户可以选择的设置以让主题更加符合使用者的心意，请注意针对目标平台调整适配，其中的配置项很多被 ejs 模板文件用到， js 块下的是构建时经由 scripts 里的代码构建并在 js 读取站点运行时
4. layout 目录，这里存放的是用于生成页面的模板，不同的页面已经做好了切分，一些可以复用的组件也基本都有独立文件封装，请注意这些是 ejs 格式（一种支持内嵌代码的 HTML 生成模板，有点类似于 php），用到的一些状态和配置项注入需要参考目标平台进行调整

应该主要就这些，可以参考仓库像 @ArcticLampyrid 说的， Kratos-Rebirth-Demo 那个仓库可以直接获得构建完成的 html 文件和相关的资源
