### ISSUE TITLE
新功能建议： 代码块复制可选是否添加版权信息

### ISSUE THREAD

**Issue by zhxycn** [Candinya/Kratos-Rebirth#166]
0. **报告前须知**

- [x] 我已确认该功能确实不存在
- [x] 我会认真详细地描述清楚我想要的功能

1. **您的新功能建议是由使用时出现的不便引发的吗？**

多行代码块在点击复制按钮复制时会添加文章版权信息，这对一些包含命令行操作的教程类文章不是很友好

2. **请描述您所设想的功能或是解决方案**

将`复制的内容中添加版权信息`设置为可选功能

3. **补充内容:**

点击复制按钮后，若代码块中若仅有一行代码则不会出现此问题

很棒的主题，辛苦了

**Comment by ArcticLampyrid** [comment]
https://github.com/Candinya/Kratos-Rebirth/blob/b7aa3332a941bbc7a31b9a1d1f2ed329f3051213/_config.yml#L214
设置为 `copyrightNotice: null`

**Comment by Candinya** [comment]
最新的开发代码调整了一下这部分的接口，现在应该不会在复制代码的时候把提示信息带上了
使用了 https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard 这个 API

**Comment by zhxycn** [comment]
好哒~ 晚上看看

**Comment by zhxycn** [comment]
刚刚升级了最新的2.1.2版，试了一下也没什么问题了，感谢
