### ISSUE TITLE
自动检查更新错误

### ISSUE THREAD

**Issue by SurveyorCangMing** [Candinya/Kratos-Rebirth#167]
![image](https://user-images.githubusercontent.com/82685282/204099833-d6d67492-0337-4700-baae-c70b7cd9b79c.png)

**Comment by ArcticLampyrid** [comment]
网络正常吗？开代理没？

**Comment by SurveyorCangMing** [comment]
> 网络正常吗？开代理没？

网络正常的，可以正常部署到github

**Comment by Candinya** [comment]
您可以在命令行里运行以下代码，检查和接口的连接情况：
```
curl -v https://api.github.com/repos/Candinya/Kratos-Rebirth/releases/latest
```
NodeJS 网络比较迷，有时候可能会出现奇怪的问题，或者也有可能是因为命令行并不会使用代理服务器的原因

不过这个检查更新只是个提示，不影响主题的正常使用，不用担心
