### ISSUE TITLE
原markdown代码块不起作用

### ISSUE THREAD

**Issue by Heartfilia** [Candinya/Kratos-Rebirth#168]
大佬请问一下在markdown里面 ```python 这种代码框语法是没有问题的，但是我这里今天发现当前主题好像不太行了，还有怎么才能有大大你这种代码的框框
我想要样子的如图
![想要的样子](http://static.litetools.top/test/%E9%A2%84%E6%9C%9F.png)

我的代码是这样子的
![代码样子](http://static.litetools.top/test/%E4%BB%A3%E7%A0%81%E6%A0%B7%E5%AD%90.png)

结果页面实际展示效果这样子的
![实际页面效果](http://static.litetools.top/test/%E5%AE%9E%E9%99%85%E9%A1%B5%E9%9D%A2%E6%95%88%E6%9E%9C.png)

大大这里是怎么弄出这个代码框的呀

**Comment by Candinya** [comment]
检查一下 Hexo 有没有安装并启用 `highlight.js` ？这个主题目前的高亮工作是由生成时实现的，并非前端完成，如果高亮调用失败可能会导致糊成一团的情况

**Comment by Heartfilia** [comment]
好的谢谢大佬 我检查一下 我之前用其他主题自动就有这个东西好像 我现在试试~

**Comment by Heartfilia** [comment]
确实是这个问题，之前用其他主题的时候，都需要把这个关闭，现在这里忘记打开了，感谢大佬，打开主配置里面的这里一下解决了~~
