### ISSUE TITLE
新功能建议： banner和背景图片跟随深色浅色模式切换

### ISSUE THREAD

**Issue by RainHoutas** [Candinya/Kratos-Rebirth#172]
1. **您的新功能建议是由使用时出现的不便引发的吗？**
我发现主题文件夹里面有banner_dark图片，但是设置不出来
如果可以设置就好了，这样就不怕在暗色模式下图片过亮了，能使界面更优雅

2. **请描述您所设想的功能或是解决方案**
如果可以设置就好了，这样就不怕在暗色模式下图片过亮了，也可以增加主题美观度🙏🙏🙌

3. **补充内容:**
大佬辛苦了，已经用大佬的主题一年了，希望主题越做越好(ง •_•)ง💪

**Comment by Candinya** [comment]
推了一个修复，是图片样式被主题默认配置覆盖了导致的，下一版发布就可以了（或者可以拉取最新的开发代码试一试），自定义图片和深色模式的兼容之后我再调调看吧

**Comment by RainHoutas** [comment]
谢谢大佬！

**Comment by Candinya** [comment]
已经在 V3 版本中实现，可以参考这里 https://wiki.krt.moe/posts/configurations/#%E5%9B%BE%E7%89%87%E9%85%8D%E7%BD%AE
