### ISSUE TITLE
新功能建议： 能否添加对Twikoo评论系统的访问量统计的支持

### ISSUE THREAD

**Issue by RainHoutas** [Candinya/Kratos-Rebirth#173]
0. **报告前须知**

- [x] 我已确认该功能确实不存在
- [x] 我会认真详细地描述清楚我想要的功能

1. **您的新功能建议是由使用时出现的不便引发的吗？**
[我在配置评论系统时发现twikoo评论系统支持访问量统计](https://twikoo.js.org/faq.html#%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF%E6%96%87%E7%AB%A0%E8%AE%BF%E9%97%AE%E9%87%8F%E7%BB%9F%E8%AE%A1)

2. **请描述您所设想的功能或是解决方案**
希望能加入twikoo评论系统对访问量的统计的支持🙏🙏🙏🙏

3. **补充内容:**
谢谢大佬，辛苦了☕☕☕

**Comment by Candinya** [comment]
好的，我明天看看，看起来应该很快就能加上

**Comment by Candinya** [comment]
新版本里加上了（看起来好像是只支持对单个文章的阅读统计，不能在首页显示每一篇文章的阅读量），可以试一试
