### ISSUE TITLE
字数统计的显示问题

### ISSUE THREAD

**Issue by korin5** [Candinya/Kratos-Rebirth#177]
超过1k的字数会这样显示：
![image](https://user-images.githubusercontent.com/63297666/216006373-a39212d7-7f5c-41ef-b78f-71cb427c0276.png)

我觉得把`~`去掉比较好，在`\Kratos-Rebirth\layout\post.ejs`的23行：
```
~ <%= (wordsCount / 1000).toFixed(2) %>K
```

![image](https://user-images.githubusercontent.com/63297666/216009527-81d8329e-73a6-4474-92cb-5d992708dce8.png)

（不会提交请求，就提交issue了）

**Comment by Candinya** [comment]
加了一个参数来控制，可以在主题配置里面设置这段内容来关闭，等下个版本发版就可以了
```yaml
misc:
  showWordCountEstimateWavy: false
```

**Comment by Candinya** [comment]
新版本已经发布，可以试一试了
