### ISSUE TITLE
您好~，我在使用过程中，如何开启toc遇到了麻烦

### ISSUE THREAD

**Issue by wumingzhilian** [Candinya/Kratos-Rebirth#18]
在咱的主题中配置文件里面没有发现toc的开启，我看着咱最近发的说明也没找到

**Comment by Candinya** [comment]
toc是在每篇文章的front-matter信息区指定哒，当指定toc为true的时候，就可以对当前文章开启啦w
主题的设置是在widgets那边哦，默认是包含哒w
可以参照[这个Wiki](https://github.com/Candinya/Kratos-Rebirth/wiki/Configuration-Manual-%E9%85%8D%E7%BD%AE%E6%89%8B%E5%86%8C#%E6%96%87%E7%AB%A0%E9%A1%B5%E9%9D%A2)哦~

**Comment by wumingzhilian** [comment]
嗯~这边一开true就，然后访问本地，就会报好多错

**Comment by Candinya** [comment]
能麻烦贴一下错误的输出信息吗，方便确定具体原因呢。

**Comment by wumingzhilian** [comment]
Unhandled rejection Error: D:\github\blog\themes\Kratos-Rebirth-master\layout\layout.ejs:6
    4|     <%- body %>
    5| </div>
 >> 6| <%- partial('_partial/footer') %>

D:\github\blog\themes\Kratos-Rebirth-master\layout\_partial\footer.ejs:4
    2|             <section id="kratos-widget-area" class="col-md-4 hidden-xs hidden-sm">
    3|                 <% theme.widgets.forEach(function(widget){ %>
 >> 4|                     <%- partial('_widget/' + widget) %>
    5|                 <% }) %>
    6|             </section>
    7|         <% } %>

Partial _widget/[object Object] does not exist. (in _partial\footer.ejs)
    at Object.partial (D:\github\blog\node_modules\hexo\lib\plugins\helper\partial.js:16:11)
    at eval (D:\github\blog\themes\Kratos-Rebirth-master\layout\_partial\footer.ejs:17:17)
    at Array.forEach (<anonymous>)
    at eval (D:\github\blog\themes\Kratos-Rebirth-master\layout\_partial\footer.ejs:14:22)
    at footer (D:\github\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (D:\github\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\github\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\github\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\github\blog\themes\Kratos-Rebirth-master\layout\layout.ejs:19:17)
    at layout (D:\github\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\github\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\github\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\github\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (D:\github\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\github\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\github\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\github\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\github\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\github\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\github\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\github\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\github\blog\node_modules\bluebird\js\release\async.js:15:14)

**Comment by wumingzhilian** [comment]
您看看什么问题

**Comment by Candinya** [comment]
> Partial _widget/[object Object] does not exist. (in _partial\footer.ejs)

这边感觉是您的配置文件出现了问题呢，能麻烦贴一份您**主题文件夹**下的_config.yml文件吗（就是根据[特别提示](https://github.com/Candinya/Kratos-Rebirth#%E7%89%B9%E5%88%AB%E6%8F%90%E7%A4%BA)的提示，`手动复制一份_config.yml.example，并改名为_config.yml`的这个文件），如果您在配置widget的时候出现了异常情况（例如错误的缩进），那么是有可能导致调用时候出现类似的异常问题的呢。

**Comment by wumingzhilian** [comment]
# Global
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo:
snow: false
enableDark: true
index_post_type: false

# Top Menu
menu:
  index: /
  archives: /archives/

    

label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>档案馆
  friends: <i class="fa fa-mars-double"></i>好伙伴
  about: <li><i class="fa fa-paper-plane"></i>关于我
# Footer
group_link: 
contact:
  weibo: 
  mail: 
  telegram: wumingzhilian
  twitter: wumingzhilian
  facebook: 
  linkedin: 
  fediverse:
    instance: 
    username: 
  github: wumingzhilian
  rss: atom.xml
timenotice: 本站已运行
  
# Post Page
posts:
  show_cc: true
  donate: true
  share: true
  comments: disqusjs

# Disqus
disqus:
  shortname: 

# DisqusJS
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# APlayer
aplayer:
  enabled: true
  playlist: 
  order: random

# Widgets
sidebar: right
widgets:
- about
- toc: true
- category
- tagcloud
- posts
avatarUri: /images/avatar.png

# Fancybox
fancybox: true

# 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript相关的配置
# 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    picCDN: false
    createTime: "1970-01-01 00:00:00"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.jpg"
    qr_wechat: "/images/wechatpayqr.png"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: ""

**Comment by vensing** [comment]
> * avatarUri: /images/avatar.png

这里请不要有空格或者制表符

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/89263463-e7f63480-d663-11ea-943b-874b8256562a.png)
这里配置错误啦，toc:true是写在`Front-Matter`（就是每一篇文章的起始位置），每一篇文章独立配置的哦，这里的小挂件指出的只是说主题整体开启toc的呢

**Comment by vensing** [comment]
> * avatarUri: /images/avatar.png

widgets:
- about
- toc
- category
- tagcloud
- posts
- avatarUri: /images/avatar.jpg

请勿将其他内容写入 widgets 配置。上面这么写重现了你的错误。

正确写法如下：
>
widgets:
- about
- toc
- category
- tagcloud
- posts

avatarUri: /images/avatar.jpg

**Comment by Candinya** [comment]
> > * avatarUri: /images/avatar.png
> 
> widgets:
> 
> * about
> * toc
> * category
> * tagcloud
> * posts
> * avatarUri: /images/avatar.jpg
> 
> 请勿将其他内容写入 widgets 配置。上面这么写重现了你的错误。
> 
> 正确写法如下：
> 
> > 
> 
> widgets:
> 
> * about
> * toc
> * category
> * tagcloud
> * posts
> 
> avatarUri: /images/avatar.jpg

这个是Github显示格式的问题，原po的配置是正确的（悲

![image](https://user-images.githubusercontent.com/20502130/89264121-f729b200-d664-11ea-918a-7d263cd3fb2b.png)

**Comment by vensing** [comment]
> - toc: true
去掉 `: true`

**Comment by wumingzhilian** [comment]
awwww，我这个在hexo-admin里面这么写的话预览的时候仍然是没有（太蠢了= =）
![image](https://user-images.githubusercontent.com/69114599/89265590-4ec91d00-d667-11ea-844d-79f898c25232.png)
![image](https://user-images.githubusercontent.com/69114599/89265615-58eb1b80-d667-11ea-8345-926d7a1c8300.png)

**Comment by vensing** [comment]
```
---
title: xxx
comments: true
categories:
  - xxx
tags:
  - xxx
date: 
toc: true
---
```
这么写

**Comment by Candinya** [comment]
Front-Matter是指在文章内容之上，不显示出来，而是给Hexo作为页面参数什么的那些设置哦，记得不要放到内容里面去啦，例如就像这篇文章这样呢：
![image](https://user-images.githubusercontent.com/20502130/89265863-b8e1c200-d667-11ea-910d-1a816163efd4.png)

**Comment by wumingzhilian** [comment]
在hexo-admin里面写的md的话，好像是会存在的。。。。
![image](https://user-images.githubusercontent.com/69114599/89266498-91d7c000-d668-11ea-9ef1-56a4bccfc8a9.png)

![image](https://user-images.githubusercontent.com/69114599/89266447-86849480-d668-11ea-9332-e3d0bdbb4657.png)

**Comment by Candinya** [comment]
是的，因为目前Hexo-Admin暂时不支持编辑Front-Matter的内容呢，还是比较推荐*使用文本编辑器直接编辑md文件*的说呢w

**Comment by wumingzhilian** [comment]
谢谢师傅们~，两位大佬aww，我拿模板上了

**Comment by Candinya** [comment]
有任何疑惑欢迎随时再来问哦，预祝使用愉快啦~o(*￣▽￣*)ブ
