### ISSUE TITLE
关于从主页点击文章LaTeX失效

### ISSUE THREAD

**Issue by Light-Century** [Candinya/Kratos-Rebirth#180]
**对Bug的描述:**
blog使用了hexo-renderer-pandoc渲染和hexo-render-mathjax插件。
从blog首页直接点击文章进行查看，但mathjax并没有在进入的界面中加载。
但在网页刷新后或选择另起标签页打开便可以正常加载。

麻烦大佬帮助一下

**Comment by ArcticLampyrid** [comment]
可能相关的代码部分：
https://github.com/Candinya/Kratos-Rebirth/blob/f930f02b7fff6fc0160cc146bbd2ea2f52af7e01/src/js/kratosr.js#L705-L710

**Comment by ArcticLampyrid** [comment]
Kratos-Rebirth 的测试是基于 [hexo-math](https://www.npmjs.com/package/hexo-math) 插件做的，可以尝试更换为 [hexo-math](https://www.npmjs.com/package/hexo-math) 插件渲染数学公式，看看是否正常
另外，也可以尝试使用 server-side 的 render：
- [hexo-filter-katex](https://www.npmjs.com/package/hexo-filter-katex)
- [hexo-filter-mathjax](https://www.npmjs.com/package/hexo-filter-mathjax)
