### ISSUE TITLE
新功能建议：增加wordcount关闭选项/wordcount字数统计不准确

### ISSUE THREAD

**Issue by EFF-Mr-W** [Candinya/Kratos-Rebirth#181]
### 报告前须知

- [X] 我已确认该功能确实不存在
- [X] 我会认真详细地描述清楚我想要的功能

### 您的新功能建议是由使用时出现的不便引发的吗？

是

### 请描述您所设想的功能或是解决方案

增加wordcount开启关闭选项或优化wordcount统计算法

### 补充内容

Hello,
Maintenance team:

感谢你们一直以来的持续维护。
我正使用该主题来制作英文版博客。
在此期间，我发现文章页面的字数统计与实际结果存在较大差异。 基于我的调查，我猜测你们使用的是william 所编写的[hexo wordcount](https://github.com/willin/hexo-wordcount) ， 该plugin似乎使用的是基于统计空格的字符数进行计数，实际上，其中文统计也并不精准，更由于英文单词的构成导致该统计与实际结果大相径庭。
因此，基于该项目已多年未做维护，以及该功能可能产生的较大误导性质，我希望可以添加一个switch灵活选择wordcount 开启及关闭。 当然，如果你们愿意尝试优化该统计算法的中英文统计，那是再好不过，不过我想前者应该是一个更好达到的请求，wordcount对我来说不是必须。

Thanks!
Mr.W

**Comment by Candinya** [comment]
其实现在的字数统计就是非常简单粗暴地统计字符，确实对非独字符语言不太友好
是一个好建议，会加一个选择是否开启的选项

https://github.com/Candinya/Kratos-Rebirth/blob/d92945e627ba8e297df6da04ec2306ca3c80feb4/layout/post.ejs#L19-L24

**Comment by Candinya** [comment]
添加了一个控制开关，会在下个版本发布时候合并入生产环境

**Comment by Candinya** [comment]
新版本发布了，您可以试一试
https://github.com/Candinya/Kratos-Rebirth/blob/5fe84b262f428ca6be73f4d46aeb182c3babc400/_config.yml#L104-L106
