### ISSUE TITLE
请问怎么修改index页面默认的hexo内容呢

### ISSUE THREAD

**Issue by TobeMagic** [Candinya/Kratos-Rebirth#183]
### 报告前须知

- [X] 我已确认该功能确实不存在
- [X] 我会认真详细地描述清楚我想要的功能

### 您的新功能建议是由使用时出现的不便引发的吗？

是的

### 请描述您所设想的功能或是解决方案

很好

**Comment by TobeMagic** [comment]
index页面banner的那个默认标题hexo

**Comment by TobeMagic** [comment]
非常感谢如果您能抽空回答的话

**Comment by Candinya** [comment]
这个是站点配置（ `_config.yml` ）的内容，
主标题是 `title` ，副标题是 `subtitle` ，个人简介模块的内容是 `description` ，
可以在这些地方修改

**Comment by TobeMagic** [comment]
非常感谢！



---Original---
From: "Nya ***@***.***&gt;
Sent at: 2023年3月23日(Thu) PM4:36
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Candinya/Kratos-Rebirth] 请问怎么修改index页面默认的hexo内容呢 (Issue #183)




 
这个是站点配置（ _config.yml ）的内容，
 主标题是 title ，副标题是 subtitle ，个人简介模块的内容是 description ，
 可以在这些地方修改

**Comment by ArcticLampyrid** [comment]
宝子们，如果还有问题的话，可以看看[站点配置Hexo官方文档](https://hexo.io/zh-cn/docs/configuration)和[Kratos-Rebirth主题配置文档](https://github.com/Candinya/Kratos-Rebirth/blob/master/Kratos-Rebirth-Manual.md)哦

**Comment by TobeMagic** [comment]
好嘞感谢感谢！



---Original---
From: ***@***.***&gt;
Sent at: 2023年3月24日(Fri) AM8:23
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Candinya/Kratos-Rebirth] 请问怎么修改index页面默认的hexo内容呢 (Issue #183)




 
宝子们，如果还有问题的话，可以看看站点配置Hexo官方文档和Kratos-Rebirth主题配置文档哦
