### ISSUE TITLE
新功能建议： （增加畅言评论系统）

### ISSUE THREAD

**Issue by mvfeng** [Candinya/Kratos-Rebirth#190]
### 报告前须知

- [X] 我已确认该功能确实不存在
- [X] 我会认真详细地描述清楚我想要的功能

### 您的新功能建议是由使用时出现的不便引发的吗？

是的

### 请描述您所设想的功能或是解决方案

畅言官网 https://changyan.kuaizhan.com/

**Comment by mvfeng** [comment]
希望如果可以的话换成hugo博客

**Comment by ArcticLampyrid** [comment]
offtopic
