### ISSUE TITLE
[Question]：文章pic路径如何填写？

### ISSUE THREAD

**Issue by yaoyu49** [Candinya/Kratos-Rebirth#194]
### 报告前须知

- [X] 我已确认该功能确实不存在
- [X] 我会认真详细地描述清楚我想要的功能

### 您的新功能建议是由使用时出现的不便引发的吗？

pic那个文章的缩略图的具体设置是什么
我一直设置不对

### 请描述您所设想的功能或是解决方案

pic那个文章的缩略图的具体设置是什么
我一直设置不对

**Comment by ArcticLampyrid** [comment]
dup of #157
