### ISSUE TITLE
APlayer中的enabled设置为false，播放器照样显示  

### ISSUE THREAD

**Issue by MyFloret** [Candinya/Kratos-Rebirth#196]
### 报告前须知

- [x] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

使用 npm 等包管理工具安装至 node_modules 目录下

### 对 Bug 的描述

配置项APlayer中的enabled设置为false，播放器照样显示  

### 复现的方法

APlayer中的enabled设置为false，播放器照样显示  

### 期望的行为

播放器不显示

### 运行环境

windwos10

**Comment by jht3QAQ** [comment]
问题未能复现

**Comment by ArcticLampyrid** [comment]
请给出您的具体配置方法和配置信息

**Comment by MyFloret** [comment]
> 请您给出具体的配置方法和配置信息
