### ISSUE TITLE
Bug 回报：标签聚合变成全大写

### ISSUE THREAD

**Issue by ted423** [Candinya/Kratos-Rebirth#208]
### 报告前须知

- [X] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

使用 npm 等包管理工具安装至 node_modules 目录下

### 对 Bug 的描述

对于分辨率来说，大写P其实属于错误写法。并且我点进去，url是小写，会报404，相反，之前不注意写错的tag倒是可以正常显示（正在修，一会就没了）。

### 复现的方法

https://ted423.github.io/tags/1080p/

### 期望的行为

不全都改成大写

### 相关的截图

![image](https://github.com/user-attachments/assets/3c227c0a-09a5-41cf-b417-912363c957c5)

### 运行环境

Win11 chrome

**Comment by ted423** [comment]
不知道为啥 1080i可以点进去 1080p 不行。
写错的720P可以（目前已经没了），正确的就不行
https://ted423.github.io/tags/1080P/
测试1080P改大写可以，印象里使用开始使用这个模板的时候可能有tag写成 1080P的，现在应该修正了。使用了 filelocatetor 进行了区分大小写的搜索来确认这件事情

**Comment by ted423** [comment]
![image](https://github.com/user-attachments/assets/73a31daa-19b8-4ec7-a169-0c841b4eb1a9)
突然想起来win不区分大小写

**Comment by ted423** [comment]
https://www.git-scm.com/docs/git-config/2.14.6#Documentation/git-config.txt-coreignoreCase

查了下，大小写这块可以有这块设置。这块解决了。





但是希望标签聚合不要全大写，因为有些字母大小写代表了完全不同的意思 例如 MB/s Mb/s。（通常来说是Mbps和MB/s的写法，不过p=/）
其中B是Byte,b是bit。1Byte=8bit

https://answers.openeye.net/Troubleshooting/Frequently_Asked_Questions/Network/Bit_vs_Byte_(Mbps_vs_MBps)

**Comment by ted423** [comment]
升级到了v3 dev,看起来行为还是一样的

**Comment by Candinya** [comment]
是样式配置的问题，更新了一下样式，可以试试 `v3.0.0-dev.8`

**Comment by ted423** [comment]
辛苦
