### ISSUE TITLE
Bug 回报：V3 版本使用 CDN 有资源加载问题

### ISSUE THREAD

**Issue by d-w-x** [Candinya/Kratos-Rebirth#210]
### 报告前须知

- [X] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

Git clone 项目仓库至 themes 目录下

### 对 Bug 的描述

开启CDN后，静态资源实际上无法访问：
- 浏览器试图访问的资源 `https://cdn.jsdelivr.net/npm/hexo-theme-kratos-rebirth@3.0.0-alpha.0/css/kr-core.min.css`
- 实际上存在的资源 `https://cdn.jsdelivr.net/npm/hexo-theme-kratos-rebirth@3.0.0-alpha.0/source/css/kr-core.min.css`

### 复现的方法

开启配置中的 CDN，执行 `pnpm run server` ，浏览器打开页面即可发现资源缺失。

### 期望的行为

正确加载相关资源

### 运行环境

- "hexo-theme-kratos-rebirth": "3.0.0-alpha.0"
- "hexo": "^7.3.0"

### 主题配置文件

```yaml
vendors:
  npm_cdn: "https://cdn.jsdelivr.net/npm/" # 默认使用站点直接提供
```

**Comment by Candinya** [comment]
更新了一下代码，可以试试 `3.0.0-alpha.1` 是否修复了这个问题
