### ISSUE TITLE
Bug 回报： toc 样式的一些问题 自动展开 或者设置是否浮动

### ISSUE THREAD

**Issue by ted423** [Candinya/Kratos-Rebirth#211]
### 报告前须知

- [X] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

使用 npm 等包管理工具安装至 node_modules 目录下

### 对 Bug 的描述

一些二级或者更高的目录会因为不自动展开无法显示。因为文章比较长，目录比较短。下拉的时候toc已经不见了

就个人习惯而言，感觉分类和标签不太需要浮动，反倒是toc会希望经常使用。

### 复现的方法

https://fxxs-encoder.github.io/2.Tools/Demux&Remux/#FFmpeg

### 期望的行为

目前的想法是如果toc超过页面高度，就不进行浮动，反之可以浮动展示(多级目录折叠也可以根据这个？)

不过完全展开，不浮动也不折叠说不定简单一些

### 运行环境

vivaldi

**Comment by Candinya** [comment]
可以检查一下主题配置的 `sidebar.widgets` 配置项里 splitter 是不是放在了 toc 下面，导致 toc 在页面滚动时被顶上去了

toc 要默认展开的话其实直接追加一下样式就行（ `#kratos-widget-area #krw-toc .toc-item>.toc-child` 是通过 max-height 限制来实现隐藏效果的，追加 CSS 里给它设置成 unset 就可以去掉这个隐藏）

**Comment by ted423** [comment]
确实是被顶上去了
