### ISSUE TITLE
请问主题不支持开启mathjax么

### ISSUE THREAD

**Issue by 7att1ce** [Candinya/Kratos-Rebirth#24]

**Comment by Candinya** [comment]
我没有测试过（事实上在我搜索之前我都没听说过这个（小声）
可以考虑作为一个新的features准备加入~

**Comment by 7att1ce** [comment]
啊这
辛苦作者了ヾ(≧▽≦*)o

**Comment by Candinya** [comment]
大概是已经添加上去了，可以测试一下啦
有发现什么bug的话欢迎随时联系哦~
在涉及转义符号的时候记得注意一下和MarkDown的兼容，为了能在前端显示出来，有些单反斜杠可能要写成两个。具体的可以参阅[提交记录的说明](https://github.com/Candinya/Kratos-Rebirth/commit/e5b3e7ecdc368f69faa15ee068dbc1dda32b8e73)。

**Comment by 7att1ce** [comment]
emm不知道为什么我的公式没有渲染出来
公式直接消失了
我的mathjax配置方法参考的是这个 https://www.jianshu.com/p/68e6f82d88b7

**Comment by Candinya** [comment]
仔细检查了一下，发现是因为这些设置会让公式以script的形式呈现，之后调用`hexo-renderer-mathjax`插件来实现相关代码的载入与渲染工作，所以是因为本主题没有调用该插件导致的，我会再去研究研究相关的操作吧（
![image](https://user-images.githubusercontent.com/20502130/93547183-0192d780-f997-11ea-8ded-2e53a661ee27.png)
我这个主题这边功能的实现方案比较偷懒，是直接使用前端调用压缩整合后的MathJax库，并且在ajax操作后也有重置代码，所以不需要那些复杂的配置啦，直接在文章内写入$$包括起来的公式，就能使用了（逃
![image](https://user-images.githubusercontent.com/20502130/93547263-3acb4780-f997-11ea-898c-f34c7dae861b.png)
不过也因此导致了部分转义符号的麻烦（小声

**Comment by Candinya** [comment]
我大概知道MathJax为什么不支持了（
这个插件是通过搜寻layout.ejs中的`</body>`标签，在此之前插入相应的代码来实现注入的，但是我整理的时候把这个标签放到footer.ejs里面去了（（
将在下一个commit中修复，怀疑其他插件无法正常注入也是因为这个原因了（
![image](https://user-images.githubusercontent.com/20502130/95478393-0ce88a00-09bc-11eb-9306-9d48f7afcfd2.png)

**Comment by Candinya** [comment]
应该已经修复，可以测试一下看看啦
