### ISSUE TITLE
新 功能

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#25]
能支持valine吗？valine真的很好，而且我想在markdown生成的html中，head自动加上谷歌等使用站长资源要加的那个，还有谷歌百度一些统计访问人数的东西

**Comment by greenhandzdl** [comment]
还要就是一些其他的，例如封面图cover能不能满足，我想直接链接我的图床

**Comment by Candinya** [comment]
可以试一试啦，有什么bug或是推荐的优化方案之类的欢迎随时提出哦 😆

**Comment by Candinya** [comment]
统计访问人数之类的可以将那一块代码整理成一行放到主题设置的`site_analytics`段（就是用script包起来的那一大段东西，整理成一行，在渲染页脚的时候会自动渲染出来的

**Comment by greenhandzdl** [comment]
> 统计访问人数之类的可以将那一块代码整理成一行放到主题设置的`site_analytics`段（就是用script包起来的那一大段东西，整理成一行，在渲染页脚的时候会自动渲染出来的

咳咳，其实我是想说向谷歌那些搜索引擎证明所有权加在head的代码

**Comment by Candinya** [comment]
加入了Google搜索的所有权验证模块，直接在配置文件底部对应位置里填写content中的那一串随机码即可 🚀

**Comment by greenhandzdl** [comment]
> 加入了Google搜索的权限验证模块，直接在配置文件底部对应位置里填写内容中的那一串随机码即可 🚀
> 
> 另外还约会了valine的文章阅读统计模块，至少已经启用了w

咳咳，那么百度和必应啥的我就在下面加上baidu是不是啊

**Comment by Candinya** [comment]
> > 加入了Google搜索的权限验证模块，直接在配置文件底部对应位置里填写内容中的那一串随机码即可 🚀
> > 另外还约会了valine的文章阅读统计模块，至少已经启用了w
> 
> 咳咳，那么百度和必应啥的我就在下面加上baidu是不是啊

不，我不知道那些的元数据长什么样所以没有引入（（
如果有样例可供参考的话也就可以添加上去啦 🤣

**Comment by greenhandzdl** [comment]
> > > 加入了Google搜索的权限验证模块，直接在配置文件底部对应位置里填充内容中的那一串随机码即可 🚀
> > > 另外还约会了valine的文章阅读统计模块，至少已经启用了w
> > 
> > 
> > 咳嗽，那么百度和必应啥的我就在下面加上baidu是不是啊
> 
> 不，我不知道那些的元数据长某种所以没有约会（（
> 如果有样例注意到参考的话也就可以添加上去啦🤣

咳咳，我是隔壁nexmoe迁移过来的，但是他们那里issue处理很慢，所以才换主题，他们那里应该有百度的那个，还有一个cover封面，能不能搞一个类似的，咳咳咳。

**Comment by Candinya** [comment]
> > > > 加入了Google搜索的权限验证模块，直接在配置文件底部对应位置里填充内容中的那一串随机码即可 🚀
> > > > 另外还约会了valine的文章阅读统计模块，至少已经启用了w
> > > 
> > > 
> > > 咳嗽，那么百度和必应啥的我就在下面加上baidu是不是啊
> > 
> > 
> > 不，我不知道那些的元数据长某种所以没有约会（（
> > 如果有样例注意到参考的话也就可以添加上去啦🤣
> 
> 咳咳，我是隔壁nexmoe迁移过来的，但是他们那里issue处理很慢，所以才换主题，他们那里应该有百度的那个，还有一个cover封面，能不能搞一个类似的，咳咳咳。

好耶，我去*友好借鉴*一下 😆

**Comment by Candinya** [comment]
应该是已经加上啦，有什么问题的话欢迎随时跟进哦

**Comment by greenhandzdl** [comment]
那么py友链，咳咳咳，其实我并不想改动.md文件

**Comment by greenhandzdl** [comment]
咳咳，google的analytics统计和百度统计很不错。

**Comment by Candinya** [comment]
> 那么py友链，咳咳咳，其实我并不想改动.md文件

本主题的[友链模块](https://github.com/Candinya/Kratos-Rebirth-Specified-Pages/blob/master/source/friends/index.md)是外部定制的页面模块，迁移几个参数（链接、头像、昵称、Bio）即可完成设置。您可以手动新建需要的页面，应该并不是很麻烦。
或者如果您更偏向于自定义的文章页面那种格式，也可以直接加入需要的内容与格式。

**Comment by greenhandzdl** [comment]
那么两边about页面都差不多相同吧

**Comment by Candinya** [comment]
可能有些区别，这边的页面只有准备对应的特定文件，可以参考[Kratos:Rebirth 主题特定页面](https://github.com/Candinya/Kratos-Rebirth-Specified-Pages)这个项目，自行设置相关的文件与配置呢。

**Comment by greenhandzdl** [comment]
我记得隔壁好像还有QQ群的链吧，emmm，不会自己改

**Comment by greenhandzdl** [comment]
还有字数统计，人数统计

**Comment by Candinya** [comment]
QQ群这个是被我砍了的，一定要加的话等会我再去加一下，但是那个加群格式不是特别好处理，可能需要把整个链接丢上去了
阅读人数统计已经用valine的加上去了，字数统计我在研究

**Comment by greenhandzdl** [comment]
> QQ群这个是被我砍了的，一定要加的话等会我再去加一下，但是那个加群格式不是特别好处理，可能需要把整个链接丢上去了
> 阅读人数统计已经用valine的加上去了，字数统计我在研究

咳咳，就是我习惯接其他的API，谷歌百度那里都有，还有隔壁nexmoe可以通过字数大概估计阅读时间。

**Comment by Candinya** [comment]
> > QQ群这个是被我砍了的，一定要加的话等会我再去加一下，但是那个加群格式不是特别好处理，可能需要把整个链接丢上去了
> > 阅读人数统计已经用valine的加上去了，字数统计我在研究
> 
> 咳咳，就是我习惯接其他的API，谷歌百度那里都有，还有隔壁nexmoe可以通过字数大概估计阅读时间。

记错了，QQ群那边的功能并没有删除，只是需要将整个加群链接 ( https:\/\/jq.qq.com\/什么的 )那一串 放到 主题的配置文件 *(手动复制一份_config.yml.example，并改名为_config.yml)* 的`group_link` 字段，即可在页面右下角展示一个群组图标的小按钮，单击可以加入群

字数统计我大概有思路了，很快就能加上了，不慌

**Comment by greenhandzdl** [comment]
真的很期待这个新主题，如果都差不多出来了，我就换下测试下

**Comment by Candinya** [comment]
字数统计功能也加入啦，在每篇文章的标题下方内容栏可以看到，每篇文章都会自动开启

**Comment by greenhandzdl** [comment]
那么谷歌和百度的那个统计，咳咳

**Comment by Candinya** [comment]
> 那么谷歌和百度的那个统计，咳咳

把相关的代码用单引号包裹起来，统一塞到配置文件顶端的`site_analytics`块就可以了，因为考虑到可能会有很多不同的解决方案（例如喜欢用百度的、喜欢用Google的、喜欢用CNZZ统计的 或者是其他很多第三方的统计数据）等等，如果针对每一个都生产适配（并且调整pjax函数与内容）会导致主题变臃肿，所以我留了一个接口用于将相关的代码直接渲染到每一个页面的页脚中去，只需将<script>包裹的代码块作为字符串包裹起来（注意引号配对问题，不要冲突即可）
![image](https://user-images.githubusercontent.com/20502130/95418849-ec441400-096a-11eb-8ab2-38bbb63b1465.png)
![image](https://user-images.githubusercontent.com/20502130/95418874-f9f99980-096a-11eb-8623-382d66fec5d8.png)

**Comment by greenhandzdl** [comment]
感谢，现在正在git下来，已经准备使用了

**Comment by greenhandzdl** [comment]
咳咳咳，能不能把除黑夜模式，加背景图，隔壁好像可以透明，但是chrome好像有点点bug。还有head的那个icon，当然搜狗还有神马的那些验证也不怎么会弄，能不能给个接口。

**Comment by Candinya** [comment]
“把除黑暗模式”是什么意思，想关闭的话去主题设置里把`enableDark`设置为false即可，**文档里有说明的**；站点图标是`site_logo`，**文档里也是有说明的**，自动变化不喜欢的话在`jsconfig`的`main`中`siteLeaveEvent`设置为false；背景图默认是有的，只是一半是透明像素了而已，把`source/images/bg.webp`更换成自己喜欢的图片即可，webp不知道是什么的话可以Google一下，文件名保持一致就可以；最后搜狗是个什么东西，那么多搜索引擎我是不是全都要做适配，一定要加的话head部分的模板文件在`layout/_partial/head.ejs`文件中，当成HTML来编辑，看不懂的部分不要去动，单纯添加自己需要的模块、元数据即可

**Comment by greenhandzdl** [comment]
但是背景图是链接呢

**Comment by Candinya** [comment]
> 但是背景图是链接呢

`kratos-rebirth/src/css/kratosr.css`文件最后，`background-image: url('/images/bg.webp')`部分，改成自己的图片地址，再跑一遍gulp压缩
懒得压缩的话直接去翻`source/css/kratosr.min.css`文件，虽然混成一团但是最后也能找到相应的关键词，替换成自己的图片地址即可

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-08-19-25-31](https://user-images.githubusercontent.com/61241103/95453026-bd469600-099c-11eb-8d19-643249f1130e.png)

![Screenshot_2020-10-08-19-25-03](https://user-images.githubusercontent.com/61241103/95452978-aef87a00-099c-11eb-8b46-e07182c22568.png)
![Screenshot_2020-10-08-19-25-10](https://user-images.githubusercontent.com/61241103/95452996-b3249780-099c-11eb-8002-029044683bda.png)
![Screenshot_2020-10-08-19-25-24](https://user-images.githubusercontent.com/61241103/95453010-b7e94b80-099c-11eb-8c9c-7a7c146c0dac.png)


![Screenshot_2020-10-08-19-24-41](https://user-images.githubusercontent.com/61241103/95452937-9f793100-099c-11eb-8427-d1b535c63a71.png)
![Screenshot_2020-10-08-19-24-50](https://user-images.githubusercontent.com/61241103/95452957-a607a880-099c-11eb-8246-43701c4f0090.png)
![Screenshot_2020-10-08-19-24-56](https://user-images.githubusercontent.com/61241103/95452969-ab64f300-099c-11eb-8e91-8dfb9b152a63.png)
比较奇怪的事飘红

**Comment by Candinya** [comment]
这里的generate操作是没有出错的，请问您是否有对于主题相关文件的修改？
以及如果方便的话，希望您可以附上您的主题配置文件（关键部分，如各种API Key请自行删除），以及您的站点环境json（即您安装了哪些插件，我们来排查是否可能出现不兼容的插件）

**Comment by greenhandzdl** [comment]
![IMG_20201008_195623](https://user-images.githubusercontent.com/61241103/95455441-778bcc80-09a0-11eb-9451-1ebe10073828.png)
![IMG_20201008_195700](https://user-images.githubusercontent.com/61241103/95455450-7b1f5380-09a0-11eb-8ff1-de9c83139117.png)
![Screenshot_2020-10-08-19-55-41](https://user-images.githubusercontent.com/61241103/95455459-7eb2da80-09a0-11eb-8f22-2387aa5e15fa.png)
还有就是谷歌统计那里只有ua-xxxx，没有scrip部分

**Comment by greenhandzdl** [comment]
> “把除黑暗模式”是什么意思，想关闭的话去主题设置里把`enableDark`设置为false即可，**文档里有说明的**；站点图标是`site_logo`，**文档里也是有说明的**，自动变化不喜欢的话在`jsconfig`的`main`中`siteLeaveEvent`设置为false；背景图默认是有的，只是一半是透明像素了而已，把`source/images/bg.webp`更换成自己喜欢的图片即可，webp不知道是什么的话可以Google一下，文件名保持一致就可以；最后搜狗是个什么东西，那么多搜索引擎我是不是全都要做适配，一定要加的话head部分的模板文件在`layout/_partial/head.ejs`文件中，当成HTML来编辑，看不懂的部分不要去动，单纯添加自己需要的模块、元数据即可

话说不是webp格式可以吗？对面是api，我也不知道是啥格式

咳咳，还有一个就是点继续阅读的时候进不去
![Screenshot_2020-10-08-20-09-50](https://user-images.githubusercontent.com/61241103/95456711-5035ff00-09a2-11eb-9a88-feb52ec7a079.png)
我也不知道什么情况

**Comment by Candinya** [comment]
不是webp的也完全没有问题，webp只是一个格式，通过API调用的直接改成API地址即可。
点不进去是因为页面渲染出现了问题导致的失败，我这边也还在测试具体的问题根源。
而您的配置存在部分细节上的瑕疵，例如posts的comments处，您也许需要填写valine以调用valine评论功能；aplayer处没有集成后端，您需要填写一个符合aplayer歌单格式的地址文件（之前我有[aplayer-simple-backend](https://github.com/Candinya/aplayer-simple-backend)，但是Meting使用的网页版API已经失效，所以这个项目暂时处于废弃状态），才能正确播放。
现在的情况是不知道您是否对于layout/post.ejs文件做出了修改进而导致了文章页面渲染的失败，关于Google统计的部分我会再去查询相关的信息的（因为我个人没有使用这些东西）

**Comment by greenhandzdl** [comment]
layout/post.ejs是直接git下来的，排除问题，发现是之前.md文件没有适配，正在抓紧适配中

**Comment by Candinya** [comment]
> layout/post.ejs是直接git下来的，排除问题，发现是之前.md文件没有适配，正在抓紧适配中

嗯，辛苦啦
如果能发现md文件中是哪里导致的问题，方便的话也可以帮忙提供一下具体的表现形式呢，如果是比较普遍的情况的话我这边也可以去加入相关的处理代码之类的呢

**Comment by greenhandzdl** [comment]
头图是pic吗？为什么我没有显示啊

**Comment by greenhandzdl** [comment]
不是pic头图吗？我写的404.md出来怎么显示不了，还有aplayer好像也不行，还有别的

**Comment by greenhandzdl** [comment]
.md文件到底是什么啊，脑瓜子感觉不够想了

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-08-21-27-46](https://user-images.githubusercontent.com/61241103/95465117-51b8f480-09ad-11eb-9f11-b7593e81a705.png)
![Screenshot_2020-10-08-21-28-28](https://user-images.githubusercontent.com/61241103/95465137-55e51200-09ad-11eb-898c-b94259267e86.png)
没显示头图，友链也没有了，头疼

**Comment by greenhandzdl** [comment]
> > 但是背景图是链接呢
> 
> `src/css/kratosr.css`文件最后，`background-image: url('/images/bg.webp')`部分，改成自己的图片地址，再跑一遍gulp压缩
> 懒得压缩的话直接去翻`source/css/kratosr.min.css`文件，虽然混成一团但是最后也能找到相应的关键词，替换成自己的图片地址即可

比较尴尬的是直接定位，但还是没有显示我改的

**Comment by Candinya** [comment]
移动端是没有头图显示的，桌面端会有头图的（如果配置没有问题的话
友链不应该会出问题，可以试着检查一下您的浏览器，例如使用类似Chrome这些主流浏览器进行尝试？如果您有生成静态文件的话，方便的话我可以协助进行相关的调试工作。
另外就是使用*indexPostType*时会将首页的文章直接进行渲染，所以设置的文章配图内容如果没有放在文章里的话，也就都丢掉了（
md文件指的是MarkDown格式的文件，这种格式相比起传统的HTML，具有更强的编辑友好性吧
404.md的问题可能是因为这边对于404页面没有特别正式的支持（因为按照原主题的格式，陈列方式和脚本内容不是很一致，但理论上应该并不存在相关的问题，也有可能是相关的兼容性难题）

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-08-21-50-06](https://user-images.githubusercontent.com/61241103/95467614-41eedf80-09b0-11eb-85f6-17d2ee8dfcb3.png)
实际上，emmm，头图还是没有

**Comment by greenhandzdl** [comment]
而且，我的live2d好像不能显示了

**Comment by Candinya** [comment]
站点相关的默认图片文件都在`source/images`文件夹下
站点的整体头图是banner.webp和banner_dark.webp（深色模式），
页面的头图需要自己在MarkDown中以图片格式引入，pic标注的只是在opengraph和卡片格式的首页（indexPostType为false）情况下展示的图片，是不会展示到文章内的；
您那边友链的情况看上去还是很奇怪，代码上不存在任何问题但是无法载入，也许需要比较详细的调试日志便于排除错误吧。
如果方便的话，您可以考虑将站点的原始文件（除去node_modules文件夹中的部分）或是这些生成的临时文件打成压缩包，传送给我以协助进一步的debug处理。

**Comment by Candinya** [comment]
我怀疑这个主题含有和部分插件不兼容的部分，例如mathjax和live2d这些，目前已知mathjax在一般主题中会引入的代码块在本主题中同样无法引入导致公式无法渲染（ #24 ），我会再继续研究相关的详细情况

**Comment by greenhandzdl** [comment]
所以怎么发，邮箱吗？我觉得建个群聊也是有必要的，毕竟issues翻有点点累

**Comment by Candinya** [comment]
把之前和MathJax冲突的部分、导致页面渲染失败的部分都已经修复了（找到了那个多出来的分号并且清理掉了）
现在可以再试一试了

**Comment by greenhandzdl** [comment]
live2d还是没有解决，背景图感觉文件写的太混乱了，希望给个接口，然后markdown写code语法夸克显示不正常，最后，就是谷歌统计这玩意，ua-xxx他没给code，要不去隔壁看看，emmm

**Comment by greenhandzdl** [comment]
好吧，我pic加的是我图床链接，但是就是显示不出来感觉很奇怪

**Comment by Candinya** [comment]
背景图配置就在CSS那个位置，现在主题还没改成scss写css资源所以暂时只能丢在静态文件里面，sources/css/kratosr.min.css是为了加载性能被压缩过的，自然乱，原本的src/css/kratosr.css文件都有分区的，涉及到图片资源的全部丢在最底下，，压缩完之后也在最底下所以直接找那关键词bg.webp就可以
以及关于MarkDown语法渲染的问题，如果所有浏览器显示不正常那是主题相关兼容性的锅，夸克就一个非主流浏览器显示不正常那就不是主题的问题，是浏览器自身兼容的问题，
然后关于Google Analytics我说了**整段代码引号包起来放在站点配置第一项site_analytics段**是因为我表达能力不行还是您看不到我举的例子，这段东西我说了留了接口的直接丢进去就可以了，那我像下图这样演示请问您可以不可以，，我真的不想再往主题里加这种偷人隐私的流氓代码了，所以留了接口要加的话自己加进去就可以了，，
有单双引号问题的话自行调整一下，像我把所有内部的单引号全部换成双引号，这样就不会和外部的大单引号冲突导致内容错误了（yaml似乎没法使用反引号）
然后关于图片载入不出来是指怎样的报错，有没有浏览器调试器截图，源代码里面对应的图片文件是否生成正确，有没有可能是因为CORS或是referrer的问题，浏览器报错404还是403还是其他什么（例如生成的链接有误），我什么都没法知道的情况下怎么debug，，，
![image](https://user-images.githubusercontent.com/20502130/95587025-1e8d6880-0a74-11eb-86e8-d266b18aa175.png)
![image](https://user-images.githubusercontent.com/20502130/95587066-2947fd80-0a74-11eb-969d-fac3db50ac17.png)

**Comment by greenhandzdl** [comment]
INFO  Files loaded in 7.17 s
INFO  Generated: config/main.json
FATAL {
  err: [Error: EEXIST: file already exists, mkdir] {
    errno: -17,
    code: 'EEXIST',
    syscall: 'mkdir'
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by greenhandzdl** [comment]
还有就是对pic感觉很迷惑
![Screenshot_2020-10-10-19-28-24](https://user-images.githubusercontent.com/61241103/95655264-9ae97f80-0b38-11eb-9863-cbb41738de07.png)
但是实际上是
![Screenshot_2020-10-10-20-37-55](https://user-images.githubusercontent.com/61241103/95655279-ac328c00-0b38-11eb-9e85-7384b9d4c944.png)
![Screenshot_2020-10-10-20-38-34](https://user-images.githubusercontent.com/61241103/95655282-afc61300-0b38-11eb-9a77-7b3a565d0438.png)
必须在本地吗？如果必须，那么跟我直接在文章插图片，more隔开有区别吗？

**Comment by greenhandzdl** [comment]
并且关于这个主题，还有比较尴尬的是，不知道书写，所以d不上去

**Comment by greenhandzdl** [comment]
好吧，我觉得pic可能不怎么有。。。感觉还是直接插入好。。。emmm，就这样吧。

**Comment by Candinya** [comment]
每篇文章的pic指的是**卡片模式下**当前文章在首页的卡片展示图（以替代随机的图库图片），并不是指当前文章的内容背景图；在站点设置中*indexPostType*模式为true的情况下，文章是没有卡片图的（因为是相当于直接开始文章的阅读了，包括”阅读更多“按钮是会在页面加载完成之后跳转到more标签之后的内容），需要带图片的话您需要关闭这个选项，使用传统的卡片格式；
如果您需要指定整个站点的背景图，您暂时需要调整css中对应的位置：目前由于使用静态css语言开发，所以暂时没法引入变量，请您谅解，我会在之后改写成scss进行相应的升级；
如果您需要针对每篇文章自定义背景图，您也许需要一些其他的方法来实现；
主题的话我是提交到Github Registry的，所以使用的时候并不能像npm那样直接安装hexo-theme-什么的这些，需要使用`npm install @candinya/kratos-rebirth`来进行安装和包管理。
但是请注意，由于发布版一般更新的并不如开发版快速，因而更多时候还是推荐使用开发版，并且将生成的静态文件直接使用`hexo d`部署，或是其他的手动git push指令等。
给您的工作带来的不便还请您谅解。

**Comment by greenhandzdl** [comment]
比较尴尬的是，在我这边py友链这个并没有正常，所以采用了名字（标题）插入图片加链接
还有的是，头图，不是背景图，我还是改成了文章插入外部图片方式，emmm，我感觉对主题放弃治疗了，能跑就好

**Comment by greenhandzdl** [comment]
其实我喜欢more功能，但鱼与熊掌不可兼得，然后我就在more的前面插入小卡片，emm

**Comment by Candinya** [comment]
嗯，抱歉给您的使用体验造成了不舒适的体验呢，主要是考虑主页使用卡片模式在横向布局的桌面端，和纵向展开的布局在移动端这样搭配对于各种内容有相对较强的兼容性（而且也是原主题的设计风格），所以是这样设计的；关于indexPostType和more功能这些，其实是为了向传统的hexo主题那种看齐，包括为了凸显一些内容偏向为主的博客，所以特别单独设置出来的样式，可能各方面的体验并没有做到尽善尽美吧，之后我会尝试继续引入相关的优化的（例如使用卡片格式的移动端样式来优化等）
友链渲染方面目前我也不是很有头绪，可能是哪边存在一些细节上的冲突导致无法运行与渲染吧，之后的情况和测试升级之类的我也会继续跟进的。
如果您有其他任何使用上的问题或是建议也欢迎您随时继续提出，开源的项目离不开大家的努力与支持，祝您使用愉快。

**Comment by greenhandzdl** [comment]
最后说点建议吧
# live2d小人物感觉很有趣，但是也不知道什么时候兼容，如果不打算弄的话，希望能tell me
# 其次就是friends好像不怎么行，emmm，让人遗憾
# 最后就是我比较期盼的背景图了，真的，改文件什么的我真不会弄，要不给个接口吧，你说呢
# 除此之外，就是config能不能多点注释，emm，就是这里坑了点时间。还有就是教程能不能完善一点点，毕竟不一定是随时随刻都能被指点，那么我觉得还不如把指点的都整理一下，防止新手走弯路。
# 真的是最后了，能不能组个交流群啊，issue从最开始翻到最后面是真的痛苦。

**Comment by Candinya** [comment]
1. live2d不是主题不兼容，是您自己配置可能存在些许欠缺的地方，该渲染的模块全都已经渲染出来了，但是您对于live2d插件相关的路径配置不正确导致您引用了错误的地址，无法载入人物，所以无法完成渲染实现；您可以再检查一下相关插件的描述是否存在需要额外注意的内容，例如去翻一翻他们的文档；而根据目前的情况来看，渲染的模块的位置也会挡住主题的功能区按钮，您可能需要进一步地调整目标插件的相关配置参数；
![image](https://user-images.githubusercontent.com/20502130/95660149-7d2c1280-0b58-11eb-84c1-ee2eeadf2dd6.png)
2. 友链部分我确实没法确认是什么原因导致的异常，我会将我的友链页面原始文件夹打包成压缩包附在以下，以方便您的测试和相关的调整；
[candinya-friends-page.zip](https://github.com/Candinya/Kratos-Rebirth/files/5359432/candinya-friends-page.zip)
3. 背景图接口会改写，之后会使用scss重构整个主题的CSS资源文件，预期会引入一些变量；
4. config文件的注释**全部写在[文档](https://github.com/Candinya/Kratos-Rebirth/wiki/Configuration-Manual-%E9%85%8D%E7%BD%AE%E6%89%8B%E5%86%8C)里面**，并且**项目的首页就有提到文档**，希望您是有好好阅读过之后再提出的疑问；本主题没什么特别需要注意的教程，基本属于开箱即用的那种（我样例站的构建也只修改了没几个参数），看到不懂的就翻文档，没写清楚或是没理解的就开issue问即可；
5. 建交流群我以前也试过，但实际测试体验不佳，所以最终还是放弃了这个方案；并且不希望这个项目会像某些项目那样逐渐由建群变成建墙最终变成开发者恰烂钱的工具，所以我宁可盯着收件箱多翻issue也不想给所有人带来麻烦。

如果您的疑问暂时已经得到了解决，那么我会先关闭这个issue。如果您有其他任何需要补充说明的内容，您可以随时再开启。非常感谢您的理解与支持，祝您使用愉快，身体健康，工作顺利。
