### ISSUE TITLE
404页面暂时不受支持

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#26]
是不是404页面还不支持啊？我访问自己的404页面只能后面加入/404进入。

**Comment by Candinya** [comment]
0. 一个issue的标题请表达清楚你想问什么东西，别整一串形式主义的日期上来，issue不是您私人的日记本，谢谢。
1. 是的，页面格式和渲染问题，layout那边的格式对于404页面的兼容不是太好，hexo默认也没有404页面的样式，所以我的404页面是直接使用的静态文件，之后可能会使用外部代码注入的方式进行页面的生成。
我目前使用的404页面已通过附件附上，可以供您进行参考。将解压后的404.html文件放置在source文件夹下即可在站点生成时自动包含。
[candinya-404page-demo.zip](https://github.com/Candinya/Kratos-Rebirth/files/5360633/candinya-404page-demo.zip)
