### ISSUE TITLE
望针对优化

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#27]
![Screenshot_2020-10-13-06-24-55-39](https://user-images.githubusercontent.com/61241103/95795689-8b775b80-0d1d-11eb-9102-7d61c6c8eb4b.png)

**Comment by Candinya** [comment]
Google Search Console移动设备易用性那边的问题我会在之后我这边复现了的情况下进行调整与修复（因为它报错很玄学，之前有报错的记录现在会消失，所以我现在查不到可以用来示例的网站，之后能查到的话会排查样式中需要修正的部分）

**Comment by greenhandzdl** [comment]
> SEO的优化我之后也会看情况适当处理的，但是请注意，我有查询发现GitHub Pages是屏蔽了百度爬虫的（说是因为百度瞎爬太狠，弄得GitHub服务器像被打了一样），如果您有相关的服务需求（同时为了提高您的搜索引擎排名），建议您购买精简好记有含义的主流顶级域名（如.com、.org、.net这种）并进行CDN的搭建工作，一方面能切实提高用户的访问体验，另一方面也能通过相关的绕路方案来避免后端源站的限制吧。

但是换主题之前还是正常的，emm，我截图给你看看

![Screenshot_2020-10-14-18-55-45](https://user-images.githubusercontent.com/61241103/95980001-1ad05c00-0e4f-11eb-9ec0-fe859e49d366.png)
第一个是换主题前的，第二个是换主题后百度再次爬取的，真不知道什么情况

**Comment by Candinya** [comment]
不知是否可能是由于重复的description元数据导致的问题，目前已经将相关的重复项移除，并持续关注后续的情况。
或者也有可能是百度的抓取问题？同样使用该主题的我的博客似乎就没有出现这个问题，也许等待一段时间之后百度的数据库会自然修复这个错误的情况。
![image](https://user-images.githubusercontent.com/20502130/95983891-f24b6080-0e54-11eb-8ecf-3831bc26216a.png)

**Comment by greenhandzdl** [comment]
hexo-2dlive-helpful还是不能用，我换了其他主题还算正常
`"name": "hexo-site",                                                          "version": "0.0.0",                                                           "private": true,                                                              "scripts": {                                                                    "build": "hexo generate",
    "clean": "hexo clean",                                                        "deploy": "hexo deploy",                                                      "server": "hexo server"                                                     },                                                                            "hexo": {                                                                       "version": "5.2.0"                                                          },                                                                            "dependencies": {                                                               "hexo": "^5.1.1",                                                             "hexo-admin": "^2.3.0",                                                       "hexo-auto-category": "^0.2.0",                                               "hexo-baidu-url-submit": "^0.0.6",                                            "hexo-deployer-git": "^2.1.0",                                                "hexo-generator-archive": "^1.0.0",                                           "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^1.0.0",                                          "hexo-generator-feed": "^3.0.0",                                              "hexo-generator-index": "^2.0.0",                                             "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.3.2",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-git-backup": "^0.1.3",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-translate-title": "^1.0.11",
    "hexo-wordcount": "^6.0.1",
    "live2d-widget-model-shizuku": "^1.0.5"
  }
}`
我不确定是我插件冲突还是其他的，我的根目录配置改为默认主题live2d是可以用的，求解下。

**Comment by greenhandzdl** [comment]
还有就是阅览人数还是0...

**Comment by greenhandzdl** [comment]
还有friends根据安装包修改然后g出来的:
https://github.com/greenhandzdl/greenhandzdl.github.io/blob/master/friends/index.html

**Comment by greenhandzdl** [comment]
> 还有friends根据安装包修改然后g出来的:
> https://github.com/greenhandzdl/greenhandzdl.github.io/blob/master/friends/index.html

渲染出来了，就是没有显示，感觉很迷惑

**Comment by Candinya** [comment]
1. live2d插件相关的我再排查一下，可能是插件注入方式不兼容导致的
2. 阅览人数这里我看好像是那个用于统计的代码404了？感觉像是valine那边的问题吧
![image](https://user-images.githubusercontent.com/20502130/96336733-89622380-10b4-11eb-9e3f-a39fe73b1cc3.png)
3. 我发现您播放器使用了我的后端，但是域名不在我的白名单内，导致之前无法使用，现在已经帮您加入白名单，播放器应该可以加载了。但是请注意，由于网易云现在给出了网页版API对于歌曲获取的限制，所以目前您的歌单只能显示10首歌曲。当前基于Meting的API已经被抛弃了，之后应该会改用基于其他的API进行进一步的开发操作。
4. 以及您友链部分的代码请问是下载了原始文件之后直接复制编辑对应代码的吗，这边显示您复制的内容出现了比较严重的问题导致无法生成，请问您是不是复制了网页上的代码导致相关的编码内容没有转换成正确的格式呢。
![image](https://user-images.githubusercontent.com/20502130/96336920-78fe7880-10b5-11eb-8ed3-b88ab1beb9cf.png)

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-17-20-28-33-94](https://user-images.githubusercontent.com/61241103/96337146-5ff6c700-10b7-11eb-80a4-482f8dc47317.png)
friends页面这样写的

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-17-20-29-58-79](https://user-images.githubusercontent.com/61241103/96337173-90d6fc00-10b7-11eb-988e-b57ebe0f2810.png)

**Comment by Candinya** [comment]
1. 本地测试发现live2d模型应该是能加载的，不知道是什么问题导致的。
![image](https://user-images.githubusercontent.com/20502130/96337059-954ee500-10b6-11eb-8ddd-2c49047a2911.png)
2. GitHub的编辑器将这段代码直接视作文本来转义、呈现了，所以出现了大量的报错，正常情况下script内的内容是不会被渲染运行出来的。您可能需要使用本地文本编辑器直接对该MarkDown文件进行编辑。

**Comment by greenhandzdl** [comment]
> 1. 本地测试发现live2d模型应该是能加载的，不知道是什么问题导致的。
>    ![image](https://user-images.githubusercontent.com/20502130/96337059-954ee500-10b6-11eb-8ddd-2c49047a2911.png)
> 2. GitHub的编辑器将这段代码直接视作文本来转义、呈现了，所以出现了大量的报错，正常情况下script内的内容是不会被渲染出来的。您可能需要使用本地文本编辑器直接对该MarkDown文件进行编辑。

emm，本地编辑器vim？编辑friends.md？但我就是vim编辑的啊

还有就是本地。。。我本地好像也加载不出来
![1602939077161374513228](https://user-images.githubusercontent.com/61241103/96337531-866a3180-10ba-11eb-94f1-3f16b7d32c1f.jpg)
我不确定是什么导致的，但我保证我控制文件写法是绝对没问题的，因为我是直接cp官方readme修改的

**Comment by Candinya** [comment]
发现您的friends部分不知道是哪里的问题（可能是未知的插件冲突，您也许需要检查一下是不是什么插件将本该作为代码部分执行的内容尝试渲染成了代码内容），原本的MarkDown文件确实是正确的（GitHub编辑器是我口误），应该是渲染成html文件的过程中可能出现了比较意外的情况。
live2d那边也是，我看您那边渲染出来的引用路径不知为何成了相对引用了，不知道是否是什么插件的冲突，或是没有将设置项转移到相关的设置文件中等。
这些bug目前无法在本地复现，所以目前没法有效debug。但是相关的冲突我们会继续排查，争取能尽快解决不兼容导致的问题。

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-17-23-12-32](https://user-images.githubusercontent.com/61241103/96346451-81af7880-10ce-11eb-9770-42e64f7ff56e.png)
大概就是这个原因吧，但是为什么他会在后面加这些东西，emmm，我都不知道到底发生了什么。

**Comment by greenhandzdl** [comment]
emmm，其实加不加都无所谓，我能访问到他引入的文件，但为什么他不能渲染呢？

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/96364972-22a24000-1170-11eb-80ba-81a9c354058a.png)
![image](https://user-images.githubusercontent.com/20502130/96365145-18cd0c80-1171-11eb-9932-6fdcc783c8e9.png)
您的live2d插件是否出现了设置问题（导致引用的路径错误），您可以检查一下您的model/use段是否有设置正确。**例如`shizuku`的最后一个u忘记写了？**
![image](https://user-images.githubusercontent.com/20502130/96365108-d6a3cb00-1170-11eb-98a0-48ce2a199387.png)
正确设置后的jsonPath应当是一段绝对路径，而不是您站点渲染出来的那种相对路径。
![image](https://user-images.githubusercontent.com/20502130/96365130-ff2bc500-1170-11eb-8db7-bed9ec0d5e2e.png)

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-18-20-28-02](https://user-images.githubusercontent.com/61241103/96367450-7c126b00-1180-11eb-9a98-652fa4de524a.png)
嗯，效果出来了，但是emm的是挡住旁边东西了，emm，左边放不行，右边放也不行，头疼

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/96367604-723d3780-1181-11eb-8cfd-b7b59066b725.png)
![image](https://user-images.githubusercontent.com/20502130/96367651-b29cb580-1181-11eb-99df-86a5d8bd99a0.png)

您应该可以通过调整插件的位置来实现不遮挡的效果，这个是官方提供的功能，相信您如果有**仔细阅读过文档**的话应该是能明白的。

**Comment by greenhandzdl** [comment]
感谢，目前只有谷歌的那个鬼畜建议需要优化了

**Comment by greenhandzdl** [comment]
字体大小链接分享: https://search.google.com/search-console/mobile-usability/drilldown?resource_id=https%3A%2F%2Fgreenhandzdl.github.io%2F&item_key=CAw&sharing_key=jSd_SGFPdAVSm9o1XVVcMQ
这个是可点击元素: 
https://search.google.com/search-console/mobile-usability/drilldown?resource_id=https%3A%2F%2Fgreenhandzdl.github.io%2F&item_key=CAs&sharing_key=KVryZFot_VZ7dlTsPfDHug
还有内容宽度的: 
https://search.google.com/search-console/mobile-usability/drilldown?resource_id=https%3A%2F%2Fgreenhandzdl.github.io%2F&item_key=CAk&sharing_key=vQXF0q7ocvmow0w50Xkmaw
第n次检测还是过不了，希望对优化有所帮助。

**Comment by Candinya** [comment]
尝试调整了几个细节样式，希望能有所帮助

**Comment by greenhandzdl** [comment]
emmm谷歌还是不行，不得不说，dplayer是个很好的视频插入方式(｢･ω･)｢嘿

**Comment by greenhandzdl** [comment]
话说能不能干脆在主题配一个压缩，emmm，不然每次访问都要发送那么多包，感觉体验感不怎么行。

**Comment by greenhandzdl** [comment]
还有就是运行时间在怎么设置去了，emm，翻了一下文档看了，我自己设置了，然后我自己又忘记怎么设了

**Comment by Candinya** [comment]
css之类的会在之后使用stylus重写的时候整合，js因为涉及到多个模块目前没有想到整合的方案（
运行时间设置在主题设置的`jsconfig`->`main`->`createTime`段

**Comment by greenhandzdl** [comment]
![-9979d0ecbb535ad](https://user-images.githubusercontent.com/61241103/97083159-e9227680-1640-11eb-83ec-7c5750793e84.jpg)
![64ced09fdc569150](https://user-images.githubusercontent.com/61241103/97083171-f7709280-1640-11eb-8aa7-5afbaa96684b.jpg)
感觉比前面那个主题做的还是。。。

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/97083245-44ecff80-1641-11eb-8eaa-1b8e68021947.png)
![image](https://user-images.githubusercontent.com/20502130/97083295-8aa9c800-1641-11eb-9640-141d1d71d102.png)

我这边显示的情况似乎没有那么糟糕，能麻烦您帮忙检查一下具体阻塞渲染进程的内容吗，我觉得也许并不应该是主题导致的问题（因为能做的优化基本都做了，lazyload之后也会尝试加入）

**Comment by greenhandzdl** [comment]
emmm,说实话排查我不怎么擅长，sources仓库邀请给您了，希望能帮忙排查一下。

**Comment by Candinya** [comment]
好的，我已接受邀请。
结合PageSpeed Insight对站点的评估，发现主要的原因可能如下：
1. CDN的问题。我的站点使用了CloudFlare的CDN，能提升很多资源相对Google伺服器的加载速度，但是这么做需要一个域名。
2. 图片没有lazyload导致阻塞交互的加载。我之后会继续查询Hexo的文档，尝试使用自定义的生成器处理图片生成的问题。
3. Live2D插件加载时对于主线程的阻塞。不知相关的插件是否会有提供独特的优化方案。
4. 部分CSS的优化问题。之后会重写相关部分。
5. 部分外链图片伺服器与Google的连接情况不佳导致的。面向的主要用户群体为国内用户时可以忽略这个问题。

**Comment by greenhandzdl** [comment]
emmm，我使用了npx压缩，但是所有的文章全都消失了，只留下了404，emmm

**Comment by Candinya** [comment]
1. npx不是压缩，npx的意思是调用可执行文件，gulp才是用来压缩的核心
2. 主题附带的这个gulp压缩脚本仅仅是用于处理主题文件的，如果您是从其他地方寻找到的站点压缩脚本那么请考虑相关的内容兼容性及注意事项

**Comment by greenhandzdl** [comment]
但我仅仅处理主题，emmm，其他的并没有用

**Comment by Candinya** [comment]
您是在主题文件夹下调用该命令的吗，有没有报错，有没有其他的输出内容，运行结束后有没有手动停止监听进程
主题默认就已经压缩完成了，这个仅仅是在修改了相关文件（如CSS文件、JS文件等）之后才需要重新压缩的，一般使用情况下无需重新处理

**Comment by greenhandzdl** [comment]
...我发现好像我的文章全部渲染成了.html
![Screenshot_2020-10-25-14-11-09](https://user-images.githubusercontent.com/61241103/97100229-3dbf0380-16cc-11eb-94ca-a166dabccda3.png)

**Comment by greenhandzdl** [comment]
还有npx执行时任在install
![Uploading Screenshot_2020-10-25-14-14-38.png…]()

**Comment by Candinya** [comment]
本主题提供的开发脚本都是不会影响到您文章内容的，主题本身更没有权限修改您的站点渲染文件，因而任何与主题不相关的操作我也不知道为什么，您应当去询问相关教程的编写人员或是相关工具的开发者。

**Comment by greenhandzdl** [comment]
![Screenshot_2020-10-25-14-30-52](https://user-images.githubusercontent.com/61241103/97100472-d2c2fc00-16ce-11eb-9451-09f991e6137d.png)
所以都是正常现象吗？

**Comment by Candinya** [comment]
我想我的文档没有使用火星文书写吧？
![image](https://user-images.githubusercontent.com/20502130/97100528-3c430a80-16cf-11eb-9990-d34d240bf5e5.png)
就明明白白两条指令
1. `npm install`
2. `npx gulp`

第一条指令用于使用npm安装主题压缩需要的gulp组件
第二条指令用于调用gulp进行压缩
为什么要和gulpfile过不去呢

**Comment by greenhandzdl** [comment]
比如这几个，emmm

**Comment by greenhandzdl** [comment]
我用了
cnpm i
npx gulp
然后再次运行时提醒我下载

**Comment by greenhandzdl** [comment]
咳咳，正常了，发现后面好像多复制了一点点，难怪我执行完
```
cnpm i
```
执行那个的时候还要我下载，原来如此

**Comment by greenhandzdl** [comment]
我想在下面接一言api，话说直接插该在主题文件哪里写？

**Comment by Candinya** [comment]
站点标题在`/layout/_partial/header.ejs`文件中
 - 桌面端的主副标题分别在第38、39行
 - 移动端的在第8行

侧边栏小挂件的个人说明在`/layout/_widget/about.ejs`文件中
 - 文字部分在第13行

页脚部分在`/layout/_partial/footer.ejs`文件中
