### ISSUE TITLE
Valine文章阅读量统计没有生效

### ISSUE THREAD

**Issue by sineatos** [Candinya/Kratos-Rebirth#29]
Hello~

我在配置文件中设置`valine.visitor=true`，设置好了`app_id`和`app_key`。按照网上的例子在LeanCloud上创建了一个名为Counter的Class，但是每次刷新文章页面，文章的阅读次数一只都是0，我开启了评论功能，评论功能生效了，说明LeanCloud应该是能正常使用的，请问要使阅读量统计生效还要做什么配置吗？

**Comment by Candinya** [comment]
是我没看仔细文档，当时光顾着加入相关的结构，忘记了指定id段导致无法统计，抱歉啦，马上就修复

**Comment by Candinya** [comment]
应该是已经修复了，可以尝试着更新一下最新的代码（暂未发布，建议使用git pull的方式进行获取）

**Comment by sineatos** [comment]
> 应该是已经修复了，可以尝试着更新一下最新的代码（暂未发布，建议使用git pull的方式进行获取）

好像还是不行，我pull了当前的master分支下来替换，刷新页面以后阅读量统计那里原本显式 “0次” ，现在连“0”也没有了，console输出如下图，是我少了什么配置吗？

<img width="460" alt="bug1" src="https://user-images.githubusercontent.com/9444250/98437489-75429c80-211d-11eb-8f8a-59572c640dd8.png">

**Comment by Candinya** [comment]
jQuery报错了，不知道是不是刚刚加入的lazyload代码中存在细节错误导致的问题，能否麻烦您提供报错右侧的错误地址，以排查具体的文件和位置呢？非常感谢您的帮助

**Comment by Candinya** [comment]
以及有一个新的选项（enableQQ），那个也是valine的功能（刚才发现的接口），您可能需要在配置文件中补充上这一项，可能就是这里的逗号问题了
![image](https://user-images.githubusercontent.com/20502130/98437561-10d40d00-211e-11eb-8c66-ca56de642829.png)

**Comment by sineatos** [comment]
加上`enableQQ`以后可以正常使用了，评论和访问量统计都生效了。
