### ISSUE TITLE
新功能建议： Mac风格代码块

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#31]
![Screenshot_2020-11-16-22-38-42](https://user-images.githubusercontent.com/61241103/99266225-81d19e00-285d-11eb-80de-1b10a15cab13.png)
我真的认真读了pre文档，但是前面加了pre，把所有风格都用了还是加载不出来，真的不知道发生了什么。

**Comment by greenhandzdl** [comment]
emmm，这是别人的博客，我的还没有实现。

**Comment by Candinya** [comment]
不需要添加pre，仅需使用默认的高亮配置，使用Markdown默认格式的代码块即可实现。
您可参照样例站点中的[代码高亮测试页面](https://kr-demo.candinya.com/posts/code-highlight/)，页面的[原始文件](https://github.com/hexojs/hexo-theme-unit-test/blob/master/source/_posts/code-highlight.md)中直接使用了Markdown语法规定的代码块高亮样式。

**Comment by greenhandzdl** [comment]
所以.md文件是引用吗？emmm，我看的不太明白。

**Comment by greenhandzdl** [comment]
<pre><code>好像是不行的

**Comment by Candinya** [comment]
并不是，而是说请注意块状代码高亮是需要使用整个代码块来实现，而不是单行的代码。
发现您的站点使用了每一行都单独用单个\`包括起来的样式，这样是单行代码的写法；如果需要实现代码块，您可以参照如下的格式，以三个\`将您需要高亮显示的代码块包括起来：

\`\`\` 用于高亮的语言，如bash
这里填写您的内容
\`\`\`

**Comment by greenhandzdl** [comment]
![Screenshot_2020-11-16-23-08-36](https://user-images.githubusercontent.com/61241103/99269077-e3dfd280-2860-11eb-9539-249ee2c62590.png)
这样吗？

**Comment by Candinya** [comment]
那个不是引号，而是就像您行内代码一样的那个英文反引号。单个反引号负责一行的行内代码，三个反引号包括起来的一大部分能成为一个代码块。

**Comment by greenhandzdl** [comment]
![Screenshot_2020-11-16-23-27-12](https://user-images.githubusercontent.com/61241103/99273723-60c07b80-2864-11eb-8b94-dd55a51b55e8.png)
但是mac风格需要自己下吗，emm

**Comment by Candinya** [comment]
不需要，主题默认的就是Mac风格的代码高亮。您是否是把代码高亮样式改炸了，或是未指定需要高亮的语言，或是在站点的高亮设置中配置出现了问题？
此处附上本站站点设置中的高亮配置段：
![image](https://user-images.githubusercontent.com/20502130/99274667-8f8b2180-2865-11eb-9052-21b9b5b6a4e4.png)
``` yaml
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
```
和一个正常高亮显示的代码段：
![image](https://user-images.githubusercontent.com/20502130/99275032-f90b3000-2865-11eb-9692-53d65beb9b5d.png)
![image](https://user-images.githubusercontent.com/20502130/99275111-13dda480-2866-11eb-9b3f-ae5948ad3804.png)

**Comment by greenhandzdl** [comment]
https://greenhandzdl.github.io/how-to-quickly-build-linux-on-mobile-phones.html/#more

emm,这一页突然不正常了

**Comment by Candinya** [comment]
您像是用错Highlight样式的生成格式了。
您可以参考Hexo文档中[代码高亮](https://hexo.io/zh-cn/docs/syntax-highlight)部分。
请注意，本主题使用的是Hexo默认的配置，即后端运行highlight.js，显示行号并且输出整个table块。
![image](https://user-images.githubusercontent.com/20502130/99276283-784d3380-2867-11eb-9743-3951ad51c083.png)
您页面的工作看上去不正常，怀疑是渲染的过程中出现了问题。
![image](https://user-images.githubusercontent.com/20502130/99276347-88fda980-2867-11eb-9150-1b0f5d939792.png)

**Comment by greenhandzdl** [comment]
emm，看看我的bak库，到现在还没有排除问题，但我感觉是插件有问题

**Comment by Candinya** [comment]
您可以考虑另行搭建干净的测试环境用于插件间的错误排查。如果您能定位到与本主题发生冲突的插件，我会去进行相关的研究与兼容性调整。

**Comment by greenhandzdl** [comment]
我还是不知道什么情况，emmm，加载出来就极为的怪异，但是用code却比较正常

**Comment by greenhandzdl** [comment]
![Screenshot_2020-11-17-23-59-57](https://user-images.githubusercontent.com/61241103/99414092-6e900280-2931-11eb-9518-04f165c6b6bb.png)
![Screenshot_2020-11-17-23-49-18](https://user-images.githubusercontent.com/61241103/99414144-7ea7e200-2931-11eb-8f98-9b73dc46f7ce.png)
![Screenshot_2020-11-17-23-59-48](https://user-images.githubusercontent.com/61241103/99414165-82d3ff80-2931-11eb-947e-9819166f3b34.png)
然后配置文件在bak仓库里面
我重新配置了下sh啥的发现还是这样

**Comment by greenhandzdl** [comment]
切换主题（官方自带）
![Screenshot_2020-11-18-21-22-41](https://user-images.githubusercontent.com/61241103/99540325-54fec180-29ea-11eb-9466-0aa07dbfe945.png)
![Screenshot_2020-11-18-21-22-37](https://user-images.githubusercontent.com/61241103/99540346-592adf00-29ea-11eb-8aae-89e61a0abd22.png)
使用hexo-admin在线查看（图略）

渲染问题可能是主题的，emmm，希望能修复

**Comment by Candinya** [comment]
能否麻烦您找到**复现方式**，我本地无法复现的情况下无法定位诱发原因，谢谢。
另外，如果您确定了是主题的问题，而不是您本地配置的问题或其他的插件冲突，麻烦您新开启一个[bug上报](https://github.com/Candinya/Kratos-Rebirth/issues/new?assignees=Candinya&labels=bug&template=bug_report.md)的issue，Mac风格代码块+带行号高亮是本主题已有的功能，按照提供的高亮配置方案（也就是Hexo默认的高亮设置方案）应该即可正常显示，而非「新功能建议」。

**Comment by Candinya** [comment]
如果您指的是因为改动了高亮显示设置，将行号显示等设置内容全部关闭后导致长代码块渲染脱离table格式，进而引发显示溢出的问题，将会在之后的开发工作中进行测试与相关的修复工作。
