### ISSUE TITLE
新功能建议： Valine优化

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#34]
![Screenshot_2020-11-21-19-42-49](https://user-images.githubusercontent.com/61241103/99876522-2bd07200-2c32-11eb-9d6b-606f19ff3d1c.png)
如图，我想要将用户名等等修改为可选项，如果用户名不填则显示我的自定义无名氏用户名。
我还想要头像设置成如上的random，评论显示系统环境及浏览器是什么。

**Comment by Candinya** [comment]
这是Valine的内容，您也许可以参阅[Valine的配置文档](https://valine.js.org/configuration.html)。
本主题的valine评论生成结构在`layout/_comments/valine.ejs`中，您可以根据您的需要进行相关的配置项修改。

**Comment by greenhandzdl** [comment]
如果我想加入新的评论系统呢？也是在layout/_comments/创建新的文件吗？

**Comment by Candinya** [comment]
> 如果我想加入新的评论系统呢？也是在layout/_comments/创建新的文件吗？

是的，并且请记得修改主题设置中的`comments`字段为您新建的文件名（不包含后缀.ejs），系统会自动加载对应的文件。

**Comment by greenhandzdl** [comment]
好吧，去部署那家评论的时候发现教程还没谢全，版本过了一个月还是测试。
