### ISSUE TITLE
Bug 回报：requestIdleCallback API 在 Safari 浏览器上不支持，导致文章底部评论框加载失败

### ISSUE THREAD

**Issue by vensing** [Candinya/Kratos-Rebirth#36]
1. **对Bug的描述:**
`window.requestIdleCallback` 及`window.cancelIdleCallback` API 在 Safari 浏览器上不支持，导致文章底部评论框加载失败

2. **复现Bug的方法:**
在 Safari (iOS/iPadOS/macOS) 浏览器上访问开启评论留言的页面时，因 Safari 浏览器上不支持`window.requestIdleCallback` 及`window.cancelIdleCallback` API，导致评论功能加载失败。

3. **期望的行为:**
能在 Safari 浏览器上正常使用各种评论插件显示评论。

4. **相关的截图:**
![](https://i.loli.net/2020/12/01/nViAPfe8TqQFUbL.png)
![](https://i.loli.net/2020/12/01/4C7sfzITWDKmUvi.jpg)
see: https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestIdleCallback

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
`window.requestIdleCallback` 及`window.cancelIdleCallback` API 在 Safari 浏览器上不支持

6. **补充内容:**
可以用 setTimeout() 重构 `window.requestIdleCallback` 及`window.cancelIdleCallback` API 来解决 Safari 上的兼容问题，我将发起 PR : )
see: https://developer.mozilla.org/zh-CN/docs/Web/API/Background_Tasks_API

**Comment by Candinya** [comment]
好耶！o(*￣▽￣*)ブ
