### ISSUE TITLE
Bug 回报：文章过期提醒功能某些情况下重复添加警告框

### ISSUE THREAD

**Issue by vensing** [Candinya/Kratos-Rebirth#38]
1. **对Bug的描述:**

- 文章过期时间功能某些情况下重复添加警告框
- 在非文章详情页面也会执行 `expireNotify` 函数，这是不必要的

2. **复现Bug的方法:**
1 前往一篇带有文章过期提醒的详情页面；
2 点击导航栏上的任意菜单；
3 点击浏览器  go back 按钮，返回查看之前打开的文章历史记录网页；
4 文章过期提醒框重复添加。
这是 pjax 引起的问题。

3. **期望的行为:**

不会重复添加文章过期提示框；在非文章详情页面不执行 `expireNotify` 函数。

4. **相关的截图:**

![](https://i.loli.net/2021/01/07/2JQwZWdneOPSkNV.png)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

6. **补充内容:**
可以在 post.ejs 中实现文章过期提醒功能，这种实现方式只会在文章 post 详情页面执行过期提醒逻辑 (避免在其他页面执行不必要的函数)，且不会重复添加提示框；刷新页面时提示框不会延迟追加到 DOM  节点上，js 编程的方式刷新页面会闪一下页面延迟追加。

```ejs
<% if (theme.expire.enable) { %>
    <% const diffDays = moment(new Date()).diff(moment(page.updated), 'day');  
        const expireDay = theme.expire.day;
    %>
    <% if (expireDay!=0 && diffDays > expireDay) { %>
        <div class="alert alert-warning" role="alert">
            本文最后编辑于 <%= diffDays %> 天前，其中的内容可能需要更新。
        </div>
    <%  } %>
<%  } %>
```

在 ejs 中实现如上所示，需要在 `_config.yml` 中新增：
```yml
expire:
  enable: true
  day: 30
```

是否可以 PR ~

**Comment by Candinya** [comment]
这样的话过期时间就会锁定成站点最后生成时间而不是用户访问的实时时间了🤔
也许可以修改成预置隐藏的节点，如果需要显示过期信息的话就往里面填充内容&取消隐藏的方案（记得使用.hidden的class应该就可以…？）
我等会去处理一下吧🍬

**Comment by vensing** [comment]
确实是会变成最后生成时间了，而不是再根据当前时间了
