### ISSUE TITLE
Bug 回报：谷歌浏览器分享按钮无反应

### ISSUE THREAD

**Issue by liaochenlanruo** [Candinya/Kratos-Rebirth#39]
1. **对Bug的描述:**
本谷歌浏览器点击分享按钮无反应，微软Edge浏览器可用

**Comment by vensing** [comment]
是否开启了拦截广告的插件呢，如果有的话，请关闭后刷新页面再试试

**Comment by liaochenlanruo** [comment]
> 是否开启了拦截广告的插件呢，如果有的话，请关闭后刷新页面再试试

原来如此，我开了“AdGuard 广告拦截器 3.5.31”，关闭以后就可以了，谢谢！很不错的主题！
