### ISSUE TITLE
Bug 回报：（请简略描述Bug的情况）

### ISSUE THREAD

**Issue by qizhiSong** [Candinya/Kratos-Rebirth#40]
clone了这个主题后， 设置好了菜单，添加文章后，不能正常启用valine的评论功能。
看了一下博主的源码，没有找到问题所在。valine的appkey已经替换成了自己的，请求博主支援拉

**Comment by vensing** [comment]
md 文件中 front matter 有设置 comments: true 吗？设置了才会开启评论的说

**Comment by Candinya** [comment]
comments默认模式下即指定为true，因而只要不是手动设置为false的情况，都是会以true来呈现的，应当不会构成问题。
请问控制台在生成时是否存在报错，并且您的设置项posts段中是否有指定 `comments: valine`（样例文件`_config.yml.example`的第55行） ，还是留空了呢？
![image](https://user-images.githubusercontent.com/20502130/107021445-16a1c300-67df-11eb-8fe5-6fbbe30bfc52.png)

**Comment by Candinya** [comment]
该issue因已超过一周没有后续，暂时进行关闭操作，如有相关跟进信息或是后续疑问，欢迎您随时重新打开。
