### ISSUE TITLE
新功能建议： 在首页为每篇文章添加阅读次数

### ISSUE THREAD

**Issue by liaochenlanruo** [Candinya/Kratos-Rebirth#44]
1. **您的新功能建议是由使用时出现的不便引发的吗？**

否
2. **请描述您所设想的功能或是解决方案**

在首页为每篇文章添加**阅读次数**，可以放在日期和tag之后，阅读全文之前。这样方便在首页查看每篇文章的热度。
3. **补充内容:**

也可以添加**评论次数**，甚至可以把右侧边栏的最新文章改为最热文章排名。

**Comment by Candinya** [comment]
应该已经添加上了，在 [演示站点](https://kr-demo.candinya.com/) 可以看到效果。
不过这个功能（以及评论统计）需要配合 valine / waline 评论系统提供的API来实现，其他的支持暂时没有支持。
如果您有什么其他推荐的平台兼容，欢迎随时跟进。

**Comment by liaochenlanruo** [comment]
多谢大佬，这个功能非常有用
