### ISSUE TITLE
代码高亮主题怎么改

### ISSUE THREAD

**Issue by smilk520** [Candinya/Kratos-Rebirth#45]
我对scss内容还不了解，我看到了src/scss/highlight.scss里面有相关的代码，但是修改后没有效果，虽然修改source/css/highlight.min.css里面的代码可以看效果，但是如何去对应，代码高亮主题的五种选择呢？（normal | night | night eighties | night blue | night bright）

**Comment by Candinya** [comment]
这一块是还有bug，我给改一下吧

**Comment by smilk520** [comment]
我想改成亮色的主题

**Comment by smilk520** [comment]
能发给我一个改好的highlight.min.css吗？

**Comment by Candinya** [comment]
好的，这里是改成light主题的：
[highlight.min.css.zip](https://github.com/Candinya/Kratos-Rebirth/files/6175599/highlight.min.css.zip)

样式大概是这样：
![image](https://user-images.githubusercontent.com/20502130/111870450-cada6000-89bf-11eb-8dfb-296b57301cf8.png)

**Comment by smilk520** [comment]
好的，感谢~~

**Comment by smilk520** [comment]
issues 要关掉吗

**Comment by Candinya** [comment]
先开着吧，这边调整好加入文档了会关掉的

**Comment by smilk520** [comment]
OK

**Comment by smilk520** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nya ***@***.***&gt;; 
发送时间: 2021年3月20日(星期六) 晚上9:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Candinya/Kratos-Rebirth] 代码高亮主题怎么改 (#45)





 
好的，这里是改成light主题的：
 highlight.min.css.zip
 
样式大概是这样：
