### ISSUE TITLE
上传到gitee上，代码主题依然是原来的那个

### ISSUE THREAD

**Issue by smilk520** [Candinya/Kratos-Rebirth#46]
![image](https://user-images.githubusercontent.com/80802024/111873200-27db1380-89ca-11eb-8eba-c833d23f7089.png)
![image](https://user-images.githubusercontent.com/80802024/111873209-375a5c80-89ca-11eb-942f-b4fd84294a33.png)

**Comment by smilk520** [comment]
上面是上传到gitee上，下面是github

**Comment by smilk520** [comment]
用的都说统一hexo写的博客

**Comment by Candinya** [comment]
应该是浏览器缓存问题，可以尝试 Ctrl + F5 强制刷新一下页面，或是打开 https://smilk.gitee.io/css/highlight.min.css 刷新几次更新一下，浏览器缓存，在这里查看是正确的。
![image](https://user-images.githubusercontent.com/20502130/111873315-af288700-89ca-11eb-91f7-270c59257b88.png)

**Comment by smilk520** [comment]
好了，应该就是浏览器缓存的问题。
