### ISSUE TITLE
新功能建议： 流程图渲染支持

### ISSUE THREAD

**Issue by chen-yixin** [Candinya/Kratos-Rebirth#47]
1. **您的新功能建议是由使用时出现的不便引发的吗？**
はい

2. **请描述您所设想的功能或是解决方案**
[hexo-filter-mermaid-diagrams](https://github.com/webappdevelp/hexo-filter-mermaid-diagrams)
[next主题文档](https://theme-next.js.org/docs/tag-plugins/mermaid)

3. **补充内容:**
(与本isuue无关)比较好奇MathJax那块支持后再去除的原因，是冲突还是啥的

**Comment by Candinya** [comment]
并不是去除，是因为修正了插件注入位置之后能使用插件直接来实现了，所以就没有单独再内置重复的功能支持呢
这个插件的支持马上就会去加入哒😃

**Comment by Candinya** [comment]
应该是加上了，pjax那边也调整过了，初步测试看上去似乎是没有问题的
hexo-filter-mermaid-diagrams 这个插件的实现方案是代码块，和next的标签实现方式并不相同。由于提到了这个插件，目前使用的是插件的解决方案。

> \`\`\` mermaid
> graph TD;
>     A-->B;
>     A-->C;
>     B-->D;
>     C-->D;
> \`\`\` 

![image](https://user-images.githubusercontent.com/20502130/111908891-e879f900-8a95-11eb-95c3-7c2327158e5d.png)

**Comment by Candinya** [comment]
暂时没有问题的话，这个 issue 就先关闭了。如果有任何其他需要帮助的情况发生，或是使用上的帮助，欢迎您随时重新开启。

**Comment by chen-yixin** [comment]
更新最新master分支代码并且安装hexo-filter-mermaid-diagrams插件后运行，
图表是正常显示的，但是别的代码块样式渲染有点奇怪
![image](https://user-images.githubusercontent.com/47199142/112717908-8f451600-8f2a-11eb-98f5-75c2c1f830ca.png)

尝试v1.6.1tag+用`hexo g`命令重新生成页面+浏览器清缓存刷新+卸载hexo-filter-mermaid-diagrams插件，还是不行
你那有遇到类似的情况码？

**Comment by Candinya** [comment]
应该是代码高亮没有开
可以参见 #42

**Comment by chen-yixin** [comment]
这个选项一直都开着的
![image](https://user-images.githubusercontent.com/47199142/112718270-ddf3af80-8f2c-11eb-8887-f7b0b44e2055.png)

**Comment by Candinya** [comment]
可能是 29c9c1a 引入的高亮单独设置问题，现在需要在站点配置文件内指定高亮显示的样式了。
![image](https://user-images.githubusercontent.com/20502130/112718427-e4365b80-8f2d-11eb-9473-9d210cd7504d.png)

**Comment by Candinya** [comment]
追加了一个默认高亮样式的修复，可以尝试测试一下。

**Comment by chen-yixin** [comment]
正常渲染了，感谢

![image](https://user-images.githubusercontent.com/47199142/112718644-578c9d00-8f2f-11eb-93b0-388f4b131f59.png)

**Comment by tyokyo320** [comment]
插入mermaid图报错：

```bash
ERROR Render HTML failed: index.html
TypeError: /home/xxx/work/repos/blog/node_modules/hexo-theme-kratos-rebirth/layout/layout.ejs:22
    20| 
    21|         <%- partial('_partial/footer') %>
 >> 22|         <%- partial('_partial/after-footer') %>
    23|     </body>
    24| </html>

/home/xxx/work/repos/blog/node_modules/hexo-theme-kratos-rebirth/layout/_partial/after-footer.ejs:36
    34| <!-- Extra support for third-party plguins  -->
    35| <% if (config.mermaid && config.mermaid.enable || theme.mermaid && theme.mermaid.enable) { %>
 >> 36|     <%- partial('../_plugins/mermaid', { mermaidConfig: config.mermaid || theme.mermaid }) %>
    37| <% } %>
    38| 

/home/xxx/work/repos/blog/node_modules/hexo-theme-kratos-rebirth/layout/_plugins/mermaid.ejs:10
    8|     };
    9|     if (typeof mermaid == 'undefined') {
 >> 10|         const src = '<%- url_npm_cdn(`mermaid", "dist/mermaid.min.js`) %>';
    11|         $.getScript(src, init);
    12|     }
    13|     // Set PJAX callback function

Cannot read properties of undefined (reading 'includes')
```

已经安装

```bash
npm install hexo-filter-mermaid-diagrams
```

主题目录下已经设置

```yaml
# Mermaid tag
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: forest
```

插入的代码

```code
sequenceDiagram
    Client->>Server: SYN=1, ack=0, seq=x
    Server->>Client: SYN=1, ack=1, seq=y, ack=x + 1
    Client->>Server: ACK=1, seq=x + 1, ack=y + 1
```

```mermaid
sequenceDiagram
    Client->>Server: SYN=1, ack=0, seq=x
    Server->>Client: SYN=1, ack=1, seq=y, ack=x + 1
    Client->>Server: ACK=1, seq=x + 1, ack=y + 1
```

同样的配置 next 主题没有报错，mermaid 图正常显示，请问我的配置出现了问题吗？
