### ISSUE TITLE
脚页部分是否可以修改呢？如何修改？

### ISSUE THREAD

**Issue by smilk520** [Candinya/Kratos-Rebirth#48]
我看到了footer.ejs和kratosr.min.css里面有涉及到脚页的内容，但是还是不知道如何下手去修改。例如如何将脚页的高度修改的小一点，以及如何改成白色背景？
![image](https://user-images.githubusercontent.com/80802024/111893866-dd48ae00-8a40-11eb-9315-cbf352402020.png)

**Comment by smilk520** [comment]
就是感觉脚页高度太高了，尤其是用手机预览，感觉占了手机屏幕的4分之一

**Comment by smilk520** [comment]
还有就是最好能让他呈现白色的背景，例如github这样的
![image](https://user-images.githubusercontent.com/80802024/111893916-6233c780-8a41-11eb-8e06-83665f6c049b.png)

**Comment by Candinya** [comment]
https://github.com/Candinya/Kratos-Rebirth/blob/74546059fa4b3b914e37875a8639df0eae4cdfb9/src/scss/kratosr.scss#L2210-L2262

这一块是样式，改完了可以使用 gulp 重新打包

可以参见 [🍩 二次开发相关](https://github.com/Candinya/Kratos-Rebirth#-%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E7%9B%B8%E5%85%B3)

**Comment by smilk520** [comment]
关于最后页脚，我想标注主题作者的来源，可是总感觉语法上不通，Theme Kratos:Rebirth Site built with  by smilk
![image](https://user-images.githubusercontent.com/80802024/111894032-54cb0d00-8a42-11eb-97e4-e05ae42812cd.png)

**Comment by smilk520** [comment]
这是默认的效果

**Comment by smilk520** [comment]
是不是你当时制作时，疏忽了，还是这句话本身语法是正确的呢？

**Comment by Candinya** [comment]
这是两段，因为不知道怎么设置自动显示分隔线，所以看上去像是一段了，我去设置一下 margin 吧
原来的是这样的，后来想了想都留了主题地址了，就把站点的位置留给站长吧
https://github.com/Candinya/Kratos-Rebirth/blob/657760582933c02512ea45836e1b95a1e6fb20b0/layout/_partial/footer.ejs#L54-L57

**Comment by smilk520** [comment]
嗯嗯，那我就自行修改了，当然我会会留下主题的地址的
