### ISSUE TITLE
在命令行执行 npx gulp 出现错误

### ISSUE THREAD

**Issue by smilk520** [Candinya/Kratos-Rebirth#49]
![image](https://user-images.githubusercontent.com/80802024/111936156-1431c900-8b00-11eb-97ef-d6f02db32566.png)

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/111937352-81def480-8b02-11eb-8adb-3d025cc920b9.png)
可以试着升级一下最新的主题版本，这边现在已经改成渲染全部高亮主题+手动在 config.yml 中配置高亮的方案了
https://github.com/Candinya/Kratos-Rebirth/blob/1dec899cfa5d0e17617cf6183a069c8113834b9d/_config.yml.example#L7

**Comment by smilk520** [comment]
ok
