### ISSUE TITLE
左下角播放器如何修改

### ISSUE THREAD

**Issue by smilk520** [Candinya/Kratos-Rebirth#50]
如何关掉歌词显示，可以换左下角播放器的样式吗？手机版搜索会挡住播放器歌曲列表的按钮，这样的化无法自选选歌
![QQ图片20210322115455](https://user-images.githubusercontent.com/80802024/111938672-780ac080-8b05-11eb-8f1d-4a23c52a904f.png)

**Comment by Candinya** [comment]
https://github.com/Candinya/Kratos-Rebirth/blob/1dec899cfa5d0e17617cf6183a069c8113834b9d/layout/_tools/player.ejs#L1-L31

这里是播放器的配置文件，可以参考 [APlayer 文档](https://aplayer.js.org/#/zh-Hans/) ，如果使用的是 MetingJS 加载方式的话可以参照 [MetingJS](https://github.com/metowolf/MetingJS) 进行调整

**Comment by smilk520** [comment]
好的，谢谢
