### ISSUE TITLE
Bug 回报：主题配置 → 文章页面：【sticky】对应的数字权重与使用指南不一致

### ISSUE THREAD

**Issue by SuiteLHY** [Candinya/Kratos-Rebirth#53]
1. **对Bug的描述:**
使用手册中的[主题配置 → 文章页面：【sticky】对应的数字权重]与所描述的“数字越大优先级越高”不一致，实际效果为[数字越大优先级越低]。

![image](https://user-images.githubusercontent.com/20529292/114259583-84e24c00-9a01-11eb-88d8-5546a67c58cc.png)

2. **复现Bug的方法:**
![image](https://user-images.githubusercontent.com/20529292/114259447-8eb77f80-9a00-11eb-97a2-e3b53a2026ba.png)
![image](https://user-images.githubusercontent.com/20529292/114259482-c8888600-9a00-11eb-8be9-185f5b4ce192.png)
![image](https://user-images.githubusercontent.com/20529292/114259557-59f7f800-9a01-11eb-88b0-0d4f954fa3e2.png)

3. **期望的行为:**
方案一. 修正[使用手册](https://candinya.com/posts/Kratos-Rebirth-Manual/#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE)的对应配置项说明。
方案二. 修改代码使配置项【sticky】实现的功能与[使用手册](https://candinya.com/posts/Kratos-Rebirth-Manual/#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE)的描述一致。

4. **相关的截图:**
![image](https://user-images.githubusercontent.com/20529292/114259335-b3f7be00-99ff-11eb-927e-169933afe0a1.png)

5. **对应版本**
![image](https://user-images.githubusercontent.com/20529292/114259701-6761b200-9a02-11eb-9c2b-a11953ac0808.png)

6. **补充说明**
影响不大，小问题。~~有空就改，没空就摸鱼~~

**Comment by Candinya** [comment]
这个是 JavaScript 为弱类型的问题，"2147483647-1"会被当成一个字符串而非数学表达式来参与运算，进而计算出的结果为 `NaN` ，因而导致排序出错。如果换成"2147483646"，那么序列的顺序就是正确的。
可以参考默认主页生成器的代码。

https://github.com/hexojs/hexo-generator-index/blob/1a637a04ea809d127a771810c30fbb18e08ca388/lib/generator.js#L9

![image](https://user-images.githubusercontent.com/20502130/114261911-93376480-9a0f-11eb-9e7a-8fa2e735c0f5.png)

**Comment by SuiteLHY** [comment]
> 这个是 JavaScript 为弱类型的问题，"2147483647-1"会被当成一个字符串而非数学表达式来参与运算，进而计算出的结果为 `NaN` ，因而导致排序出错。如果换成"2147483646"，那么序列的顺序就是正确的。
> 可以参考默认主页生成器的代码。
> 
> https://github.com/hexojs/hexo-generator-index/blob/1a637a04ea809d127a771810c30fbb18e08ca388/lib/generator.js#L9
> 
> ![image](https://user-images.githubusercontent.com/20502130/114261911-93376480-9a0f-11eb-9e7a-8fa2e735c0f5.png)

经过完整的测试，发现我最初的描述不准确，我的问题描述应该修正为👉使用手册中的[主题配置 → 文章页面：【sticky】对应的数字权重]与所描述的“数字越大优先级越高”不一致，实际效果为[创建时间越晚优先级越高]。

** 补充说明

* 问题复现截图

![image](https://user-images.githubusercontent.com/20529292/114263569-e82ba880-9a18-11eb-9427-09eb9c78c2bd.png)

编辑了创建时间为【2021-04-10 16:05:24】的数据后（排除了编辑时间的因素；确定了\[在置顶文章之中\]排序权重只与创建时间有关）

![image](https://user-images.githubusercontent.com/20529292/114263992-efec4c80-9a1a-11eb-871f-a7df85bd6de3.png)

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/114265738-1616ea00-9a25-11eb-804d-13ec1947ca3b.png)
这里无法复现。请注意这并不是一个主题特性，而是根据官方的首页文章排布方案做出的兼容与配合举措。请检查您的 `hexo-generator-index` 版本（在站点的package.json文件中），只有`2.0.0`开始的版本（目前只有2.0.0）才加入了 sticky 参数。
具体可以参见 [hexo-generator-index 的 版本发布页面](https://github.com/hexojs/hexo-generator-index/releases)

**Comment by SuiteLHY** [comment]
> ![image](https://user-images.githubusercontent.com/20502130/114265738-1616ea00-9a25-11eb-804d-13ec1947ca3b.png)
> 这里无法复现。请注意这并不是一个主题特性，而是根据官方的首页文章排布方案做出的兼容与配合举措。请检查您的 `hexo-generator-index` 版本（在站点的package.json文件中），只有`2.0.0`开始的版本（目前只有2.0.0）才加入了 sticky 参数。
> 具体可以参见 [hexo-generator-index 的 版本发布页面](https://github.com/hexojs/hexo-generator-index/releases)

我发现了，一开始我没有描述清楚，是在【分类】和【标签】列表下才出现的问题，主页列表没有问题（有问题的是某一条异常数据，和此 issue 无关）。很抱歉，麻烦你有空再看看orz

**Comment by Candinya** [comment]
是 hexo-generator-tag 和 hexo-generator-category 的问题，我提了两个issue用于跟进。
hexojs/hexo-generator-tag#46
hexojs/hexo-generator-category#44

**Comment by SuiteLHY** [comment]
非常感谢！👍❤
