### ISSUE TITLE
新功能建议： 折叠插件能否快捷地实现 [默认全部展开] 的功能

### ISSUE THREAD

**Issue by SuiteLHY** [Candinya/Kratos-Rebirth#54]
1. **您的新功能建议是由使用时出现的不便引发的吗？**
关于折叠插件，未能在使用指南中找到 \[快捷实现 \[默认全部展开\] 的功能\]，且根据[查阅到的资料](https://www.google.com/search?q=collapse+%E9%BB%98%E8%AE%A4%E5%85%A8%E9%83%A8%E5%B1%95%E5%BC%80&oq=collapse+%E9%BB%98%E8%AE%A4%E5%85%A8%E9%83%A8%E5%B1%95%E5%BC%80&aqs=chrome..69i57j0i5i30l2j69i61.13985j0j15&sourceid=chrome&ie=UTF-8)实现较为困难，需要插件封装并实现 \[对应功能的配置项\]。

2. **请描述您所设想的功能或是解决方案**
* 【没有实现描述功能的情况】

方案一. 简单地实现所描述的功能，并在[文档的相应章节更新最新的示例代码](https://candinya.com/posts/Kratos-Rebirth-Manual/#%E6%8A%98%E5%8F%A0%E5%86%85%E5%AE%B9)。

* 【实现了描述的功能，文档未明确的情况】

方案一. 完善[文档的示例代码](https://candinya.com/posts/Kratos-Rebirth-Manual/#%E6%8A%98%E5%8F%A0%E5%86%85%E5%AE%B9)。

3. **补充内容:**
* [使用指南](https://candinya.com/posts/Kratos-Rebirth-Manual/)截图

![image](https://user-images.githubusercontent.com/20529292/114262673-d5fb3b80-9a13-11eb-8e78-881472ad3a78.png)

* 功能实现效果（说明）

![image](https://user-images.githubusercontent.com/20529292/114263012-9c2b3480-9a15-11eb-9f6f-0d89acdcc9ef.png)

**Comment by Candinya** [comment]
已经实装，可以在折叠框标题后加入` open` 参数来默认开启。（请记得使用空格分隔）

**Comment by SuiteLHY** [comment]
> 已经实装，可以在折叠框标题后加入` open` 参数来默认开启。（请记得使用空格分隔）

已更新确认无误，感谢大大🍭！
