### ISSUE TITLE
功能建议：顶部目录栏下滑阅读时能向上隐藏

### ISSUE THREAD

**Issue by crorylove** [Candinya/Kratos-Rebirth#55]
！、功能描述
- 下滑阅读时顶部横栏向上隐藏
![K1QP(V@4NZ(@H4G$FXZM29G](https://user-images.githubusercontent.com/74654422/114707624-06690f80-9d5d-11eb-9c86-d8040c457edf.png)

**Comment by Candinya** [comment]
已经添加上了（并且修了一些bug），可以试一试。
有什么问题欢迎随时联系哦。

**Comment by crorylove** [comment]
好的，好快啊。感觉很不错。目前没有其他需求啦，
先用段时间在回来。
