### ISSUE TITLE
Bug 回报：config微博设置，访问用户名找不到

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#60]
1. **对Bug的描述:**
config中微博设置问题

2. **复现Bug的方法:**
- [ ] 填入自己的用户名
- [ ] 找不到该页面（404 not found）

3. **期望的行为:**
应该不是
`https://weibo.com/u/real_greenhandzdl`
`https://m.weibo.cn/u/real_greenhandzdl?&jumpfrom=weibocom`
而是
`https://m.weibo.cn/u/6570808175?uid=6570808175&t=0&luicode=10000011&lfid=100103type%3D1%26q%3Dreal_greenhandzdl`

**Comment by Candinya** [comment]
您可以在那里配置成 `6570808175` ，就能直接变成 `https://weibo.com/u/6570808175` 这样的链接了。
