### ISSUE TITLE
文章随机图标自定义配置

### ISSUE THREAD

**Issue by SuiteLHY** [Candinya/Kratos-Rebirth#61]
1. **您的新功能建议是由使用时出现的不便引发的吗？**
想要给站点博文&thinsp;拓展&thinsp;自定义的随机图标，结果发现&thinsp;随机图标有数量限制（<u>最多20张图片</u>）.
~~我想要放上100张美图~~

2. **请描述您所设想的功能或是解决方案**
    * （如果未提供相应的拓展功能和公开配置项）方案一. 提供类似于
        ```
        ## 随机头图的数量
        thumbnail:
            random_amount: 19
        ```
        上述代码的配置方案.
    * （如果已实现拓展功能, 但是未公开或者在文档中说明配置项）麻烦完善一下项目文档，谢谢啦🍭~

3. **补充内容:**
    * 类似功能实现: [为Hexo博客添加随机文章头图 · 语雀](https://www.yuque.com/itypen/blog/qydx1c#eb92090f)

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/116981669-6dde0380-acfa-11eb-89f0-f42305b3d948.png)
在 JavaScript 配置段新加了一些可选配置，也许可以试一试 😃

**Comment by SuiteLHY** [comment]
> ![image](https://user-images.githubusercontent.com/20502130/116981669-6dde0380-acfa-11eb-89f0-f42305b3d948.png)
> 在 JavaScript 配置段新加了一些可选配置，也许可以试一试 😃

已经在线确认解决，辛苦大大了！🍭
