### ISSUE TITLE
请告诉我怎么安装

### ISSUE THREAD

**Issue by losand** [Candinya/Kratos-Rebirth#62]
我没有在文档里看到主题
theme文件
`git clonehttps://github.com/Candinya/Kratos-Rebirth/ theme` 类似这段的代码
请问要怎么安装这个主题呢

**Comment by Candinya** [comment]
安装流程：
1. `hexo init your-awesome-blog` 初始化您的 Hexo 博客文件夹（已经完成则可以忽略）
2. 使用 `git clone https://github.com/Candinya/Kratos-Rebirth/ themes/kratos-rebirth` 将主题安装到站点文件夹下的 theme 主题目录中
3. 修改站点文件夹下的 `_config.yml` 站点配置文件，将 `theme: landscape` 修改成 `theme: kratos-rebirth`
4. 进入主题文件夹，手动复制一份 `_config.yml.example` ，并改名为 `_config.yml` 。您可以在这里进行主题设置的修改。
    补注：由于 #56 的问题，暂时不能支持将主题配置文件拷贝到站点根目录下的使用方式，还请您谅解。
