### ISSUE TITLE
分享的二维码生成错误

### ISSUE THREAD

**Issue by N1ULL** [Candinya/Kratos-Rebirth#63]
生成的网址是http://example.com/2021/05/18/%E7%AC%AC%E4%B8%80%E7%AF%87%E5%8D%9A%E5%AE%A2/
前面主站网址怎么改正成自己的网址

**Comment by Candinya** [comment]
建议使用 [Bug上报] 模板
附带上您的站点和主题配置文件（请隐去关键内容），怀疑是您站点配置里的域名没有设置正确
描述不清的问题我无法解决
