### ISSUE TITLE
侧边栏内容居中问题

### ISSUE THREAD

**Issue by Antastsy7** [Candinya/Kratos-Rebirth#68]
你好~非常喜欢你的主题&感谢你的无私分享！！
有个小问题，我将siderbar设置为none，但是内容并没有居中，请问有什么办法可以解决这个问题吗0.0

**Comment by Candinya** [comment]
这个应该是 bug ，我来看一看w

**Comment by Candinya** [comment]
试着设置为 `false` 呢？我用的判断比较简陋，`none`可能是被识别为一种样式啦w

**Comment by Candinya** [comment]
应该修复完成啦，可以拉取最新的代码试一试哦

**Comment by Antastsy7** [comment]
天啦噜这么快Σ(っ °Д °;)っ
试过了现在没问题啦~真的超级感谢！！！
