### ISSUE TITLE
侧边栏取消后的居中问题

### ISSUE THREAD

**Issue by Antastsy7** [Candinya/Kratos-Rebirth#69]
你好~有关之前侧边栏取消之后，我想把post_type设为true然后他的图片似乎还是原来的排版，感觉上是侧边栏的隐藏问题？
![image](https://user-images.githubusercontent.com/22287325/122634209-773af800-d10f-11eb-97d6-004ea52b0cfb.png)

**Comment by Candinya** [comment]
发现是样式设置时候遗留的历史样式问题，现在应该已经修复啦，可以试着拉取一下最新的代码哦w

**Comment by Antastsy7** [comment]
嗯嗯没问题啦！辛苦了😂
（git不会用于是只能手动merge）

**Comment by Candinya** [comment]
可以试试 Github Desktop 哦（大雾x

**Comment by Antastsy7** [comment]
hhhtheme下的git好像管理有点问题🤪（也可能就是菜）

**Comment by Candinya** [comment]
> hhhtheme下的git好像管理有点问题🤪（也可能就是菜）

其实嵌套 git 确实有怪问题，我这边是不知道怎么就调整好啦（超级小声ww

**Comment by Antastsy7** [comment]
> 其实嵌套 git 确实有怪问题，我这边是不知道怎么就调整好啦（超级小声ww
遇事不决重新clone🤣
