### ISSUE TITLE
手机端的浏览问题ˋ( ° ▽、° ) 

### ISSUE THREAD

**Issue by Antastsy7** [Candinya/Kratos-Rebirth#70]
侧边栏隐藏的时候，手机端会给右侧留下空栏左右滑动😂但是手机横过来就没问题
抱歉再三叨扰(o-ωｑ)).oO  真的辛苦了

**Comment by Candinya** [comment]
发现 bug 是好事哒，完全没有打扰哦ww
这边似乎没能复现问题呢，能否麻烦帮忙提供一下使用的浏览器型号、样例的问题站点和主题配置文件（记得隐去隐私内容），如果可以的话可以试着使用截图来辅助说明呢？非常感谢您的帮助哒w

**Comment by Antastsy7** [comment]
我之前是在safari😂然後我刚才改了sidebar又改回来，它似乎又好了orz

**Comment by Candinya** [comment]
看来可能是缓存原因呢
解决了就好哦！不慌不慌哒w
