### ISSUE TITLE
在列表标题超过2行的时候 内容简介过多会导致样式错位

### ISSUE THREAD

**Issue by greenhaha** [Candinya/Kratos-Rebirth#71]
1. **对Bug的描述:**

在列表标题超过2行的时候 内容简介过多会导致样式错位
2. **复现Bug的方法:**

新增文档，将内容标题书写过长 超过2行
此时简介区内容过多的时候会出现样式错位
3. **期望的行为:**
修复建议：
对代码中 kratos-entry-header-new样式名增加新的样式
```
.kratos-entry-header-new{
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```

4. **相关的截图:**

 
![image](https://user-images.githubusercontent.com/42140733/123118651-68d53f00-d475-11eb-8b2f-d97c5f5918a1.png)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

mac os 11.4
chrome 最新版
sfair 14.1.1
任何系统下都会出现这个问题
6. **补充内容:**

无

**Comment by Candinya** [comment]
调整了一下样式，让整个右侧部分区域溢出的部分样式设置为隐藏（因为对于标题而言也许并不算是溢出？），可以试着拉取一下最新的代码检查一下是否正确哦w
