### ISSUE TITLE
Bug 回报：package.json依赖中有较多的模块版本有漏洞

### ISSUE THREAD

**Issue by KirisameMarisas** [Candinya/Kratos-Rebirth#74]
1. **对Bug的描述:**
在主题文件夹中使用npm install 安装相关npm modules 时，npm audit审计报出依赖中有较多漏洞。
2. **复现Bug的方法:**
可以使用如下的方案进行复现:
在最新版本的主题文件夹下使用npm install 报出依赖有漏洞。

3. **期望的行为:**
正常安装安全依赖

4. **相关的截图:**
![image](https://user-images.githubusercontent.com/49802446/124713979-cbc5dc00-df33-11eb-99ab-b50596fb0122.png)
![image](https://user-images.githubusercontent.com/49802446/124715585-c10c4680-df35-11eb-9908-c408b614185f.png)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
操作系统：Win10 wsl2 (Ubuntu 20.04)
浏览器：Chrome 91.0.4472.124
Nodejs：16.4.2
npm：7.19.1
6. **补充内容:**
在使用npm audit fix 之后，依旧存在此问题。
PS: 找到使用ncu自动更新npm module后漏洞数量减少
![image](https://user-images.githubusercontent.com/49802446/124715482-a1751e00-df35-11eb-97e2-02f0930e6906.png)
![image](https://user-images.githubusercontent.com/49802446/124715514-ab971c80-df35-11eb-895b-886b57543aed.png)

**Comment by Candinya** [comment]
已经修复 👌 ❤️
