### ISSUE TITLE
请问一下，想把站点的site_logo设置成圆形的怎么做？

### ISSUE THREAD

**Issue by VictoryNo1** [Candinya/Kratos-Rebirth#75]
就像你的站点那样，该怎么设置呢？谢谢！

**Comment by Candinya** [comment]
使用圆形的图片就好哒
![image](https://user-images.githubusercontent.com/20502130/125195680-4a4eb080-e289-11eb-9b24-79c27dc9be92.png)

**Comment by VictoryNo1** [comment]
好嘞，谢谢你
