### ISSUE TITLE
更新到v1.6.5版本后，在文章页面点击某个目录项会延迟一会才滑动过去

### ISSUE THREAD

**Issue by hhjian666** [Candinya/Kratos-Rebirth#76]
首先感谢作者提供的主题，在万千主题中最钟爱这一款！！！
之前用的是v1.6.3版本，感觉非常流畅，但是更新到v1.6.5版本后，在文章页面点击某个目录项会延迟一会才滑动过去
是不是新版本新添加的呀，体验感略差了耶（呜~

**Comment by Candinya** [comment]
可能是因为修改了标题获取参数导致的，我检查一下吧w
非常感谢提醒哦！

**Comment by Candinya** [comment]
确认了，是 bootstrap 的问题，暂时还是先移除掉啦w

**Comment by hhjian666** [comment]
> 确认了，是 bootstrap 的问题，暂时还是先移除掉啦w

perfect!
