### ISSUE TITLE
markdown图片链接问题

### ISSUE THREAD

**Issue by Ceilzcx** [Candinya/Kratos-Rebirth#78]
大佬，问一下我markdown里面引用的图片应该放在哪个文件夹下，我目前放在source下，创建了一哥images的文件夹用来存放图片，使用相对路径引用，但是hexo g后，图片url有问题

**Comment by Candinya** [comment]
需要使用 `asset_img` 标签，可以参照 Hexo 官方文档中描述的内容： [相对路径引用的标签插件](https://hexo.io/zh-cn/docs/asset-folders#%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84%E5%BC%95%E7%94%A8%E7%9A%84%E6%A0%87%E7%AD%BE%E6%8F%92%E4%BB%B6)

**Comment by Ceilzcx** [comment]
谢谢大佬，已解决
