### ISSUE TITLE
新功能建议： 可以加一下更换图片的接口吗？

### ISSUE THREAD

**Issue by Plato-Ideal** [Candinya/Kratos-Rebirth#79]
**不太懂前端，麻烦大佬告诉一下怎么更换图片可以吗？或者在之后的版本更新中可以加入一下接口，阿里嘎多**

**Comment by Candinya** [comment]
可以参照 **主题设置** 中的 jsconfig - main - pic 段（约第 130 行）的注释调整配置哦， CDN 设置为 false 就能从资源目录中加载自己修改的图片文件啦

**Comment by Plato-Ideal** [comment]
不是，pic段应该是文章的随机图片吧？我想更换的是background&banner top，这个图片的接口在哪里？我用的是阿里云的oss，不想在本地加载图片，太慢了，麻烦大佬再告知一下，谢谢了

**Comment by Candinya** [comment]
已经添加了配置项，可以进行修改啦
有任何问题欢迎随时跟进哦

**Comment by Plato-Ideal** [comment]
吼吼，谢谢大佬，看到了
