### ISSUE TITLE
新功能建议： 鼠标点击特效开关

### ISSUE THREAD

**Issue by Plato-Ideal** [Candinya/Kratos-Rebirth#80]
大佬好，想问一下，鼠标点击特效是不是可以设置一个开关呢？
3. **补充内容:**

另外就是在博客页面的字体颜色问题，太轻了，不清楚，想问一下字体颜色调整的接口在哪里？我想去修改一下，辛苦大佬了

**Comment by Plato-Ideal** [comment]
发现了一个bug，新建categories页面，分类页面空无一物，不知道哪里出了问题

**Comment by Candinya** [comment]
已经添加了一项新的配置项 `click_animate_js` ，可以编辑使用的文件，或是设置为 false 来禁用啦
主题颜色的话您可能需要修改` src/scss/kr-dark.scss` 文件中的颜色配置呢

**Comment by Plato-Ideal** [comment]
thanx，辛苦大佬了，那字体族修改是哪个文件，我刚才修改了颜色但完全没反应啊，是RGB颜色对吧？我设置了#0f0f0f不起作用呢，什么情况

**Comment by Candinya** [comment]
字体是 `kratosr.scss` 文件，这些文件修改之后需要重新构建一遍主题的说呢
可以参照 [🍩 二次开发相关](https://github.com/Candinya/Kratos-Rebirth#-%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E7%9B%B8%E5%85%B3) 的介绍哦

**Comment by Plato-Ideal** [comment]
已经调整好了，谢谢大佬
