### ISSUE TITLE
Bug 回报：分类页面不显示分类内容

### ISSUE THREAD

**Issue by Plato-Ideal** [Candinya/Kratos-Rebirth#81]
1. **对Bug的描述:**

`hexo new page "categories"`之后，index.md也修改完毕，我上传了两篇文章，但分类界面不显示任何类别，不知道什么情况
4. **相关的截图:**

![(0 2`68S85W~I4$3 8DR2(E](https://user-images.githubusercontent.com/71149552/127779650-628c3574-832e-4bc2-bf12-3bb096a21da7.png)
![GN@0VG}0 9R)5W2UYN11J~E](https://user-images.githubusercontent.com/71149552/127779653-72447301-c525-43c0-a9e1-7428b1333ac4.png)

**Comment by vensing** [comment]
你说的分类应该是归档页吧🤔，例如：https://kr-demo.candinya.com/archives/

**Comment by vensing** [comment]
#82  @Candinya

**Comment by Plato-Ideal** [comment]
不是哎，我有做归档页，归档页可以正常显示写过的博客，以时间顺序排列，但分类页面就完全没有

**Comment by Candinya** [comment]
Hexo 默认似乎是没有 分类页面 和 标签页面 的哦
不过主题可以提供一份，具体的样式我再去研究研究吧

**Comment by Plato-Ideal** [comment]
我知道，我是new的，执行命令`hexo new page "categories"`就出现分类页面了，但是应该是接口不对，分类页面不显示，可以给个邮箱吗，我不想发在这里

**Comment by Candinya** [comment]
> 我知道，我是new的，执行命令`hexo new page "categories"`就出现分类页面了，但是应该是接口不对，分类页面不显示，可以给个邮箱吗，我不想发在这里

我觉得可能是我表达有误…

是这样的，这个指令只是新建了一个名为 "categories" 的页面，由于 hexo 本身没有对该页面的特殊支持、目前主题也没有设置支持代码，所以这个页面只是一个普通的页面：如果 Markdown 文件里面没有内容，那么这个页面就是一个空白的页面。它的 "categories" 只能代表它的路径是 "categories" （站点配置中描述的那样），并不代表它就会自动生成 分类页面 该有的内容。

主题这边会在后续的版本中针对 分类页面 和 标签页面 提供特殊支持实现。

**Comment by Plato-Ideal** [comment]
明白，期待大佬赶快更新啊~~~~
