### ISSUE TITLE
新功能建议：友链中不存在的字段

### ISSUE THREAD

**Issue by d-w-x** [Candinya/Kratos-Rebirth#83]
1. **您的新功能建议是由使用时出现的不便引发的吗？**

在说明中提到了以下内容：

> - friends : 友链页面全局字段，删除此字段以禁止自动生成友链页面
>   - href : 友链页面的路径，如friends表示yoursite.ltd/friends/的路径，留空此字段会使用Tag模式
>   - page : 页面相关的参数，您可以配置任意多您需要的页面参数，提供的样例可供您参考
>   - list : 友链列表，您可以参照提供的样例进行对应的复制修改，每一项可以提供显示的名字(name)、简介(bio)、头像链接(avatar)和目标站点链接(link)，无用项建议留空（而不是直接删除）
>   - verify : 是否在每次启动时验证友联的可访问性

但是当 `简介(bio)、头像链接(avatar)` 在配置文件中留空时，简介是 `null`， 头像是指向 `null` 的超链接：

![字段为空的效果图](https://user-images.githubusercontent.com/35656321/127970489-cbf856e5-bfcd-4133-8f98-a4b595892981.png)

2. **请描述您所设想的功能或是解决方案**

希望当简介是空的时候，显示的简介就是**空字符串**；

当头像是空的时候，显示某个**默认头像**（感觉也可以同时允许指定一个远程的默认头像走cdn省流量[穷鬼爆哭]）。

**Comment by Candinya** [comment]
已经部署优化啦，可以试一试哦

**Comment by d-w-x** [comment]
ok啦,感谢~
