### ISSUE TITLE
valine评论系统失效

### ISSUE THREAD

**Issue by fatal-scythe** [Candinya/Kratos-Rebirth#84]
1. **对Bug的描述:**
我将该主题从1.4.7升级到1.6.6版本，按照之前的方法同样对_config.yml进行了配置，包括valine的app_id:和app_key，以及posts:  comments: valine  
hexo g,hexo s了之后原本有评论的区域变成了空白。  
对比了一下/layout/_comments/valine.ejs没发现什么变化...好吧，我不会。  
呜呜，不知道这是不是BUG，还是我太菜...  

2. **相关的截图:**

更新前的示例：  
![pic1](https://user-images.githubusercontent.com/45097791/130202995-85ea618e-5520-4889-8f5f-3cbc4b233f4a.jpg)
更新后的示例：  
![pic2](https://user-images.githubusercontent.com/45097791/130205321-2cdfb350-9fa2-4f03-af72-9afaba8516b2.jpg)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

 操作系统: Windows 10
 浏览器: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3870.400 QQBrowser/10.8.4405.400

**Comment by Candinya** [comment]
怀疑有可能是 NodeJS 的版本导致的呢，之前有几个版本升级的时候使用了一些新的操作符，可能导致不好向下兼容，能否请问您的 NodeJS 版本是什么呢？
另外能否麻烦帮忙检查一下后台和浏览器控制台有没有出现错误提示信息呢，非常感谢！

**Comment by fatal-scythe** [comment]
```
$ hexo -v
INFO  Validating config
hexo: 5.3.0
hexo-cli: 4.2.0
os: Windows_NT 10.0.19042 win32 x64
node: 14.15.4
v8: 8.4.371.19-node.17
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1i
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
```  
在主题1.6.5更新时建议使用node v14以上，我这个是14.15.4应该不是这个问题...  
但浏览器的控制台也确实报错：  
`Uncaught SyntaxError: Unexpected token .`   
感谢您的回复！

**Comment by Candinya** [comment]
浏览器报错的话可能未必是 valine 评论区的错误，因为使用的是 lazyload 方案，可能是由于前面哪个 JS 运行时候出现了错误，导致后续的包括评论加载代码在内的部分都无法正常运行。
如果可以的话，能否就浏览器控制台的报错信息帮忙点击前面的小三角展开，并提供一份完整的截图方便这边定位错误呢？非常感谢！

**Comment by fatal-scythe** [comment]
在控制台只能获取到这样的信息...  
![error](https://user-images.githubusercontent.com/45097791/130216289-05e9d687-b461-4045-b2cb-73d898eec123.jpg)  
而且神奇的是，我用chrome浏览器打开就没有任何问题！  
之前一直用的QQ浏览器10.8.1 (4492)Chromium70.0.3538.25 \IE11.789.19041.0

**Comment by Candinya** [comment]
发现啦，是因为 QQ 浏览器内核版本老旧，不支持 `?.` 操作符导致哒，这个操作符在 Chrome 80 (Chromium 应该也是) 版本正式实装，导致之前版本的浏览器会出现错误问题的说w
![image](https://user-images.githubusercontent.com/20502130/130217671-67d0a993-ca27-486b-95d6-e5f1eb1f9793.png)

**Comment by fatal-scythe** [comment]
原来是这样！破案了...破案了...  
感谢作者大人帮忙回复！
