### ISSUE TITLE
Bug 回报：colorpanel 内叠加 collapse 会导致显示错误

### ISSUE THREAD

**Issue by BecodReyes** [Candinya/Kratos-Rebirth#86]
1. **对Bug的描述:**
colorpanel 内叠加 collapse 会导致显示错误

2. **复现Bug的方法:**
markdown：
```
{% colorpanel info 面板框的标题 %}
  {% collapse 折叠框的标题 open %}
  被折叠的内容 1
  被折叠的内容 2
  ...
  {% endcollapse %}
{% endcolorpanel %}
***
测试文字测试文字
{% colorpanel danger 面板框的标题 %}
  {% collapse 折叠框的标题 open %}
  被折叠的内容 1
  被折叠的内容 2
  ...
  {% endcollapse %}
{% endcolorpanel %}
```

3. **期望的行为:**
修复，正常显示

4. **相关的截图:**
![pic.png](https://inews.gtimg.com/newsapp_ls/0/13994815842/0)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
应该不需要

6. **补充内容:**
疑似collapse渲染成html后又被hexo使用markdown渲染引擎渲染

**Comment by BecodReyes** [comment]
已自行解决，加了`<span></span>`占位
神奇的bug 神奇的解决方法
发现是原本要结束div的地方被引擎转义了
```
<pre><code>&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
</code></pre>
```
```
// 折叠内容
hexo.extend.tag.register('collapse', function(args, content){
    content = hexo.render.renderSync({text: content, engine: 'markdown'});

    return `<div class="xControl${args[1] === 'open' ? ' active' : ''}">
    <div class="xHeading"><div class="xIcon"><i class="fa fa-plus"></i></div><span>${args[0]}</span></div>
    <div class="xContent${args[1] === 'open' ? ' pre-open' : ''}"><div class="inner">
        <span></span>${content}
    </div></div>
    </div>`;
}, {ends: true});
```

**Comment by BecodReyes** [comment]
反复测试后发现在引入代码块之后引擎渲染正常，主题版本https://github.com/Candinya/Kratos-Rebirth/commit/dce837fe3e40a9957dbd9c9b393b737dbbd3ff5e ，js层未作任何更改
```
{% colorpanel success 面板框的标题 %}
{% collapse 折叠框的标题 open %}
被折叠的内容 1
被折叠的内容 2

\```
\```
{% endcollapse %}
{% endcolorpanel %}

{% colorpanel success 面板框的标题 %}
{% collapse 折叠框的标题 open %}
被折叠的内容 1
被折叠的内容 2
{% endcollapse %}
{% endcolorpanel %}
```
![pic.png](http://inews.gtimg.com/newsapp_ls/0/13995060420/0)
![pic.png](http://inews.gtimg.com/newsapp_ls/0/13995066701/0)

**Comment by Candinya** [comment]
有趣的是这里似乎无法复现这个问题，能否请问一下您的 node 和 hexo 版本号呢

**Comment by BecodReyes** [comment]
> 有趣的是这里似乎无法复现这个问题，能否请问一下您的 node 和 hexo 版本号呢

```
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19043
node: 16.9.1
v8: 9.3.345.16-node.12
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 93
nghttp2: 1.42.0
napi: 8
llhttp: 6.0.2
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by Candinya** [comment]
不应该有问题…我的 `package.json` 中的版本是这些：

``` json
    "hexo": "^5.4.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-deployer-rss3": "^0.0.4",
    "hexo-filter-date-from-git": "^0.1.2",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-util": "^2.5.0",
    "highlight.js": "^11.1.0"
```

**Comment by BecodReyes** [comment]
除了`package.json`和`_config.yml`是沿用之前，其他均为全新安装
![image.png](https://inews.gtimg.com/newsapp_ls/0/13995130214/0)
```
    "hexo": "^5.0.0",
    "hexo-filter-flowchart": "^1.0.4",
    "hexo-filter-sequence": "^1.0.3",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-math": "^4.0.0",
    "hexo-neat": "^1.0.9",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3"
```

**Comment by BecodReyes** [comment]
这是我在gitpod全新安装测试的快照
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/94f17ab2-f613-4bfa-b76d-8005059727a9)

![image.png](https://inews.gtimg.com/newsapp_ls/0/13995142484/0)

**Comment by Candinya** [comment]
非常非常的奇怪，怀疑是和渲染器的渲染层级有关， code block 的出现部分改变了渲染行为（但还不够，并且可能导致其他异常的发生）

![image](https://user-images.githubusercontent.com/20502130/134059983-960dc27c-2b0d-4897-85ab-fdb619196d6f.png)
![image](https://user-images.githubusercontent.com/20502130/134060063-108e8bc5-346e-4bc9-9390-e1d6042d9ba0.png)
![image](https://user-images.githubusercontent.com/20502130/134060100-0aedacfc-a132-4f9c-89f3-62e5ae519c6d.png)
![image](https://user-images.githubusercontent.com/20502130/134060141-603b9408-8c53-4d84-ab77-4da23356b2da.png)
![image](https://user-images.githubusercontent.com/20502130/134060507-0e14904d-f7d8-4f31-a9b9-1ae6b3353144.png)
![image](https://user-images.githubusercontent.com/20502130/134060558-da8e0e2e-39f4-4044-8ca8-c92948f9948d.png)
![image](https://user-images.githubusercontent.com/20502130/134060598-d51b3aa3-215a-4ea0-b04b-4ed465a60f16.png)

**Comment by Candinya** [comment]
感觉这个可能和 Hexo 的渲染器的嵌套逻辑有关，应该并不属于主题设置的部分，因而暂时关闭该 issue ，如有后续跟进欢迎随时再次开启。
