### ISSUE TITLE
BUG回报：一旦我修改了_config.yml的文件hexo s就会报错

### ISSUE THREAD

**Issue by sarRikka** [Candinya/Kratos-Rebirth#87]
1. **对Bug的描述:**

![图片](https://user-images.githubusercontent.com/61453232/137434074-3563d3a1-feb2-474c-93a7-494ec23e0cc6.png)

2. **复现Bug的方法:**

3. **期望的行为:**

4. **相关的截图:**

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**

6. **补充内容:**

**Comment by Candinya** [comment]
![image](https://user-images.githubusercontent.com/20502130/137434170-f98039ec-c398-40c9-9966-d013fcec5c52.png)
`avatarUri` 和 `mobile_toc` 前不应有空格，此处加入空格会导致 yaml 格式错误。

**Comment by sarRikka** [comment]
成功解决，感谢作者大大~
