### ISSUE TITLE
希望能够支持gitalk

### ISSUE THREAD

**Issue by Ashitahe** [Candinya/Kratos-Rebirth#92]
1. **您的新功能建议是由使用时出现的不便引发的吗？**

2. **请描述您所设想的功能或是解决方案**

  **希望能够支持gitalk，这样就可以将评论区托管在仓库的issue里**

3. **补充内容:**

**Comment by Candinya** [comment]
应该已经加入了，可以拉取最新的代码进行尝试（记得注意更新配置文件中新增的 gitalk 配置段）
