### ISSUE TITLE
Bug 回报：waline评论报错

### ISSUE THREAD

**Issue by Swt2000** [Candinya/Kratos-Rebirth#93]
1. **对Bug的描述:**
waline服务器后端能提交评论，部署上博客之后报错如下:
Unexpected token < in JSON at position 5

**Comment by Candinya** [comment]
如果可以的话，希望您能根据 Bug 回报模板完整填写所有可能的信息（包括您的主题配置文件，请记得隐藏密码等私密内容），以便于我们的复现和调试排查，非常感谢您的帮助。

**Comment by Candinya** [comment]
您好，请问您遇到的问题还存在吗

**Comment by Candinya** [comment]
您好，由于暂时没有后续跟进，此 issue 将关闭。如您有任何后续跟进，欢迎随时再开启。
非常感谢您对本主题的喜欢和关注。
