### ISSUE TITLE
点击进入文章后banner和avatar的filename 改变导致 404 not found

### ISSUE THREAD

**Issue by VladmirLin** [Candinya/Kratos-Rebirth#97]
目前仅修改_config.yml中的avatar文件名为image/avatar.png 修改banner文件名为image/aph1.png，在首页时banner与avatar可正常加载，点击进入文章后filename中插入了文章目录名
eg：在http://localhost:4000/gorjevich-lin/Robomaster/Exterior-Ballistics.html中avatar.png的filename 变为
http://localhost:4000/gorjevich-lin/Robomaster/images/avatar.png

**Comment by Candinya** [comment]
avatar 的配置应该是绝对路径格式（`/`起始），您可以尝试检查一下。
https://github.com/Candinya/Kratos-Rebirth/blob/master/_config.yml.example#L130

**Comment by Candinya** [comment]
由于该 issue 长时间处于不活跃状态，因而暂行关闭，如有任何跟进您可随时重新开启，非常感谢您的帮助。
