### ISSUE TITLE
当文章存在层级目录时，进入阅读文章时，控制台出现（Cannot read properties of null (reading 'offsetTop')）【图一】错误，当点击层级目录时，控制台出现（Cannot read properties of undefined (reading 'top')）【图二】错误。

### ISSUE THREAD

**Issue by wi-gang** [Candinya/Kratos-Rebirth#98]
图一
![image](https://user-images.githubusercontent.com/46734261/149158641-397506e1-97ac-44b9-8354-dd1f4f437be1.png)

图二
![image](https://user-images.githubusercontent.com/46734261/149158707-9f74e49e-29cd-40e8-afbb-cdf3c0961f43.png)

测试文章
[5_test.md](https://github.com/Candinya/Kratos-Rebirth/files/7855301/5_test.md)

主题配置文件【我将yml文件改成了txt格式的文件，方便上传】
[_config.txt](https://github.com/Candinya/Kratos-Rebirth/files/7855288/_config.txt)

**Comment by Candinya** [comment]
确实存在问题，经过检查发现是一级标题的链接没有被正确生成导致的，不知道是 hexo 方面的问题还是主题调用 toc 函数时候出现的疏漏；目前追加了一个遇到错误临时解除所有折叠的方案（但体验会下降），暂时比较优雅的缓解办法是将所有的标题降一级（一级标题变二级，二级标题变三级，以此类推）以避开消失的链接。

相关的内容将保持进一步跟进。

![image](https://user-images.githubusercontent.com/20502130/149171758-721ca36e-5356-4099-acae-7eb7b3238d70.png)

**Comment by wi-gang** [comment]
标题降级后好像并不能缓解当前问题，没有任何效果。

**Comment by Candinya** [comment]
> 标题降级后好像并不能缓解当前问题，没有任何效果。

所有标题都降级了吗，请注意一级标题一个都不可以出现 👀

**Comment by wi-gang** [comment]
已确认，测试文件所有标题已降级。[吃瓜]
[6_test.md](https://github.com/Candinya/Kratos-Rebirth/files/7855914/6_test.md)

**Comment by Candinya** [comment]
不好意思我忘记 push 了 💦 
并且修复了一个新问题，是移动端目录样式在计算的时候没有被排除掉，导致当左侧边栏模式下会定位错误导致失效
可以再试一试了 💦

**Comment by wi-gang** [comment]
子级标题已显示，但是标题链接还是存在失效。
![image](https://user-images.githubusercontent.com/46734261/149182318-75e57aff-502c-4d2b-9ff0-31eab5d19359.png)

**Comment by Candinya** [comment]
> 子级标题已显示，但是标题链接还是存在失效。 ![image](https://user-images.githubusercontent.com/46734261/149182318-75e57aff-502c-4d2b-9ff0-31eab5d19359.png)

对的，因为出现了没有链接的标题。这些标题都降级了吗？

**Comment by wi-gang** [comment]
一级标题降级为二级标题，二级标题降级为三级标题.....所有标题都降了一级

**Comment by Candinya** [comment]
能否麻烦请问一下您本主题的本地 commit hash （以便确认是否为最新），和您的站点配置文件，以及 hexo 版本号信息（以便执行兼容性检查），方便这边的复现？

**Comment by wi-gang** [comment]
主题版本：
![image](https://user-images.githubusercontent.com/46734261/149657655-b332cc80-c6b8-4480-8d60-3d4b6350ffce.png)

站点版本：
![image](https://user-images.githubusercontent.com/46734261/149657661-c1a3bc2c-0ab1-40b0-abb3-98f838c86ae2.png)

站点配置文件：
[_config.txt](https://github.com/Candinya/Kratos-Rebirth/files/7876831/_config.txt)

**Comment by Candinya** [comment]
您好，我指的是主题的 **commit hash** ，您可在主题目录下运行 `git log` 查看，当前最新的 commit hash 应为 26e71c66027cf340dddd1c3f40f55e1936753f67 。如果您的本地结果不是这个，请考虑使用 `git pull` 等命令拉取最新的提交，以便测试提交而尚未发布的修复尝试。
![image](https://user-images.githubusercontent.com/20502130/149658188-a9ed1448-70d9-48a7-86a7-fdfe61b1d1fa.png)

**Comment by wi-gang** [comment]
![image](https://user-images.githubusercontent.com/46734261/149661849-c852d266-a1e6-4538-92b4-d3e7dcd74f5f.png)

**Comment by Candinya** [comment]
在主题更新后，您使用 `hexo clean` 清理本地缓存文件了吗

**Comment by wi-gang** [comment]
我不知道咋个回事，我这边现在没有问题了

**Comment by Candinya** [comment]
可能是缓存原因，没有问题了就好，非常感谢您的反馈和帮助 🎉

**Comment by qwx** [comment]
为了后续人查到这个问题不知道该怎么做，这里留一个问题排查过程：
Hexo渲染markdown的时候，header的id是由渲染引擎处理的，当你使用[hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it)这个引擎时，默认是2级及以上的层级目录生成ID，可以通过config配置，具体看渲染引擎仓库，但是我看默认引擎应该是会无视这一条规则。
