### ISSUE TITLE
部署主题后，访问浏览器显示partial

### ISSUE THREAD

**Issue by QinCode** [Candinya/Kratos-Rebirth#99]
1. 部署主题后访问页码出错
更新主题后，访问浏览器出现问题，如下：
![2](https://user-images.githubusercontent.com/47891956/154610973-2a35fcb4-1f62-47eb-97a2-0e207c950e77.png)

但使用其他主题可以正常访问，如下：
![5](https://user-images.githubusercontent.com/47891956/154611588-e0de5c7d-c98f-4d69-b2da-5001cb826dc8.png)

2. 复现
你好，在我刚搭建完hexo，想尝试一些主题效果，于是直接在github下载master分支的zip压缩包；
然后将其放至hexo 的 themes目录下解压，并复制重命名_config.yml文件
![1](https://user-images.githubusercontent.com/47891956/154610809-de2a11eb-eff1-40c4-bfe6-11a65e7f16e7.png)

修改hexo的_config.yml文件
![3](https://user-images.githubusercontent.com/47891956/154611216-9477612f-f634-4878-892d-b3d005c0727a.png)

执行hexo clean，hexo g，hexo d，hexo s
然后浏览器访问无法加载正确内容，出现异常：
![2](https://user-images.githubusercontent.com/47891956/154610973-2a35fcb4-1f62-47eb-97a2-0e207c950e77.png)

这是我的hexo版本信息：
![4](https://user-images.githubusercontent.com/47891956/154611464-cf1a1b74-7bdf-462c-b030-29581638e66b.png)

3. 问题
请问我的配置是否有什么问题，或者是否需要按照其他什么插件？

**Comment by QinCode** [comment]
或者说，主题里面的_config.yml 从github上下载下来后，不能直接使用而是要修改一些配置？

**Comment by Candinya** [comment]
这个是 `layout/layout.ejs` 文件的原始内容，看上去是缺少对应的 ejs 渲染器，能否麻烦帮忙检查一下 hexo 主目录下的 `package.json` 中是否带有 `hexo-renderer-ejs` 渲染器，如果没有的话可以尝试安装一下，清理之后再尝试生成？

**Comment by QinCode** [comment]
是缺少

**Comment by QinCode** [comment]
是缺少ejs 渲染器的问题，执行如下命令：
`npm install hexo-renderer-ejs --save`

再清理启动已经解决了，十分感谢
